// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (id, workspace_id, name, prefix, secret_hash, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, name, prefix, secret_hash, created_by, created_at, last_used_at, revoked_at
`

type CreateAPIKeyParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Prefix      string
	SecretHash  []byte
	CreatedBy   *uuid.UUID
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Prefix,
		arg.SecretHash,
		arg.CreatedBy,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Prefix,
		&i.SecretHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveAPIKeyByHash = `-- name: GetActiveAPIKeyByHash :one
SELECT id, workspace_id, name, prefix, secret_hash, created_by, created_at, last_used_at, revoked_at FROM api_keys WHERE secret_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetActiveAPIKeyByHash(ctx context.Context, secretHash []byte) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getActiveAPIKeyByHash, secretHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Prefix,
		&i.SecretHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, workspace_id, name, prefix, secret_hash, created_by, created_at, last_used_at, revoked_at FROM api_keys WHERE workspace_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListAPIKeys(ctx context.Context, workspaceID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Prefix,
			&i.SecretHash,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE api_keys SET revoked_at = coalesce(revoked_at, $1::timestamptz)
WHERE workspace_id = $2 AND id = $3
`

type RevokeAPIKeyParams struct {
	Now         time.Time
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIKey, arg.Now, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = $1::timestamptz
WHERE workspace_id = $2 AND id = $3
  AND (last_used_at IS NULL OR last_used_at < $4::timestamptz)
`

type TouchAPIKeyParams struct {
	Now         time.Time
	WorkspaceID uuid.UUID
	ID          uuid.UUID
	StaleBefore time.Time
}

func (q *Queries) TouchAPIKey(ctx context.Context, arg TouchAPIKeyParams) error {
	_, err := q.db.Exec(ctx, touchAPIKey,
		arg.Now,
		arg.WorkspaceID,
		arg.ID,
		arg.StaleBefore,
	)
	return err
}
