// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: canned_replies.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const createCannedReply = `-- name: CreateCannedReply :one
INSERT INTO canned_replies (id, workspace_id, shortcut, title, body, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $6)
RETURNING id, workspace_id, shortcut, title, body, created_at, updated_at
`

type CreateCannedReplyParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Shortcut    string
	Title       string
	Body        string
	Now         time.Time
}

func (q *Queries) CreateCannedReply(ctx context.Context, arg CreateCannedReplyParams) (CannedReply, error) {
	row := q.db.QueryRow(ctx, createCannedReply,
		arg.ID,
		arg.WorkspaceID,
		arg.Shortcut,
		arg.Title,
		arg.Body,
		arg.Now,
	)
	var i CannedReply
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Shortcut,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCannedReply = `-- name: DeleteCannedReply :execrows
DELETE FROM canned_replies WHERE workspace_id = $1 AND id = $2
`

type DeleteCannedReplyParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) DeleteCannedReply(ctx context.Context, arg DeleteCannedReplyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCannedReply, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCannedReply = `-- name: GetCannedReply :one
SELECT id, workspace_id, shortcut, title, body, created_at, updated_at FROM canned_replies WHERE workspace_id = $1 AND id = $2
`

type GetCannedReplyParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetCannedReply(ctx context.Context, arg GetCannedReplyParams) (CannedReply, error) {
	row := q.db.QueryRow(ctx, getCannedReply, arg.WorkspaceID, arg.ID)
	var i CannedReply
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Shortcut,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCannedReplies = `-- name: ListCannedReplies :many
SELECT id, workspace_id, shortcut, title, body, created_at, updated_at FROM canned_replies WHERE workspace_id = $1 ORDER BY shortcut
`

func (q *Queries) ListCannedReplies(ctx context.Context, workspaceID uuid.UUID) ([]CannedReply, error) {
	rows, err := q.db.Query(ctx, listCannedReplies, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CannedReply
	for rows.Next() {
		var i CannedReply
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Shortcut,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCannedReply = `-- name: UpdateCannedReply :one
UPDATE canned_replies SET shortcut = $1, title = $2, body = $3, updated_at = $4
WHERE workspace_id = $5 AND id = $6
RETURNING id, workspace_id, shortcut, title, body, created_at, updated_at
`

type UpdateCannedReplyParams struct {
	Shortcut    string
	Title       string
	Body        string
	Now         time.Time
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) UpdateCannedReply(ctx context.Context, arg UpdateCannedReplyParams) (CannedReply, error) {
	row := q.db.QueryRow(ctx, updateCannedReply,
		arg.Shortcut,
		arg.Title,
		arg.Body,
		arg.Now,
		arg.WorkspaceID,
		arg.ID,
	)
	var i CannedReply
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Shortcut,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
