// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (id, workspace_id, inbox_id, kind, name, settings, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $7)
RETURNING id, workspace_id, inbox_id, kind, name, settings, created_at, updated_at
`

type CreateChannelParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	InboxID     uuid.UUID
	Kind        string
	Name        string
	Settings    []byte
	Now         time.Time
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.ID,
		arg.WorkspaceID,
		arg.InboxID,
		arg.Kind,
		arg.Name,
		arg.Settings,
		arg.Now,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InboxID,
		&i.Kind,
		&i.Name,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM channels WHERE workspace_id = $1 AND id = $2
`

type DeleteChannelParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) DeleteChannel(ctx context.Context, arg DeleteChannelParams) error {
	_, err := q.db.Exec(ctx, deleteChannel, arg.WorkspaceID, arg.ID)
	return err
}

const getChannel = `-- name: GetChannel :one
SELECT id, workspace_id, inbox_id, kind, name, settings, created_at, updated_at FROM channels WHERE workspace_id = $1 AND id = $2
`

type GetChannelParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetChannel(ctx context.Context, arg GetChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannel, arg.WorkspaceID, arg.ID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InboxID,
		&i.Kind,
		&i.Name,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChannels = `-- name: ListChannels :many
SELECT id, workspace_id, inbox_id, kind, name, settings, created_at, updated_at FROM channels WHERE workspace_id = $1 AND inbox_id = $2 ORDER BY created_at, id
`

type ListChannelsParams struct {
	WorkspaceID uuid.UUID
	InboxID     uuid.UUID
}

func (q *Queries) ListChannels(ctx context.Context, arg ListChannelsParams) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listChannels, arg.WorkspaceID, arg.InboxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.InboxID,
			&i.Kind,
			&i.Name,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE channels SET name = $1, settings = $2, updated_at = $3
WHERE workspace_id = $4 AND id = $5
RETURNING id, workspace_id, inbox_id, kind, name, settings, created_at, updated_at
`

type UpdateChannelParams struct {
	Name        string
	Settings    []byte
	Now         time.Time
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, updateChannel,
		arg.Name,
		arg.Settings,
		arg.Now,
		arg.WorkspaceID,
		arg.ID,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InboxID,
		&i.Kind,
		&i.Name,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
