// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const anyChatChannelAllowsOrigin = `-- name: AnyChatChannelAllowsOrigin :one
SELECT EXISTS (
    SELECT 1 FROM chat_channels cc JOIN workspaces w ON w.id = cc.workspace_id
    WHERE cc.allowed_origins @> ARRAY[$1::text] AND w.deleted_at IS NULL
) AS allowed
`

// A CORS preflight carries neither the key nor the session (see "Hosting for others later").
func (q *Queries) AnyChatChannelAllowsOrigin(ctx context.Context, origin string) (bool, error) {
	row := q.db.QueryRow(ctx, anyChatChannelAllowsOrigin, origin)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const claimContinuity = `-- name: ClaimContinuity :exec
UPDATE conversations SET continuity_through = $1::timestamptz, continuity_sent_at = $2::timestamptz
WHERE workspace_id = $3 AND id = $4
`

type ClaimContinuityParams struct {
	Through     time.Time
	Now         time.Time
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) ClaimContinuity(ctx context.Context, arg ClaimContinuityParams) error {
	_, err := q.db.Exec(ctx, claimContinuity,
		arg.Through,
		arg.Now,
		arg.WorkspaceID,
		arg.ID,
	)
	return err
}

const closeConnection = `-- name: CloseConnection :exec
DELETE FROM realtime_connections WHERE workspace_id = $1 AND id = $2
`

type CloseConnectionParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) CloseConnection(ctx context.Context, arg CloseConnectionParams) error {
	_, err := q.db.Exec(ctx, closeConnection, arg.WorkspaceID, arg.ID)
	return err
}

const contactConnected = `-- name: ContactConnected :one
SELECT EXISTS (
    SELECT 1 FROM realtime_connections WHERE workspace_id = $1 AND contact_id = $2 AND seen_at > $3
) AS connected
`

type ContactConnectedParams struct {
	WorkspaceID uuid.UUID
	ContactID   *uuid.UUID
	FreshAfter  time.Time
}

func (q *Queries) ContactConnected(ctx context.Context, arg ContactConnectedParams) (bool, error) {
	row := q.db.QueryRow(ctx, contactConnected, arg.WorkspaceID, arg.ContactID, arg.FreshAfter)
	var connected bool
	err := row.Scan(&connected)
	return connected, err
}

const contactLastSeen = `-- name: ContactLastSeen :one
SELECT coalesce(max(last_seen_at), 'epoch')::timestamptz AS last_seen FROM contact_sessions WHERE workspace_id = $1 AND contact_id = $2
`

type ContactLastSeenParams struct {
	WorkspaceID uuid.UUID
	ContactID   uuid.UUID
}

func (q *Queries) ContactLastSeen(ctx context.Context, arg ContactLastSeenParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, contactLastSeen, arg.WorkspaceID, arg.ContactID)
	var last_seen time.Time
	err := row.Scan(&last_seen)
	return last_seen, err
}

const countContactEmails = `-- name: CountContactEmails :one
SELECT count(*) FROM contact_emails WHERE workspace_id = $1 AND contact_id = $2
`

type CountContactEmailsParams struct {
	WorkspaceID uuid.UUID
	ContactID   uuid.UUID
}

func (q *Queries) CountContactEmails(ctx context.Context, arg CountContactEmailsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countContactEmails, arg.WorkspaceID, arg.ContactID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEmailConfirmations = `-- name: CountEmailConfirmations :one
SELECT count(*) FROM email_confirmations WHERE workspace_id = $1 AND contact_id = $2 AND created_at > $3
`

type CountEmailConfirmationsParams struct {
	WorkspaceID uuid.UUID
	ContactID   uuid.UUID
	Since       time.Time
}

func (q *Queries) CountEmailConfirmations(ctx context.Context, arg CountEmailConfirmationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEmailConfirmations, arg.WorkspaceID, arg.ContactID, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChatVisitor = `-- name: CreateChatVisitor :exec
INSERT INTO chat_visitors (workspace_id, inbox_id, visitor_hash, contact_id, created_at) VALUES ($1, $2, $3, $4, $5)
`

type CreateChatVisitorParams struct {
	WorkspaceID uuid.UUID
	InboxID     uuid.UUID
	VisitorHash []byte
	ContactID   uuid.UUID
	CreatedAt   time.Time
}

func (q *Queries) CreateChatVisitor(ctx context.Context, arg CreateChatVisitorParams) error {
	_, err := q.db.Exec(ctx, createChatVisitor,
		arg.WorkspaceID,
		arg.InboxID,
		arg.VisitorHash,
		arg.ContactID,
		arg.CreatedAt,
	)
	return err
}

const createContactSession = `-- name: CreateContactSession :one
WITH s AS (
    INSERT INTO contact_sessions (id, workspace_id, channel_id, inbox_id, contact_id, token_hash, identified,
                                  created_at, expires_at, last_seen_at)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $8)
    RETURNING id, workspace_id, channel_id, inbox_id, contact_id, token_hash, identified, created_at, expires_at, last_seen_at),
seen AS (
    UPDATE contacts SET last_active_at = greatest(coalesce(contacts.last_active_at, s.last_seen_at), s.last_seen_at)
    FROM s WHERE contacts.workspace_id = s.workspace_id AND contacts.id = s.contact_id)
SELECT id, workspace_id, channel_id, inbox_id, contact_id, token_hash, identified, created_at, expires_at, last_seen_at FROM s
`

type CreateContactSessionParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	ChannelID   uuid.UUID
	InboxID     uuid.UUID
	ContactID   uuid.UUID
	TokenHash   []byte
	Identified  bool
	Now         time.Time
	ExpiresAt   time.Time
}

type CreateContactSessionRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	ChannelID   uuid.UUID
	InboxID     uuid.UUID
	ContactID   uuid.UUID
	TokenHash   []byte
	Identified  bool
	CreatedAt   time.Time
	ExpiresAt   time.Time
	LastSeenAt  time.Time
}

func (q *Queries) CreateContactSession(ctx context.Context, arg CreateContactSessionParams) (CreateContactSessionRow, error) {
	row := q.db.QueryRow(ctx, createContactSession,
		arg.ID,
		arg.WorkspaceID,
		arg.ChannelID,
		arg.InboxID,
		arg.ContactID,
		arg.TokenHash,
		arg.Identified,
		arg.Now,
		arg.ExpiresAt,
	)
	var i CreateContactSessionRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ChannelID,
		&i.InboxID,
		&i.ContactID,
		&i.TokenHash,
		&i.Identified,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
	)
	return i, err
}

const createEmailConfirmation = `-- name: CreateEmailConfirmation :exec
INSERT INTO email_confirmations (workspace_id, id, contact_id, inbox_id, email, token_hash, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateEmailConfirmationParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
	ContactID   uuid.UUID
	InboxID     uuid.UUID
	Email       string
	TokenHash   []byte
	Now         time.Time
	ExpiresAt   time.Time
}

func (q *Queries) CreateEmailConfirmation(ctx context.Context, arg CreateEmailConfirmationParams) error {
	_, err := q.db.Exec(ctx, createEmailConfirmation,
		arg.WorkspaceID,
		arg.ID,
		arg.ContactID,
		arg.InboxID,
		arg.Email,
		arg.TokenHash,
		arg.Now,
		arg.ExpiresAt,
	)
	return err
}

const deleteChatVisitor = `-- name: DeleteChatVisitor :exec
DELETE FROM chat_visitors WHERE workspace_id = $1 AND inbox_id = $2 AND visitor_hash = $3
`

type DeleteChatVisitorParams struct {
	WorkspaceID uuid.UUID
	InboxID     uuid.UUID
	VisitorHash []byte
}

func (q *Queries) DeleteChatVisitor(ctx context.Context, arg DeleteChatVisitorParams) error {
	_, err := q.db.Exec(ctx, deleteChatVisitor, arg.WorkspaceID, arg.InboxID, arg.VisitorHash)
	return err
}

const deleteContactEmailConfirmations = `-- name: DeleteContactEmailConfirmations :exec
DELETE FROM email_confirmations WHERE workspace_id = $1 AND (contact_id = $2 OR expires_at <= $3)
`

type DeleteContactEmailConfirmationsParams struct {
	WorkspaceID uuid.UUID
	ContactID   uuid.UUID
	Now         time.Time
}

func (q *Queries) DeleteContactEmailConfirmations(ctx context.Context, arg DeleteContactEmailConfirmationsParams) error {
	_, err := q.db.Exec(ctx, deleteContactEmailConfirmations, arg.WorkspaceID, arg.ContactID, arg.Now)
	return err
}

const deleteContactSession = `-- name: DeleteContactSession :exec
DELETE FROM contact_sessions WHERE workspace_id = $1 AND id = $2
`

type DeleteContactSessionParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) DeleteContactSession(ctx context.Context, arg DeleteContactSessionParams) error {
	_, err := q.db.Exec(ctx, deleteContactSession, arg.WorkspaceID, arg.ID)
	return err
}

const deleteExpiredContactSessions = `-- name: DeleteExpiredContactSessions :execrows
DELETE FROM contact_sessions WHERE workspace_id = $1 AND expires_at < $2
`

type DeleteExpiredContactSessionsParams struct {
	WorkspaceID uuid.UUID
	Before      time.Time
}

func (q *Queries) DeleteExpiredContactSessions(ctx context.Context, arg DeleteExpiredContactSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredContactSessions, arg.WorkspaceID, arg.Before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredIdentityTokenIDs = `-- name: DeleteExpiredIdentityTokenIDs :exec
DELETE FROM identity_token_ids WHERE workspace_id = $1 AND inbox_id = $2 AND expires_at <= $3
`

type DeleteExpiredIdentityTokenIDsParams struct {
	WorkspaceID uuid.UUID
	InboxID     uuid.UUID
	Now         time.Time
}

func (q *Queries) DeleteExpiredIdentityTokenIDs(ctx context.Context, arg DeleteExpiredIdentityTokenIDsParams) error {
	_, err := q.db.Exec(ctx, deleteExpiredIdentityTokenIDs, arg.WorkspaceID, arg.InboxID, arg.Now)
	return err
}

const deleteStaleConnections = `-- name: DeleteStaleConnections :execrows
DELETE FROM realtime_connections WHERE workspace_id = $1 AND seen_at < $2
`

type DeleteStaleConnectionsParams struct {
	WorkspaceID uuid.UUID
	Before      time.Time
}

func (q *Queries) DeleteStaleConnections(ctx context.Context, arg DeleteStaleConnectionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleConnections, arg.WorkspaceID, arg.Before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findChatChannelByKey = `-- name: FindChatChannelByKey :one
SELECT cc.workspace_id, cc.channel_id, cc.public_key, cc.allowed_origins, cc.allow_anonymous, cc.ask_email_offline, cc.greeting, cc.launcher_position, cc.launcher_color, cc.platforms, c.inbox_id, c.kind FROM chat_channels cc
JOIN channels c ON c.workspace_id = cc.workspace_id AND c.id = cc.channel_id
JOIN workspaces w ON w.id = cc.workspace_id
WHERE cc.public_key = $1 AND w.deleted_at IS NULL
`

type FindChatChannelByKeyRow struct {
	WorkspaceID      uuid.UUID
	ChannelID        uuid.UUID
	PublicKey        string
	AllowedOrigins   []string
	AllowAnonymous   bool
	AskEmailOffline  bool
	Greeting         string
	LauncherPosition *string
	LauncherColor    *string
	Platforms        []string
	InboxID          uuid.UUID
	Kind             string
}

// The widget names only the channel's public key, so the channel is found before the workspace is
// known (see "Hosting for others later" in docs/architecture.md).
func (q *Queries) FindChatChannelByKey(ctx context.Context, publicKey string) (FindChatChannelByKeyRow, error) {
	row := q.db.QueryRow(ctx, findChatChannelByKey, publicKey)
	var i FindChatChannelByKeyRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.ChannelID,
		&i.PublicKey,
		&i.AllowedOrigins,
		&i.AllowAnonymous,
		&i.AskEmailOffline,
		&i.Greeting,
		&i.LauncherPosition,
		&i.LauncherColor,
		&i.Platforms,
		&i.InboxID,
		&i.Kind,
	)
	return i, err
}

const findContactMessageByClientID = `-- name: FindContactMessageByClientID :one
SELECT m.id, m.conversation_id FROM messages m
JOIN conversations c ON c.workspace_id = m.workspace_id AND c.id = m.conversation_id
WHERE m.workspace_id = $1 AND c.inbox_id = $2 AND c.contact_id = $3
  AND m.author_contact_id = $3 AND m.client_id = $4::text
ORDER BY m.created_at DESC
LIMIT 1
`

type FindContactMessageByClientIDParams struct {
	WorkspaceID uuid.UUID
	InboxID     uuid.UUID
	ContactID   uuid.UUID
	ClientID    string
}

type FindContactMessageByClientIDRow struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
}

func (q *Queries) FindContactMessageByClientID(ctx context.Context, arg FindContactMessageByClientIDParams) (FindContactMessageByClientIDRow, error) {
	row := q.db.QueryRow(ctx, findContactMessageByClientID,
		arg.WorkspaceID,
		arg.InboxID,
		arg.ContactID,
		arg.ClientID,
	)
	var i FindContactMessageByClientIDRow
	err := row.Scan(&i.ID, &i.ConversationID)
	return i, err
}

const findThreadSentTo = `-- name: FindThreadSentTo :one
SELECT c.contact_id FROM message_emails e
JOIN conversations c ON c.workspace_id = e.workspace_id AND c.id = e.conversation_id
WHERE e.workspace_id = $1 AND c.inbox_id = $2 AND e.direction = 'out'
  AND e.header_message_id = ANY($3::text[]) AND $4::text = ANY(e.to_addresses)
ORDER BY e.created_at DESC, e.message_id DESC
LIMIT 1
`

type FindThreadSentToParams struct {
	WorkspaceID uuid.UUID
	InboxID     uuid.UUID
	Ids         []string
	Address     string
}

func (q *Queries) FindThreadSentTo(ctx context.Context, arg FindThreadSentToParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findThreadSentTo,
		arg.WorkspaceID,
		arg.InboxID,
		arg.Ids,
		arg.Address,
	)
	var contact_id uuid.UUID
	err := row.Scan(&contact_id)
	return contact_id, err
}

const getChatChannel = `-- name: GetChatChannel :one
SELECT workspace_id, channel_id, public_key, allowed_origins, allow_anonymous, ask_email_offline, greeting, launcher_position, launcher_color, platforms FROM chat_channels WHERE workspace_id = $1 AND channel_id = $2
`

type GetChatChannelParams struct {
	WorkspaceID uuid.UUID
	ChannelID   uuid.UUID
}

func (q *Queries) GetChatChannel(ctx context.Context, arg GetChatChannelParams) (ChatChannel, error) {
	row := q.db.QueryRow(ctx, getChatChannel, arg.WorkspaceID, arg.ChannelID)
	var i ChatChannel
	err := row.Scan(
		&i.WorkspaceID,
		&i.ChannelID,
		&i.PublicKey,
		&i.AllowedOrigins,
		&i.AllowAnonymous,
		&i.AskEmailOffline,
		&i.Greeting,
		&i.LauncherPosition,
		&i.LauncherColor,
		&i.Platforms,
	)
	return i, err
}

const getChatVisitor = `-- name: GetChatVisitor :one
SELECT contact_id FROM chat_visitors WHERE workspace_id = $1 AND inbox_id = $2 AND visitor_hash = $3
`

type GetChatVisitorParams struct {
	WorkspaceID uuid.UUID
	InboxID     uuid.UUID
	VisitorHash []byte
}

func (q *Queries) GetChatVisitor(ctx context.Context, arg GetChatVisitorParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getChatVisitor, arg.WorkspaceID, arg.InboxID, arg.VisitorHash)
	var contact_id uuid.UUID
	err := row.Scan(&contact_id)
	return contact_id, err
}

const getClientAttachment = `-- name: GetClientAttachment :one
SELECT a.id, a.workspace_id, a.conversation_id, a.message_id, a.storage_key, a.filename, a.content_type, a.size_bytes, a.created_at, a.content_id, a.inline FROM attachments a
JOIN messages m ON m.workspace_id = a.workspace_id AND m.id = a.message_id
JOIN conversations c ON c.workspace_id = a.workspace_id AND c.id = a.conversation_id
WHERE a.workspace_id = $1 AND a.id = $2 AND m.kind = 'message' AND NOT m.draft
  AND c.inbox_id = $3 AND c.contact_id = $4
`

type GetClientAttachmentParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
	InboxID     uuid.UUID
	ContactID   uuid.UUID
}

func (q *Queries) GetClientAttachment(ctx context.Context, arg GetClientAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, getClientAttachment,
		arg.WorkspaceID,
		arg.ID,
		arg.InboxID,
		arg.ContactID,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ConversationID,
		&i.MessageID,
		&i.StorageKey,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.ContentID,
		&i.Inline,
	)
	return i, err
}

const getContactRead = `-- name: GetContactRead :one
SELECT workspace_id, conversation_id, last_read_message_id, last_read_at, updated_at FROM contact_reads WHERE workspace_id = $1 AND conversation_id = $2
`

type GetContactReadParams struct {
	WorkspaceID    uuid.UUID
	ConversationID uuid.UUID
}

func (q *Queries) GetContactRead(ctx context.Context, arg GetContactReadParams) (ContactRead, error) {
	row := q.db.QueryRow(ctx, getContactRead, arg.WorkspaceID, arg.ConversationID)
	var i ContactRead
	err := row.Scan(
		&i.WorkspaceID,
		&i.ConversationID,
		&i.LastReadMessageID,
		&i.LastReadAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContactSessionByTokenHash = `-- name: GetContactSessionByTokenHash :one
SELECT s.id, s.workspace_id, s.channel_id, s.inbox_id, s.contact_id, s.token_hash, s.identified, s.created_at, s.expires_at, s.last_seen_at, ct.blocked AS contact_blocked FROM contact_sessions s
JOIN contacts ct ON ct.workspace_id = s.workspace_id AND ct.id = s.contact_id
JOIN workspaces w ON w.id = s.workspace_id
WHERE s.token_hash = $1 AND s.expires_at > $2 AND w.deleted_at IS NULL
`

type GetContactSessionByTokenHashParams struct {
	TokenHash []byte
	ExpiresAt time.Time
}

type GetContactSessionByTokenHashRow struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	ChannelID      uuid.UUID
	InboxID        uuid.UUID
	ContactID      uuid.UUID
	TokenHash      []byte
	Identified     bool
	CreatedAt      time.Time
	ExpiresAt      time.Time
	LastSeenAt     time.Time
	ContactBlocked bool
}

// A contact session token names no workspace (see "Hosting for others later").
func (q *Queries) GetContactSessionByTokenHash(ctx context.Context, arg GetContactSessionByTokenHashParams) (GetContactSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getContactSessionByTokenHash, arg.TokenHash, arg.ExpiresAt)
	var i GetContactSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ChannelID,
		&i.InboxID,
		&i.ContactID,
		&i.TokenHash,
		&i.Identified,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.ContactBlocked,
	)
	return i, err
}

const getEmailConfirmation = `-- name: GetEmailConfirmation :one
SELECT contact_id, inbox_id, email FROM email_confirmations
WHERE workspace_id = $1 AND token_hash = $2 AND expires_at > $3
`

type GetEmailConfirmationParams struct {
	WorkspaceID uuid.UUID
	TokenHash   []byte
	Now         time.Time
}

type GetEmailConfirmationRow struct {
	ContactID uuid.UUID
	InboxID   uuid.UUID
	Email     string
}

func (q *Queries) GetEmailConfirmation(ctx context.Context, arg GetEmailConfirmationParams) (GetEmailConfirmationRow, error) {
	row := q.db.QueryRow(ctx, getEmailConfirmation, arg.WorkspaceID, arg.TokenHash, arg.Now)
	var i GetEmailConfirmationRow
	err := row.Scan(&i.ContactID, &i.InboxID, &i.Email)
	return i, err
}

const getLatestPublicMessagePosition = `-- name: GetLatestPublicMessagePosition :one
SELECT id, created_at FROM messages WHERE workspace_id = $1 AND conversation_id = $2 AND kind = 'message' AND NOT draft
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type GetLatestPublicMessagePositionParams struct {
	WorkspaceID    uuid.UUID
	ConversationID uuid.UUID
}

type GetLatestPublicMessagePositionRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) GetLatestPublicMessagePosition(ctx context.Context, arg GetLatestPublicMessagePositionParams) (GetLatestPublicMessagePositionRow, error) {
	row := q.db.QueryRow(ctx, getLatestPublicMessagePosition, arg.WorkspaceID, arg.ConversationID)
	var i GetLatestPublicMessagePositionRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getSessionChannel = `-- name: GetSessionChannel :one
SELECT cc.workspace_id, cc.channel_id, cc.public_key, cc.allowed_origins, cc.allow_anonymous, cc.ask_email_offline, cc.greeting, cc.launcher_position, cc.launcher_color, cc.platforms, c.kind FROM chat_channels cc
JOIN channels c ON c.workspace_id = cc.workspace_id AND c.id = cc.channel_id
WHERE cc.workspace_id = $1 AND cc.channel_id = $2
`

type GetSessionChannelParams struct {
	WorkspaceID uuid.UUID
	ChannelID   uuid.UUID
}

type GetSessionChannelRow struct {
	WorkspaceID      uuid.UUID
	ChannelID        uuid.UUID
	PublicKey        string
	AllowedOrigins   []string
	AllowAnonymous   bool
	AskEmailOffline  bool
	Greeting         string
	LauncherPosition *string
	LauncherColor    *string
	Platforms        []string
	Kind             string
}

func (q *Queries) GetSessionChannel(ctx context.Context, arg GetSessionChannelParams) (GetSessionChannelRow, error) {
	row := q.db.QueryRow(ctx, getSessionChannel, arg.WorkspaceID, arg.ChannelID)
	var i GetSessionChannelRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.ChannelID,
		&i.PublicKey,
		&i.AllowedOrigins,
		&i.AllowAnonymous,
		&i.AskEmailOffline,
		&i.Greeting,
		&i.LauncherPosition,
		&i.LauncherColor,
		&i.Platforms,
		&i.Kind,
	)
	return i, err
}

const inboxEmailChannel = `-- name: InboxEmailChannel :one
SELECT e.workspace_id, e.channel_id, e.address, e.display_name, e.from_address, e.smtp_host, e.smtp_port, e.smtp_username, e.smtp_password, e.smtp_tls, e.auto_reply_enabled, e.auto_reply_text, e.auto_reply_interval_hours FROM email_channels e
JOIN channels c ON c.workspace_id = e.workspace_id AND c.id = e.channel_id
WHERE e.workspace_id = $1 AND c.inbox_id = $2
ORDER BY (e.address LIKE '*@%'), c.created_at, c.id
LIMIT 1
`

type InboxEmailChannelParams struct {
	WorkspaceID uuid.UUID
	InboxID     uuid.UUID
}

func (q *Queries) InboxEmailChannel(ctx context.Context, arg InboxEmailChannelParams) (EmailChannel, error) {
	row := q.db.QueryRow(ctx, inboxEmailChannel, arg.WorkspaceID, arg.InboxID)
	var i EmailChannel
	err := row.Scan(
		&i.WorkspaceID,
		&i.ChannelID,
		&i.Address,
		&i.DisplayName,
		&i.FromAddress,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpUsername,
		&i.SmtpPassword,
		&i.SmtpTls,
		&i.AutoReplyEnabled,
		&i.AutoReplyText,
		&i.AutoReplyIntervalHours,
	)
	return i, err
}

const isChatVisitor = `-- name: IsChatVisitor :one
SELECT EXISTS (SELECT 1 FROM chat_visitors WHERE workspace_id = $1 AND contact_id = $2) AS visitor
`

type IsChatVisitorParams struct {
	WorkspaceID uuid.UUID
	ContactID   uuid.UUID
}

func (q *Queries) IsChatVisitor(ctx context.Context, arg IsChatVisitorParams) (bool, error) {
	row := q.db.QueryRow(ctx, isChatVisitor, arg.WorkspaceID, arg.ContactID)
	var visitor bool
	err := row.Scan(&visitor)
	return visitor, err
}

const listAvailableMembers = `-- name: ListAvailableMembers :many
SELECT DISTINCT ON (m.id) m.id, p.name, m.created_at FROM realtime_connections rc
JOIN members m ON m.workspace_id = rc.workspace_id AND m.id = rc.member_id
JOIN people p ON p.id = m.person_id
WHERE rc.workspace_id = $1 AND rc.seen_at > $2 AND p.availability = 'auto'
  AND (m.role IN ('owner', 'admin') OR EXISTS (
      SELECT 1 FROM inbox_members im
      WHERE im.workspace_id = m.workspace_id AND im.inbox_id = $3 AND im.member_id = m.id))
ORDER BY m.id
`

type ListAvailableMembersParams struct {
	WorkspaceID uuid.UUID
	FreshAfter  time.Time
	InboxID     uuid.UUID
}

type ListAvailableMembersRow struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

func (q *Queries) ListAvailableMembers(ctx context.Context, arg ListAvailableMembersParams) ([]ListAvailableMembersRow, error) {
	rows, err := q.db.Query(ctx, listAvailableMembers, arg.WorkspaceID, arg.FreshAfter, arg.InboxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAvailableMembersRow
	for rows.Next() {
		var i ListAvailableMembersRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatChannels = `-- name: ListChatChannels :many
SELECT workspace_id, channel_id, public_key, allowed_origins, allow_anonymous, ask_email_offline, greeting, launcher_position, launcher_color, platforms FROM chat_channels WHERE workspace_id = $1 AND channel_id = ANY($2::uuid[])
`

type ListChatChannelsParams struct {
	WorkspaceID uuid.UUID
	ChannelIds  []uuid.UUID
}

func (q *Queries) ListChatChannels(ctx context.Context, arg ListChatChannelsParams) ([]ChatChannel, error) {
	rows, err := q.db.Query(ctx, listChatChannels, arg.WorkspaceID, arg.ChannelIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatChannel
	for rows.Next() {
		var i ChatChannel
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ChannelID,
			&i.PublicKey,
			&i.AllowedOrigins,
			&i.AllowAnonymous,
			&i.AskEmailOffline,
			&i.Greeting,
			&i.LauncherPosition,
			&i.LauncherColor,
			&i.Platforms,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactConversationIDs = `-- name: ListContactConversationIDs :many
SELECT id, status FROM conversations WHERE workspace_id = $1 AND inbox_id = $2 AND contact_id = $3
`

type ListContactConversationIDsParams struct {
	WorkspaceID uuid.UUID
	InboxID     uuid.UUID
	ContactID   uuid.UUID
}

type ListContactConversationIDsRow struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) ListContactConversationIDs(ctx context.Context, arg ListContactConversationIDsParams) ([]ListContactConversationIDsRow, error) {
	rows, err := q.db.Query(ctx, listContactConversationIDs, arg.WorkspaceID, arg.InboxID, arg.ContactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContactConversationIDsRow
	for rows.Next() {
		var i ListContactConversationIDsRow
		if err := rows.Scan(&i.ID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactConversations = `-- name: ListContactConversations :many
SELECT c.id, c.workspace_id, c.inbox_id, c.contact_id, c.channel_id, c.subject, c.status, c.snooze_until, c.priority, c.assignee_id, c.last_message_at, c.last_activity_at, c.created_at, c.updated_at, c.spam, c.email_token, c.related_conversation_id, c.continuity_through, c.continuity_sent_at, c.kind, c.feedback, c.email_address, c.closed_at, c.rating, c.rating_comment, c.rated_at, c.rating_requested_at FROM conversations c
WHERE c.workspace_id = $1 AND c.inbox_id = $2 AND c.contact_id = $3
  AND ($4::timestamptz IS NULL
       OR (coalesce(c.last_message_at, c.created_at), c.id) < ($4::timestamptz, $5::uuid))
ORDER BY coalesce(c.last_message_at, c.created_at) DESC, c.id DESC
LIMIT $6
`

type ListContactConversationsParams struct {
	WorkspaceID uuid.UUID
	InboxID     uuid.UUID
	ContactID   uuid.UUID
	CursorAt    *time.Time
	CursorID    *uuid.UUID
	Lim         int32
}

func (q *Queries) ListContactConversations(ctx context.Context, arg ListContactConversationsParams) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listContactConversations,
		arg.WorkspaceID,
		arg.InboxID,
		arg.ContactID,
		arg.CursorAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.InboxID,
			&i.ContactID,
			&i.ChannelID,
			&i.Subject,
			&i.Status,
			&i.SnoozeUntil,
			&i.Priority,
			&i.AssigneeID,
			&i.LastMessageAt,
			&i.LastActivityAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Spam,
			&i.EmailToken,
			&i.RelatedConversationID,
			&i.ContinuityThrough,
			&i.ContinuitySentAt,
			&i.Kind,
			&i.Feedback,
			&i.EmailAddress,
			&i.ClosedAt,
			&i.Rating,
			&i.RatingComment,
			&i.RatedAt,
			&i.RatingRequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationsWithPendingReplies = `-- name: ListConversationsWithPendingReplies :many
SELECT DISTINCT c.id FROM conversations c
JOIN messages m ON m.workspace_id = c.workspace_id AND m.conversation_id = c.id
LEFT JOIN contact_reads r ON r.workspace_id = c.workspace_id AND r.conversation_id = c.id
WHERE c.workspace_id = $1 AND c.contact_id = $2
  AND m.kind = 'message' AND m.direction = 'out' AND m.author_type = 'member' AND m.delivery_state IS NULL AND NOT m.draft
  AND (r.last_read_at IS NULL OR (m.created_at, m.id) > (r.last_read_at, r.last_read_message_id))
  AND (c.continuity_through IS NULL OR m.created_at > c.continuity_through)
`

type ListConversationsWithPendingRepliesParams struct {
	WorkspaceID uuid.UUID
	ContactID   uuid.UUID
}

func (q *Queries) ListConversationsWithPendingReplies(ctx context.Context, arg ListConversationsWithPendingRepliesParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listConversationsWithPendingReplies, arg.WorkspaceID, arg.ContactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberNames = `-- name: ListMemberNames :many
SELECT m.id, p.name FROM members m JOIN people p ON p.id = m.person_id
WHERE m.workspace_id = $1 AND m.id = ANY($2::uuid[])
`

type ListMemberNamesParams struct {
	WorkspaceID uuid.UUID
	Ids         []uuid.UUID
}

type ListMemberNamesRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) ListMemberNames(ctx context.Context, arg ListMemberNamesParams) ([]ListMemberNamesRow, error) {
	rows, err := q.db.Query(ctx, listMemberNames, arg.WorkspaceID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMemberNamesRow
	for rows.Next() {
		var i ListMemberNamesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberReadPositions = `-- name: ListMemberReadPositions :many
SELECT r.conversation_id, max(r.last_read_at)::timestamptz AS read_at
FROM conversation_reads r
JOIN conversations c ON c.workspace_id = r.workspace_id AND c.id = r.conversation_id
JOIN inboxes i ON i.workspace_id = c.workspace_id AND i.id = c.inbox_id
WHERE r.workspace_id = $1 AND r.conversation_id = ANY($2::uuid[]) AND i.mode = 'live'
GROUP BY r.conversation_id
`

type ListMemberReadPositionsParams struct {
	WorkspaceID     uuid.UUID
	ConversationIds []uuid.UUID
}

type ListMemberReadPositionsRow struct {
	ConversationID uuid.UUID
	ReadAt         time.Time
}

func (q *Queries) ListMemberReadPositions(ctx context.Context, arg ListMemberReadPositionsParams) ([]ListMemberReadPositionsRow, error) {
	rows, err := q.db.Query(ctx, listMemberReadPositions, arg.WorkspaceID, arg.ConversationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMemberReadPositionsRow
	for rows.Next() {
		var i ListMemberReadPositionsRow
		if err := rows.Scan(&i.ConversationID, &i.ReadAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingReplies = `-- name: ListPendingReplies :many
SELECT m.id, m.created_at FROM messages m
JOIN conversations c ON c.workspace_id = m.workspace_id AND c.id = m.conversation_id
LEFT JOIN contact_reads r ON r.workspace_id = m.workspace_id AND r.conversation_id = m.conversation_id
WHERE m.workspace_id = $1 AND m.conversation_id = $2
  AND m.kind = 'message' AND m.direction = 'out' AND m.author_type = 'member' AND m.delivery_state IS NULL AND NOT m.draft
  AND (r.last_read_at IS NULL OR (m.created_at, m.id) > (r.last_read_at, r.last_read_message_id))
  AND (c.continuity_through IS NULL OR m.created_at > c.continuity_through)
ORDER BY m.created_at, m.id
LIMIT 50
`

type ListPendingRepliesParams struct {
	WorkspaceID    uuid.UUID
	ConversationID uuid.UUID
}

type ListPendingRepliesRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) ListPendingReplies(ctx context.Context, arg ListPendingRepliesParams) ([]ListPendingRepliesRow, error) {
	rows, err := q.db.Query(ctx, listPendingReplies, arg.WorkspaceID, arg.ConversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingRepliesRow
	for rows.Next() {
		var i ListPendingRepliesRow
		if err := rows.Scan(&i.ID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonWorkspaceIDs = `-- name: ListPersonWorkspaceIDs :many
SELECT m.workspace_id FROM members m JOIN workspaces w ON w.id = m.workspace_id
WHERE m.person_id = $1 AND w.deleted_at IS NULL
`

func (q *Queries) ListPersonWorkspaceIDs(ctx context.Context, personID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listPersonWorkspaceIDs, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var workspace_id uuid.UUID
		if err := rows.Scan(&workspace_id); err != nil {
			return nil, err
		}
		items = append(items, workspace_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicMessages = `-- name: ListPublicMessages :many
SELECT m.id, m.workspace_id, m.conversation_id, m.kind, m.direction, m.author_type, m.author_member_id,
       m.author_contact_id, m.body, m.html, m.client_id, m.event, m.created_at, m.delivery_state, m.delivery_error,
       m.delivery_updated_at, m.author_api_key_id, m.draft, m.sent_by_member_id, m.sent_by_api_key_id, m.via, m.sent_via, m.mentions,
       coalesce(ak.bot_name, ak.name, '')::text AS bot_name, coalesce(ak.bot_avatar_url, '')::text AS bot_avatar_url,
       coalesce(sk.bot_name, sk.name, '')::text AS sent_by_bot_name
FROM messages m
LEFT JOIN api_keys ak ON ak.workspace_id = m.workspace_id AND ak.id = m.author_api_key_id
LEFT JOIN api_keys sk ON sk.workspace_id = m.workspace_id AND sk.id = m.sent_by_api_key_id
WHERE m.workspace_id = $1 AND m.conversation_id = $2 AND m.kind = 'message' AND NOT m.draft
  AND ($3::timestamptz IS NULL
       OR (m.created_at, m.id) > ($3::timestamptz, $4::uuid))
ORDER BY m.created_at, m.id
LIMIT $5
`

type ListPublicMessagesParams struct {
	WorkspaceID    uuid.UUID
	ConversationID uuid.UUID
	CursorAt       *time.Time
	CursorID       *uuid.UUID
	Lim            int32
}

type ListPublicMessagesRow struct {
	ID                uuid.UUID
	WorkspaceID       uuid.UUID
	ConversationID    uuid.UUID
	Kind              string
	Direction         *string
	AuthorType        string
	AuthorMemberID    *uuid.UUID
	AuthorContactID   *uuid.UUID
	Body              string
	Html              *string
	ClientID          *string
	Event             []byte
	CreatedAt         time.Time
	DeliveryState     *string
	DeliveryError     *string
	DeliveryUpdatedAt *time.Time
	AuthorApiKeyID    *uuid.UUID
	Draft             bool
	SentByMemberID    *uuid.UUID
	SentByApiKeyID    *uuid.UUID
	Via               *string
	SentVia           *string
	Mentions          []uuid.UUID
	BotName           string
	BotAvatarUrl      string
	SentByBotName     string
}

func (q *Queries) ListPublicMessages(ctx context.Context, arg ListPublicMessagesParams) ([]ListPublicMessagesRow, error) {
	rows, err := q.db.Query(ctx, listPublicMessages,
		arg.WorkspaceID,
		arg.ConversationID,
		arg.CursorAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicMessagesRow
	for rows.Next() {
		var i ListPublicMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ConversationID,
			&i.Kind,
			&i.Direction,
			&i.AuthorType,
			&i.AuthorMemberID,
			&i.AuthorContactID,
			&i.Body,
			&i.Html,
			&i.ClientID,
			&i.Event,
			&i.CreatedAt,
			&i.DeliveryState,
			&i.DeliveryError,
			&i.DeliveryUpdatedAt,
			&i.AuthorApiKeyID,
			&i.Draft,
			&i.SentByMemberID,
			&i.SentByApiKeyID,
			&i.Via,
			&i.SentVia,
			&i.Mentions,
			&i.BotName,
			&i.BotAvatarUrl,
			&i.SentByBotName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicMessagesDesc = `-- name: ListPublicMessagesDesc :many
SELECT m.id, m.workspace_id, m.conversation_id, m.kind, m.direction, m.author_type, m.author_member_id,
       m.author_contact_id, m.body, m.html, m.client_id, m.event, m.created_at, m.delivery_state, m.delivery_error,
       m.delivery_updated_at, m.author_api_key_id, m.draft, m.sent_by_member_id, m.sent_by_api_key_id, m.via, m.sent_via, m.mentions,
       coalesce(ak.bot_name, ak.name, '')::text AS bot_name, coalesce(ak.bot_avatar_url, '')::text AS bot_avatar_url,
       coalesce(sk.bot_name, sk.name, '')::text AS sent_by_bot_name
FROM messages m
LEFT JOIN api_keys ak ON ak.workspace_id = m.workspace_id AND ak.id = m.author_api_key_id
LEFT JOIN api_keys sk ON sk.workspace_id = m.workspace_id AND sk.id = m.sent_by_api_key_id
WHERE m.workspace_id = $1 AND m.conversation_id = $2 AND m.kind = 'message' AND NOT m.draft
  AND ($3::timestamptz IS NULL
       OR (m.created_at, m.id) < ($3::timestamptz, $4::uuid))
ORDER BY m.created_at DESC, m.id DESC
LIMIT $5
`

type ListPublicMessagesDescParams struct {
	WorkspaceID    uuid.UUID
	ConversationID uuid.UUID
	CursorAt       *time.Time
	CursorID       *uuid.UUID
	Lim            int32
}

type ListPublicMessagesDescRow struct {
	ID                uuid.UUID
	WorkspaceID       uuid.UUID
	ConversationID    uuid.UUID
	Kind              string
	Direction         *string
	AuthorType        string
	AuthorMemberID    *uuid.UUID
	AuthorContactID   *uuid.UUID
	Body              string
	Html              *string
	ClientID          *string
	Event             []byte
	CreatedAt         time.Time
	DeliveryState     *string
	DeliveryError     *string
	DeliveryUpdatedAt *time.Time
	AuthorApiKeyID    *uuid.UUID
	Draft             bool
	SentByMemberID    *uuid.UUID
	SentByApiKeyID    *uuid.UUID
	Via               *string
	SentVia           *string
	Mentions          []uuid.UUID
	BotName           string
	BotAvatarUrl      string
	SentByBotName     string
}

func (q *Queries) ListPublicMessagesDesc(ctx context.Context, arg ListPublicMessagesDescParams) ([]ListPublicMessagesDescRow, error) {
	rows, err := q.db.Query(ctx, listPublicMessagesDesc,
		arg.WorkspaceID,
		arg.ConversationID,
		arg.CursorAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicMessagesDescRow
	for rows.Next() {
		var i ListPublicMessagesDescRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ConversationID,
			&i.Kind,
			&i.Direction,
			&i.AuthorType,
			&i.AuthorMemberID,
			&i.AuthorContactID,
			&i.Body,
			&i.Html,
			&i.ClientID,
			&i.Event,
			&i.CreatedAt,
			&i.DeliveryState,
			&i.DeliveryError,
			&i.DeliveryUpdatedAt,
			&i.AuthorApiKeyID,
			&i.Draft,
			&i.SentByMemberID,
			&i.SentByApiKeyID,
			&i.Via,
			&i.SentVia,
			&i.Mentions,
			&i.BotName,
			&i.BotAvatarUrl,
			&i.SentByBotName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadForContact = `-- name: ListUnreadForContact :many
SELECT c.id FROM conversations c
LEFT JOIN contact_reads r ON r.workspace_id = c.workspace_id AND r.conversation_id = c.id
WHERE c.workspace_id = $1 AND c.id = ANY($2::uuid[])
  AND EXISTS (
      SELECT 1 FROM messages m
      WHERE m.workspace_id = c.workspace_id AND m.conversation_id = c.id
        AND m.kind = 'message' AND m.direction = 'out' AND NOT m.draft
        AND (r.last_read_at IS NULL OR (m.created_at, m.id) > (r.last_read_at, r.last_read_message_id)))
`

type ListUnreadForContactParams struct {
	WorkspaceID     uuid.UUID
	ConversationIds []uuid.UUID
}

func (q *Queries) ListUnreadForContact(ctx context.Context, arg ListUnreadForContactParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUnreadForContact, arg.WorkspaceID, arg.ConversationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markContactRead = `-- name: MarkContactRead :one
INSERT INTO contact_reads (workspace_id, conversation_id, last_read_message_id, last_read_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (workspace_id, conversation_id) DO UPDATE
SET last_read_message_id = excluded.last_read_message_id, last_read_at = excluded.last_read_at, updated_at = excluded.updated_at
WHERE (contact_reads.last_read_at, contact_reads.last_read_message_id) < (excluded.last_read_at, excluded.last_read_message_id)
RETURNING workspace_id, conversation_id, last_read_message_id, last_read_at, updated_at
`

type MarkContactReadParams struct {
	WorkspaceID    uuid.UUID
	ConversationID uuid.UUID
	MessageID      uuid.UUID
	MessageAt      time.Time
	Now            time.Time
}

func (q *Queries) MarkContactRead(ctx context.Context, arg MarkContactReadParams) (ContactRead, error) {
	row := q.db.QueryRow(ctx, markContactRead,
		arg.WorkspaceID,
		arg.ConversationID,
		arg.MessageID,
		arg.MessageAt,
		arg.Now,
	)
	var i ContactRead
	err := row.Scan(
		&i.WorkspaceID,
		&i.ConversationID,
		&i.LastReadMessageID,
		&i.LastReadAt,
		&i.UpdatedAt,
	)
	return i, err
}

const moveContactConversations = `-- name: MoveContactConversations :many
WITH moved AS (
    UPDATE conversations SET contact_id = $1, updated_at = $2
    WHERE conversations.workspace_id = $3 AND conversations.contact_id = $4
    RETURNING id, workspace_id, inbox_id, contact_id, channel_id, subject, status, snooze_until, priority, assignee_id, last_message_at, last_activity_at, created_at, updated_at, spam, email_token, related_conversation_id, continuity_through, continuity_sent_at, kind, feedback, email_address, closed_at, rating, rating_comment, rated_at, rating_requested_at),
seen AS (
    UPDATE contacts t SET last_active_at = greatest(t.last_active_at, f.last_active_at)
    FROM contacts f
    WHERE t.workspace_id = $3 AND t.id = $1 AND f.workspace_id = $3
      AND f.id = $4 AND f.last_active_at IS NOT NULL)
SELECT id, workspace_id, inbox_id, contact_id, channel_id, subject, status, snooze_until, priority, assignee_id, last_message_at, last_activity_at, created_at, updated_at, spam, email_token, related_conversation_id, continuity_through, continuity_sent_at, kind, feedback, email_address, closed_at, rating, rating_comment, rated_at, rating_requested_at FROM moved
`

type MoveContactConversationsParams struct {
	ToContact   uuid.UUID
	Now         time.Time
	WorkspaceID uuid.UUID
	FromContact uuid.UUID
}

type MoveContactConversationsRow struct {
	ID                    uuid.UUID
	WorkspaceID           uuid.UUID
	InboxID               uuid.UUID
	ContactID             uuid.UUID
	ChannelID             *uuid.UUID
	Subject               string
	Status                string
	SnoozeUntil           *time.Time
	Priority              string
	AssigneeID            *uuid.UUID
	LastMessageAt         *time.Time
	LastActivityAt        time.Time
	CreatedAt             time.Time
	UpdatedAt             time.Time
	Spam                  bool
	EmailToken            *string
	RelatedConversationID *uuid.UUID
	ContinuityThrough     *time.Time
	ContinuitySentAt      *time.Time
	Kind                  string
	Feedback              []byte
	EmailAddress          *string
	ClosedAt              *time.Time
	Rating                *string
	RatingComment         *string
	RatedAt               *time.Time
	RatingRequestedAt     *time.Time
}

func (q *Queries) MoveContactConversations(ctx context.Context, arg MoveContactConversationsParams) ([]MoveContactConversationsRow, error) {
	rows, err := q.db.Query(ctx, moveContactConversations,
		arg.ToContact,
		arg.Now,
		arg.WorkspaceID,
		arg.FromContact,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MoveContactConversationsRow
	for rows.Next() {
		var i MoveContactConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.InboxID,
			&i.ContactID,
			&i.ChannelID,
			&i.Subject,
			&i.Status,
			&i.SnoozeUntil,
			&i.Priority,
			&i.AssigneeID,
			&i.LastMessageAt,
			&i.LastActivityAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Spam,
			&i.EmailToken,
			&i.RelatedConversationID,
			&i.ContinuityThrough,
			&i.ContinuitySentAt,
			&i.Kind,
			&i.Feedback,
			&i.EmailAddress,
			&i.ClosedAt,
			&i.Rating,
			&i.RatingComment,
			&i.RatedAt,
			&i.RatingRequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveContactEmails = `-- name: MoveContactEmails :exec
UPDATE contact_emails e SET contact_id = $1::uuid,
    position = e.position + (SELECT count(*) FROM contact_emails x WHERE x.workspace_id = $2::uuid AND x.contact_id = $1::uuid)
WHERE e.workspace_id = $2::uuid AND e.contact_id = $3::uuid
`

type MoveContactEmailsParams struct {
	ToContact   uuid.UUID
	WorkspaceID uuid.UUID
	FromContact uuid.UUID
}

func (q *Queries) MoveContactEmails(ctx context.Context, arg MoveContactEmailsParams) error {
	_, err := q.db.Exec(ctx, moveContactEmails, arg.ToContact, arg.WorkspaceID, arg.FromContact)
	return err
}

const moveContactMessages = `-- name: MoveContactMessages :exec
UPDATE messages SET author_contact_id = $1
WHERE workspace_id = $2 AND author_contact_id = $3
`

type MoveContactMessagesParams struct {
	ToContact   *uuid.UUID
	WorkspaceID uuid.UUID
	FromContact *uuid.UUID
}

func (q *Queries) MoveContactMessages(ctx context.Context, arg MoveContactMessagesParams) error {
	_, err := q.db.Exec(ctx, moveContactMessages, arg.ToContact, arg.WorkspaceID, arg.FromContact)
	return err
}

const openConnection = `-- name: OpenConnection :exec
INSERT INTO realtime_connections (id, workspace_id, member_id, contact_id, seen_at)
VALUES ($1, $2, $3, $4, $5)
`

type OpenConnectionParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	MemberID    *uuid.UUID
	ContactID   *uuid.UUID
	Now         time.Time
}

func (q *Queries) OpenConnection(ctx context.Context, arg OpenConnectionParams) error {
	_, err := q.db.Exec(ctx, openConnection,
		arg.ID,
		arg.WorkspaceID,
		arg.MemberID,
		arg.ContactID,
		arg.Now,
	)
	return err
}

const saveChatChannel = `-- name: SaveChatChannel :one
INSERT INTO chat_channels (workspace_id, channel_id, public_key, allowed_origins, allow_anonymous, ask_email_offline,
                           greeting, launcher_position, launcher_color, platforms)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10)
ON CONFLICT (workspace_id, channel_id) DO UPDATE SET
    allowed_origins = excluded.allowed_origins, allow_anonymous = excluded.allow_anonymous,
    ask_email_offline = excluded.ask_email_offline, greeting = excluded.greeting,
    launcher_position = excluded.launcher_position, launcher_color = excluded.launcher_color,
    platforms = excluded.platforms
RETURNING workspace_id, channel_id, public_key, allowed_origins, allow_anonymous, ask_email_offline, greeting, launcher_position, launcher_color, platforms
`

type SaveChatChannelParams struct {
	WorkspaceID      uuid.UUID
	ChannelID        uuid.UUID
	PublicKey        string
	AllowedOrigins   []string
	AllowAnonymous   bool
	AskEmailOffline  bool
	Greeting         string
	LauncherPosition *string
	LauncherColor    *string
	Platforms        []string
}

func (q *Queries) SaveChatChannel(ctx context.Context, arg SaveChatChannelParams) (ChatChannel, error) {
	row := q.db.QueryRow(ctx, saveChatChannel,
		arg.WorkspaceID,
		arg.ChannelID,
		arg.PublicKey,
		arg.AllowedOrigins,
		arg.AllowAnonymous,
		arg.AskEmailOffline,
		arg.Greeting,
		arg.LauncherPosition,
		arg.LauncherColor,
		arg.Platforms,
	)
	var i ChatChannel
	err := row.Scan(
		&i.WorkspaceID,
		&i.ChannelID,
		&i.PublicKey,
		&i.AllowedOrigins,
		&i.AllowAnonymous,
		&i.AskEmailOffline,
		&i.Greeting,
		&i.LauncherPosition,
		&i.LauncherColor,
		&i.Platforms,
	)
	return i, err
}

const seeConnection = `-- name: SeeConnection :exec
UPDATE realtime_connections SET seen_at = $1 WHERE workspace_id = $2 AND id = $3
`

type SeeConnectionParams struct {
	Now         time.Time
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) SeeConnection(ctx context.Context, arg SeeConnectionParams) error {
	_, err := q.db.Exec(ctx, seeConnection, arg.Now, arg.WorkspaceID, arg.ID)
	return err
}

const seeContactSession = `-- name: SeeContactSession :exec
WITH s AS (
    UPDATE contact_sessions SET last_seen_at = greatest(contact_sessions.last_seen_at, $1::timestamptz)
    WHERE contact_sessions.workspace_id = $2 AND contact_sessions.id = $3
    RETURNING contact_sessions.workspace_id, contact_sessions.contact_id, contact_sessions.last_seen_at)
UPDATE contacts SET last_active_at = greatest(coalesce(contacts.last_active_at, s.last_seen_at), s.last_seen_at)
FROM s WHERE contacts.workspace_id = s.workspace_id AND contacts.id = s.contact_id
`

type SeeContactSessionParams struct {
	Now         time.Time
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) SeeContactSession(ctx context.Context, arg SeeContactSessionParams) error {
	_, err := q.db.Exec(ctx, seeContactSession, arg.Now, arg.WorkspaceID, arg.ID)
	return err
}

const setChatChannelKey = `-- name: SetChatChannelKey :one
UPDATE chat_channels SET public_key = $1
WHERE workspace_id = $2 AND channel_id = $3
RETURNING workspace_id, channel_id, public_key, allowed_origins, allow_anonymous, ask_email_offline, greeting, launcher_position, launcher_color, platforms
`

type SetChatChannelKeyParams struct {
	PublicKey   string
	WorkspaceID uuid.UUID
	ChannelID   uuid.UUID
}

func (q *Queries) SetChatChannelKey(ctx context.Context, arg SetChatChannelKeyParams) (ChatChannel, error) {
	row := q.db.QueryRow(ctx, setChatChannelKey, arg.PublicKey, arg.WorkspaceID, arg.ChannelID)
	var i ChatChannel
	err := row.Scan(
		&i.WorkspaceID,
		&i.ChannelID,
		&i.PublicKey,
		&i.AllowedOrigins,
		&i.AllowAnonymous,
		&i.AskEmailOffline,
		&i.Greeting,
		&i.LauncherPosition,
		&i.LauncherColor,
		&i.Platforms,
	)
	return i, err
}

const setContactIdentity = `-- name: SetContactIdentity :one
UPDATE contacts SET name = $1, locale = $2, attributes = $3, updated_at = $4
WHERE workspace_id = $5 AND id = $6
RETURNING id, workspace_id, name, attributes, blocked, created_at, updated_at, locale, typed_email
`

type SetContactIdentityParams struct {
	Name        string
	Locale      *string
	Attributes  []byte
	Now         time.Time
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

type SetContactIdentityRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Attributes  []byte
	Blocked     bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Locale      *string
	TypedEmail  *string
}

func (q *Queries) SetContactIdentity(ctx context.Context, arg SetContactIdentityParams) (SetContactIdentityRow, error) {
	row := q.db.QueryRow(ctx, setContactIdentity,
		arg.Name,
		arg.Locale,
		arg.Attributes,
		arg.Now,
		arg.WorkspaceID,
		arg.ID,
	)
	var i SetContactIdentityRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Attributes,
		&i.Blocked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Locale,
		&i.TypedEmail,
	)
	return i, err
}

const setContactTypedEmail = `-- name: SetContactTypedEmail :one
UPDATE contacts SET typed_email = $1, updated_at = $2
WHERE workspace_id = $3 AND id = $4
RETURNING id, workspace_id, name, attributes, blocked, created_at, updated_at, locale, typed_email
`

type SetContactTypedEmailParams struct {
	TypedEmail  *string
	Now         time.Time
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

type SetContactTypedEmailRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Attributes  []byte
	Blocked     bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Locale      *string
	TypedEmail  *string
}

func (q *Queries) SetContactTypedEmail(ctx context.Context, arg SetContactTypedEmailParams) (SetContactTypedEmailRow, error) {
	row := q.db.QueryRow(ctx, setContactTypedEmail,
		arg.TypedEmail,
		arg.Now,
		arg.WorkspaceID,
		arg.ID,
	)
	var i SetContactTypedEmailRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Attributes,
		&i.Blocked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Locale,
		&i.TypedEmail,
	)
	return i, err
}

const setPersonAvailability = `-- name: SetPersonAvailability :exec
UPDATE people SET availability = $2 WHERE id = $1
`

type SetPersonAvailabilityParams struct {
	ID           uuid.UUID
	Availability string
}

func (q *Queries) SetPersonAvailability(ctx context.Context, arg SetPersonAvailabilityParams) error {
	_, err := q.db.Exec(ctx, setPersonAvailability, arg.ID, arg.Availability)
	return err
}

const takeEmailConfirmation = `-- name: TakeEmailConfirmation :one
DELETE FROM email_confirmations WHERE workspace_id = $1 AND token_hash = $2 AND expires_at > $3
RETURNING contact_id, inbox_id, email
`

type TakeEmailConfirmationParams struct {
	WorkspaceID uuid.UUID
	TokenHash   []byte
	Now         time.Time
}

type TakeEmailConfirmationRow struct {
	ContactID uuid.UUID
	InboxID   uuid.UUID
	Email     string
}

func (q *Queries) TakeEmailConfirmation(ctx context.Context, arg TakeEmailConfirmationParams) (TakeEmailConfirmationRow, error) {
	row := q.db.QueryRow(ctx, takeEmailConfirmation, arg.WorkspaceID, arg.TokenHash, arg.Now)
	var i TakeEmailConfirmationRow
	err := row.Scan(&i.ContactID, &i.InboxID, &i.Email)
	return i, err
}

const touchContactSession = `-- name: TouchContactSession :exec
WITH s AS (
    UPDATE contact_sessions SET last_seen_at = $1::timestamptz, expires_at = $2::timestamptz
    WHERE contact_sessions.workspace_id = $3 AND contact_sessions.id = $4
      AND contact_sessions.last_seen_at < $5::timestamptz
    RETURNING contact_sessions.workspace_id, contact_sessions.contact_id, contact_sessions.last_seen_at)
UPDATE contacts SET last_active_at = greatest(coalesce(contacts.last_active_at, s.last_seen_at), s.last_seen_at)
FROM s WHERE contacts.workspace_id = s.workspace_id AND contacts.id = s.contact_id
`

type TouchContactSessionParams struct {
	Now         time.Time
	ExpiresAt   time.Time
	WorkspaceID uuid.UUID
	ID          uuid.UUID
	StaleBefore time.Time
}

func (q *Queries) TouchContactSession(ctx context.Context, arg TouchContactSessionParams) error {
	_, err := q.db.Exec(ctx, touchContactSession,
		arg.Now,
		arg.ExpiresAt,
		arg.WorkspaceID,
		arg.ID,
		arg.StaleBefore,
	)
	return err
}

const useIdentityTokenID = `-- name: UseIdentityTokenID :execrows
INSERT INTO identity_token_ids (workspace_id, inbox_id, jti, expires_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type UseIdentityTokenIDParams struct {
	WorkspaceID uuid.UUID
	InboxID     uuid.UUID
	Jti         string
	ExpiresAt   time.Time
}

func (q *Queries) UseIdentityTokenID(ctx context.Context, arg UseIdentityTokenIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, useIdentityTokenID,
		arg.WorkspaceID,
		arg.InboxID,
		arg.Jti,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
