// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contact_notes.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const createContactNote = `-- name: CreateContactNote :one
WITH n AS (
    INSERT INTO contact_notes (id, workspace_id, contact_id, author_member_id, author_api_key_id, body, created_at)
    VALUES ($1, $2, $3, $4, $5, $6, $7)
    RETURNING id, workspace_id, contact_id, author_member_id, author_api_key_id, body, created_at)
SELECT n.id, n.workspace_id, n.contact_id, n.author_member_id, n.author_api_key_id, n.body, n.created_at,
       coalesce(ak.bot_name, ak.name, '')::text AS bot_name, coalesce(ak.bot_avatar_url, '')::text AS bot_avatar_url
FROM n LEFT JOIN api_keys ak ON ak.workspace_id = n.workspace_id AND ak.id = n.author_api_key_id
`

type CreateContactNoteParams struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	ContactID      uuid.UUID
	AuthorMemberID *uuid.UUID
	AuthorApiKeyID *uuid.UUID
	Body           string
	Now            time.Time
}

type CreateContactNoteRow struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	ContactID      uuid.UUID
	AuthorMemberID *uuid.UUID
	AuthorApiKeyID *uuid.UUID
	Body           string
	CreatedAt      time.Time
	BotName        string
	BotAvatarUrl   string
}

func (q *Queries) CreateContactNote(ctx context.Context, arg CreateContactNoteParams) (CreateContactNoteRow, error) {
	row := q.db.QueryRow(ctx, createContactNote,
		arg.ID,
		arg.WorkspaceID,
		arg.ContactID,
		arg.AuthorMemberID,
		arg.AuthorApiKeyID,
		arg.Body,
		arg.Now,
	)
	var i CreateContactNoteRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ContactID,
		&i.AuthorMemberID,
		&i.AuthorApiKeyID,
		&i.Body,
		&i.CreatedAt,
		&i.BotName,
		&i.BotAvatarUrl,
	)
	return i, err
}

const deleteContactNote = `-- name: DeleteContactNote :exec
DELETE FROM contact_notes WHERE workspace_id = $1 AND id = $2
`

type DeleteContactNoteParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) DeleteContactNote(ctx context.Context, arg DeleteContactNoteParams) error {
	_, err := q.db.Exec(ctx, deleteContactNote, arg.WorkspaceID, arg.ID)
	return err
}

const listContactNotes = `-- name: ListContactNotes :many
SELECT n.id, n.workspace_id, n.contact_id, n.author_member_id, n.author_api_key_id, n.body, n.created_at,
       coalesce(ak.bot_name, ak.name, '')::text AS bot_name, coalesce(ak.bot_avatar_url, '')::text AS bot_avatar_url
FROM contact_notes n LEFT JOIN api_keys ak ON ak.workspace_id = n.workspace_id AND ak.id = n.author_api_key_id
WHERE n.workspace_id = $1 AND n.contact_id = $2
  AND ($3::timestamptz IS NULL
       OR (n.created_at, n.id) < ($3::timestamptz, $4::uuid))
ORDER BY n.created_at DESC, n.id DESC
LIMIT $5
`

type ListContactNotesParams struct {
	WorkspaceID uuid.UUID
	ContactID   uuid.UUID
	CursorAt    *time.Time
	CursorID    *uuid.UUID
	Lim         int32
}

type ListContactNotesRow struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	ContactID      uuid.UUID
	AuthorMemberID *uuid.UUID
	AuthorApiKeyID *uuid.UUID
	Body           string
	CreatedAt      time.Time
	BotName        string
	BotAvatarUrl   string
}

func (q *Queries) ListContactNotes(ctx context.Context, arg ListContactNotesParams) ([]ListContactNotesRow, error) {
	rows, err := q.db.Query(ctx, listContactNotes,
		arg.WorkspaceID,
		arg.ContactID,
		arg.CursorAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContactNotesRow
	for rows.Next() {
		var i ListContactNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ContactID,
			&i.AuthorMemberID,
			&i.AuthorApiKeyID,
			&i.Body,
			&i.CreatedAt,
			&i.BotName,
			&i.BotAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockContactNote = `-- name: LockContactNote :one
SELECT id, workspace_id, contact_id, author_member_id, author_api_key_id, body, created_at FROM contact_notes WHERE workspace_id = $1 AND contact_id = $2 AND id = $3 FOR UPDATE
`

type LockContactNoteParams struct {
	WorkspaceID uuid.UUID
	ContactID   uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) LockContactNote(ctx context.Context, arg LockContactNoteParams) (ContactNote, error) {
	row := q.db.QueryRow(ctx, lockContactNote, arg.WorkspaceID, arg.ContactID, arg.ID)
	var i ContactNote
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ContactID,
		&i.AuthorMemberID,
		&i.AuthorApiKeyID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}
