// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const addContactEmail = `-- name: AddContactEmail :exec
INSERT INTO contact_emails (workspace_id, contact_id, email, position) VALUES ($1, $2, $3, $4)
`

type AddContactEmailParams struct {
	WorkspaceID uuid.UUID
	ContactID   uuid.UUID
	Email       string
	Position    int32
}

func (q *Queries) AddContactEmail(ctx context.Context, arg AddContactEmailParams) error {
	_, err := q.db.Exec(ctx, addContactEmail,
		arg.WorkspaceID,
		arg.ContactID,
		arg.Email,
		arg.Position,
	)
	return err
}

const addContactExternalID = `-- name: AddContactExternalID :exec
INSERT INTO contact_external_ids (workspace_id, inbox_id, external_id, contact_id) VALUES ($1, $2, $3, $4)
`

type AddContactExternalIDParams struct {
	WorkspaceID uuid.UUID
	InboxID     uuid.UUID
	ExternalID  string
	ContactID   uuid.UUID
}

func (q *Queries) AddContactExternalID(ctx context.Context, arg AddContactExternalIDParams) error {
	_, err := q.db.Exec(ctx, addContactExternalID,
		arg.WorkspaceID,
		arg.InboxID,
		arg.ExternalID,
		arg.ContactID,
	)
	return err
}

const contactExists = `-- name: ContactExists :one
SELECT EXISTS (SELECT 1 FROM contacts WHERE workspace_id = $1 AND id = $2) AS found
`

type ContactExistsParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) ContactExists(ctx context.Context, arg ContactExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, contactExists, arg.WorkspaceID, arg.ID)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const contactFirstReplies = `-- name: ContactFirstReplies :many
SELECT a.asked_at::timestamptz AS asked_at, min(o.created_at)::timestamptz AS replied_at
FROM (
    SELECT i.conversation_id, min(i.created_at) AS asked_at
    FROM messages i
    JOIN conversations cv ON cv.workspace_id = i.workspace_id AND cv.id = i.conversation_id
    WHERE i.workspace_id = $1 AND cv.contact_id = $2 AND NOT cv.spam
      AND i.kind = 'message' AND i.direction = 'in'
      AND ($3::bool OR EXISTS (
          SELECT 1 FROM inbox_viewers iv
          WHERE iv.workspace_id = cv.workspace_id AND iv.inbox_id = cv.inbox_id AND iv.viewer_id = $4::uuid))
    GROUP BY i.conversation_id
) a
JOIN messages o ON o.workspace_id = $1 AND o.conversation_id = a.conversation_id
    AND o.kind = 'message' AND o.direction = 'out' AND NOT o.draft
    AND (o.author_type = 'member' OR o.sent_by_member_id IS NOT NULL)
    AND o.created_at > a.asked_at
GROUP BY a.conversation_id, a.asked_at
`

type ContactFirstRepliesParams struct {
	WorkspaceID uuid.UUID
	ContactID   uuid.UUID
	AllInboxes  bool
	ViewerID    uuid.UUID
}

type ContactFirstRepliesRow struct {
	AskedAt   time.Time
	RepliedAt time.Time
}

func (q *Queries) ContactFirstReplies(ctx context.Context, arg ContactFirstRepliesParams) ([]ContactFirstRepliesRow, error) {
	rows, err := q.db.Query(ctx, contactFirstReplies,
		arg.WorkspaceID,
		arg.ContactID,
		arg.AllInboxes,
		arg.ViewerID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContactFirstRepliesRow
	for rows.Next() {
		var i ContactFirstRepliesRow
		if err := rows.Scan(&i.AskedAt, &i.RepliedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contactRatings = `-- name: ContactRatings :many
SELECT cv.rating::text AS rating, count(*) AS n
FROM conversations cv
WHERE cv.workspace_id = $1 AND cv.contact_id = $2 AND NOT cv.spam AND cv.rating IS NOT NULL
  AND ($3::bool OR EXISTS (
      SELECT 1 FROM inbox_viewers iv
      WHERE iv.workspace_id = cv.workspace_id AND iv.inbox_id = cv.inbox_id AND iv.viewer_id = $4::uuid))
GROUP BY 1
`

type ContactRatingsParams struct {
	WorkspaceID uuid.UUID
	ContactID   uuid.UUID
	AllInboxes  bool
	ViewerID    uuid.UUID
}

type ContactRatingsRow struct {
	Rating string
	N      int64
}

func (q *Queries) ContactRatings(ctx context.Context, arg ContactRatingsParams) ([]ContactRatingsRow, error) {
	rows, err := q.db.Query(ctx, contactRatings,
		arg.WorkspaceID,
		arg.ContactID,
		arg.AllInboxes,
		arg.ViewerID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContactRatingsRow
	for rows.Next() {
		var i ContactRatingsRow
		if err := rows.Scan(&i.Rating, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contactVisibleToViewer = `-- name: ContactVisibleToViewer :one
SELECT coalesce(EXISTS (SELECT 1 FROM conversations cv JOIN inbox_viewers iv
               ON iv.workspace_id = cv.workspace_id AND iv.inbox_id = cv.inbox_id AND iv.viewer_id = $1
               WHERE cv.workspace_id = $2 AND cv.contact_id = $3)
    OR EXISTS (SELECT 1 FROM contact_external_ids x JOIN inbox_viewers iv
               ON iv.workspace_id = x.workspace_id AND iv.inbox_id = x.inbox_id AND iv.viewer_id = $1
               WHERE x.workspace_id = $2 AND x.contact_id = $3)
    OR (NOT EXISTS (SELECT 1 FROM conversations cv WHERE cv.workspace_id = $2 AND cv.contact_id = $3)
        AND NOT EXISTS (SELECT 1 FROM contact_external_ids x WHERE x.workspace_id = $2 AND x.contact_id = $3)), false)::bool
    AS visible
`

type ContactVisibleToViewerParams struct {
	ViewerID    uuid.UUID
	WorkspaceID uuid.UUID
	ContactID   uuid.UUID
}

func (q *Queries) ContactVisibleToViewer(ctx context.Context, arg ContactVisibleToViewerParams) (bool, error) {
	row := q.db.QueryRow(ctx, contactVisibleToViewer, arg.ViewerID, arg.WorkspaceID, arg.ContactID)
	var visible bool
	err := row.Scan(&visible)
	return visible, err
}

const createContact = `-- name: CreateContact :one
INSERT INTO contacts (id, workspace_id, name, attributes, blocked, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $6)
RETURNING id, workspace_id, name, attributes, blocked, created_at, updated_at, locale, typed_email
`

type CreateContactParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Attributes  []byte
	Blocked     bool
	Now         time.Time
}

type CreateContactRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Attributes  []byte
	Blocked     bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Locale      *string
	TypedEmail  *string
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (CreateContactRow, error) {
	row := q.db.QueryRow(ctx, createContact,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Attributes,
		arg.Blocked,
		arg.Now,
	)
	var i CreateContactRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Attributes,
		&i.Blocked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Locale,
		&i.TypedEmail,
	)
	return i, err
}

const deleteContact = `-- name: DeleteContact :execrows
DELETE FROM contacts WHERE workspace_id = $1 AND id = $2
`

type DeleteContactParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) DeleteContact(ctx context.Context, arg DeleteContactParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteContact, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteContactEmails = `-- name: DeleteContactEmails :exec
DELETE FROM contact_emails WHERE workspace_id = $1 AND contact_id = $2
`

type DeleteContactEmailsParams struct {
	WorkspaceID uuid.UUID
	ContactID   uuid.UUID
}

func (q *Queries) DeleteContactEmails(ctx context.Context, arg DeleteContactEmailsParams) error {
	_, err := q.db.Exec(ctx, deleteContactEmails, arg.WorkspaceID, arg.ContactID)
	return err
}

const deleteContactExternalIDs = `-- name: DeleteContactExternalIDs :exec
DELETE FROM contact_external_ids WHERE workspace_id = $1 AND contact_id = $2
`

type DeleteContactExternalIDsParams struct {
	WorkspaceID uuid.UUID
	ContactID   uuid.UUID
}

func (q *Queries) DeleteContactExternalIDs(ctx context.Context, arg DeleteContactExternalIDsParams) error {
	_, err := q.db.Exec(ctx, deleteContactExternalIDs, arg.WorkspaceID, arg.ContactID)
	return err
}

const getContact = `-- name: GetContact :one
SELECT id, workspace_id, name, attributes, blocked, created_at, updated_at, locale, typed_email
FROM contacts WHERE workspace_id = $1 AND id = $2
`

type GetContactParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

type GetContactRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Attributes  []byte
	Blocked     bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Locale      *string
	TypedEmail  *string
}

func (q *Queries) GetContact(ctx context.Context, arg GetContactParams) (GetContactRow, error) {
	row := q.db.QueryRow(ctx, getContact, arg.WorkspaceID, arg.ID)
	var i GetContactRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Attributes,
		&i.Blocked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Locale,
		&i.TypedEmail,
	)
	return i, err
}

const getContactIDByExternalID = `-- name: GetContactIDByExternalID :one
SELECT contact_id FROM contact_external_ids WHERE workspace_id = $1 AND inbox_id = $2 AND external_id = $3
`

type GetContactIDByExternalIDParams struct {
	WorkspaceID uuid.UUID
	InboxID     uuid.UUID
	ExternalID  string
}

func (q *Queries) GetContactIDByExternalID(ctx context.Context, arg GetContactIDByExternalIDParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getContactIDByExternalID, arg.WorkspaceID, arg.InboxID, arg.ExternalID)
	var contact_id uuid.UUID
	err := row.Scan(&contact_id)
	return contact_id, err
}

const listContactActivity = `-- name: ListContactActivity :many
SELECT c.id, c.last_active_at, count(cv.id) AS conversations,
       count(cv.id) FILTER (WHERE cv.status = 'open') AS open_conversations,
       coalesce(max(coalesce(cv.last_message_at, cv.created_at)), c.created_at)::timestamptz AS last_conversation_at
FROM contacts c
LEFT JOIN conversations cv ON cv.workspace_id = c.workspace_id AND cv.contact_id = c.id AND NOT cv.spam
  AND ($1::bool OR EXISTS (
      SELECT 1 FROM inbox_viewers iv
      WHERE iv.workspace_id = cv.workspace_id AND iv.inbox_id = cv.inbox_id AND iv.viewer_id = $2::uuid))
WHERE c.workspace_id = $3 AND c.id = ANY($4::uuid[])
GROUP BY c.id, c.last_active_at
`

type ListContactActivityParams struct {
	AllInboxes  bool
	ViewerID    uuid.UUID
	WorkspaceID uuid.UUID
	Ids         []uuid.UUID
}

type ListContactActivityRow struct {
	ID                 uuid.UUID
	LastActiveAt       *time.Time
	Conversations      int64
	OpenConversations  int64
	LastConversationAt time.Time
}

func (q *Queries) ListContactActivity(ctx context.Context, arg ListContactActivityParams) ([]ListContactActivityRow, error) {
	rows, err := q.db.Query(ctx, listContactActivity,
		arg.AllInboxes,
		arg.ViewerID,
		arg.WorkspaceID,
		arg.Ids,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContactActivityRow
	for rows.Next() {
		var i ListContactActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.LastActiveAt,
			&i.Conversations,
			&i.OpenConversations,
			&i.LastConversationAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactEmails = `-- name: ListContactEmails :many
SELECT contact_id, email FROM contact_emails
WHERE workspace_id = $1 AND contact_id = ANY($2::uuid[])
ORDER BY contact_id, position
`

type ListContactEmailsParams struct {
	WorkspaceID uuid.UUID
	ContactIds  []uuid.UUID
}

type ListContactEmailsRow struct {
	ContactID uuid.UUID
	Email     string
}

func (q *Queries) ListContactEmails(ctx context.Context, arg ListContactEmailsParams) ([]ListContactEmailsRow, error) {
	rows, err := q.db.Query(ctx, listContactEmails, arg.WorkspaceID, arg.ContactIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContactEmailsRow
	for rows.Next() {
		var i ListContactEmailsRow
		if err := rows.Scan(&i.ContactID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactExternalIDs = `-- name: ListContactExternalIDs :many
SELECT contact_id, inbox_id, external_id FROM contact_external_ids
WHERE workspace_id = $1 AND contact_id = ANY($2::uuid[])
ORDER BY contact_id, inbox_id, external_id
`

type ListContactExternalIDsParams struct {
	WorkspaceID uuid.UUID
	ContactIds  []uuid.UUID
}

type ListContactExternalIDsRow struct {
	ContactID  uuid.UUID
	InboxID    uuid.UUID
	ExternalID string
}

func (q *Queries) ListContactExternalIDs(ctx context.Context, arg ListContactExternalIDsParams) ([]ListContactExternalIDsRow, error) {
	rows, err := q.db.Query(ctx, listContactExternalIDs, arg.WorkspaceID, arg.ContactIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContactExternalIDsRow
	for rows.Next() {
		var i ListContactExternalIDsRow
		if err := rows.Scan(&i.ContactID, &i.InboxID, &i.ExternalID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactStorageKeys = `-- name: ListContactStorageKeys :many
SELECT a.storage_key FROM attachments a
JOIN conversations c ON c.workspace_id = a.workspace_id AND c.id = a.conversation_id
WHERE a.workspace_id = $1 AND c.contact_id = $2
`

type ListContactStorageKeysParams struct {
	WorkspaceID uuid.UUID
	ContactID   uuid.UUID
}

func (q *Queries) ListContactStorageKeys(ctx context.Context, arg ListContactStorageKeysParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listContactStorageKeys, arg.WorkspaceID, arg.ContactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var storage_key string
		if err := rows.Scan(&storage_key); err != nil {
			return nil, err
		}
		items = append(items, storage_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactSummaries = `-- name: ListContactSummaries :many
SELECT c.id, c.name,
       coalesce((SELECT e.email FROM contact_emails e
                 WHERE e.workspace_id = c.workspace_id AND e.contact_id = c.id
                 ORDER BY e.position LIMIT 1), '')::text AS email
FROM contacts c
WHERE c.workspace_id = $1 AND c.id = ANY($2::uuid[])
`

type ListContactSummariesParams struct {
	WorkspaceID uuid.UUID
	Ids         []uuid.UUID
}

type ListContactSummariesRow struct {
	ID    uuid.UUID
	Name  string
	Email string
}

func (q *Queries) ListContactSummaries(ctx context.Context, arg ListContactSummariesParams) ([]ListContactSummariesRow, error) {
	rows, err := q.db.Query(ctx, listContactSummaries, arg.WorkspaceID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContactSummariesRow
	for rows.Next() {
		var i ListContactSummariesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContacts = `-- name: ListContacts :many
SELECT id, workspace_id, name, attributes, blocked, created_at, updated_at, locale, typed_email
FROM contacts c
WHERE c.workspace_id = $1
  AND ($2::uuid IS NULL OR (
      EXISTS (SELECT 1 FROM conversations cv JOIN inbox_viewers iv
              ON iv.workspace_id = cv.workspace_id AND iv.inbox_id = cv.inbox_id AND iv.viewer_id = $2::uuid
              WHERE cv.workspace_id = c.workspace_id AND cv.contact_id = c.id)
   OR EXISTS (SELECT 1 FROM contact_external_ids x JOIN inbox_viewers iv
              ON iv.workspace_id = x.workspace_id AND iv.inbox_id = x.inbox_id AND iv.viewer_id = $2::uuid
              WHERE x.workspace_id = c.workspace_id AND x.contact_id = c.id)
   OR (NOT EXISTS (SELECT 1 FROM conversations cv WHERE cv.workspace_id = c.workspace_id AND cv.contact_id = c.id)
       AND NOT EXISTS (SELECT 1 FROM contact_external_ids x WHERE x.workspace_id = c.workspace_id AND x.contact_id = c.id))))
  AND ($3::text IS NULL OR c.search @@ websearch_to_tsquery('simple', translate($3::text, 'İı', 'ii')))
  AND ($4::text IS NULL OR ($4::text = 'known') = (
      EXISTS (SELECT 1 FROM contact_emails e WHERE e.workspace_id = c.workspace_id AND e.contact_id = c.id)
      OR EXISTS (SELECT 1 FROM contact_external_ids x WHERE x.workspace_id = c.workspace_id AND x.contact_id = c.id)))
  AND ($5::bool IS NULL OR $5::bool = EXISTS (
      SELECT 1 FROM conversations cv
      WHERE cv.workspace_id = c.workspace_id AND cv.contact_id = c.id AND cv.status = 'open' AND NOT cv.spam
        AND ($2::uuid IS NULL OR EXISTS (
            SELECT 1 FROM inbox_viewers iv
            WHERE iv.workspace_id = cv.workspace_id AND iv.inbox_id = cv.inbox_id AND iv.viewer_id = $2::uuid))))
  AND ($6::timestamptz IS NULL
       OR (c.created_at, c.id) < ($6::timestamptz, $7::uuid))
ORDER BY c.created_at DESC, c.id DESC
LIMIT $8
`

type ListContactsParams struct {
	WorkspaceID uuid.UUID
	ViewerID    *uuid.UUID
	Q           *string
	Kind        *string
	HasOpen     *bool
	CursorAt    *time.Time
	CursorID    *uuid.UUID
	Lim         int32
}

type ListContactsRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Attributes  []byte
	Blocked     bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Locale      *string
	TypedEmail  *string
}

func (q *Queries) ListContacts(ctx context.Context, arg ListContactsParams) ([]ListContactsRow, error) {
	rows, err := q.db.Query(ctx, listContacts,
		arg.WorkspaceID,
		arg.ViewerID,
		arg.Q,
		arg.Kind,
		arg.HasOpen,
		arg.CursorAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContactsRow
	for rows.Next() {
		var i ListContactsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Attributes,
			&i.Blocked,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Locale,
			&i.TypedEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactsByActivity = `-- name: ListContactsByActivity :many
SELECT id, workspace_id, name, attributes, blocked, created_at, updated_at, locale, typed_email,
       coalesce(c.last_active_at, c.created_at)::timestamptz AS active_at
FROM contacts c
WHERE c.workspace_id = $1
  AND ($2::uuid IS NULL OR (
      EXISTS (SELECT 1 FROM conversations cv JOIN inbox_viewers iv
              ON iv.workspace_id = cv.workspace_id AND iv.inbox_id = cv.inbox_id AND iv.viewer_id = $2::uuid
              WHERE cv.workspace_id = c.workspace_id AND cv.contact_id = c.id)
   OR EXISTS (SELECT 1 FROM contact_external_ids x JOIN inbox_viewers iv
              ON iv.workspace_id = x.workspace_id AND iv.inbox_id = x.inbox_id AND iv.viewer_id = $2::uuid
              WHERE x.workspace_id = c.workspace_id AND x.contact_id = c.id)
   OR (NOT EXISTS (SELECT 1 FROM conversations cv WHERE cv.workspace_id = c.workspace_id AND cv.contact_id = c.id)
       AND NOT EXISTS (SELECT 1 FROM contact_external_ids x WHERE x.workspace_id = c.workspace_id AND x.contact_id = c.id))))
  AND ($3::text IS NULL OR c.search @@ websearch_to_tsquery('simple', translate($3::text, 'İı', 'ii')))
  AND ($4::text IS NULL OR ($4::text = 'known') = (
      EXISTS (SELECT 1 FROM contact_emails e WHERE e.workspace_id = c.workspace_id AND e.contact_id = c.id)
      OR EXISTS (SELECT 1 FROM contact_external_ids x WHERE x.workspace_id = c.workspace_id AND x.contact_id = c.id)))
  AND ($5::bool IS NULL OR $5::bool = EXISTS (
      SELECT 1 FROM conversations cv
      WHERE cv.workspace_id = c.workspace_id AND cv.contact_id = c.id AND cv.status = 'open' AND NOT cv.spam
        AND ($2::uuid IS NULL OR EXISTS (
            SELECT 1 FROM inbox_viewers iv
            WHERE iv.workspace_id = cv.workspace_id AND iv.inbox_id = cv.inbox_id AND iv.viewer_id = $2::uuid))))
  AND ($6::timestamptz IS NULL
       OR (coalesce(c.last_active_at, c.created_at), c.id) < ($6::timestamptz, $7::uuid))
ORDER BY coalesce(c.last_active_at, c.created_at) DESC, c.id DESC
LIMIT $8
`

type ListContactsByActivityParams struct {
	WorkspaceID uuid.UUID
	ViewerID    *uuid.UUID
	Q           *string
	Kind        *string
	HasOpen     *bool
	CursorAt    *time.Time
	CursorID    *uuid.UUID
	Lim         int32
}

type ListContactsByActivityRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Attributes  []byte
	Blocked     bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Locale      *string
	TypedEmail  *string
	ActiveAt    time.Time
}

func (q *Queries) ListContactsByActivity(ctx context.Context, arg ListContactsByActivityParams) ([]ListContactsByActivityRow, error) {
	rows, err := q.db.Query(ctx, listContactsByActivity,
		arg.WorkspaceID,
		arg.ViewerID,
		arg.Q,
		arg.Kind,
		arg.HasOpen,
		arg.CursorAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContactsByActivityRow
	for rows.Next() {
		var i ListContactsByActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Attributes,
			&i.Blocked,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Locale,
			&i.TypedEmail,
			&i.ActiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockContact = `-- name: LockContact :one
SELECT id, workspace_id, name, attributes, blocked, created_at, updated_at, locale, typed_email
FROM contacts WHERE workspace_id = $1 AND id = $2 FOR UPDATE
`

type LockContactParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

type LockContactRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Attributes  []byte
	Blocked     bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Locale      *string
	TypedEmail  *string
}

func (q *Queries) LockContact(ctx context.Context, arg LockContactParams) (LockContactRow, error) {
	row := q.db.QueryRow(ctx, lockContact, arg.WorkspaceID, arg.ID)
	var i LockContactRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Attributes,
		&i.Blocked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Locale,
		&i.TypedEmail,
	)
	return i, err
}

const moveContactExternalIDs = `-- name: MoveContactExternalIDs :exec
UPDATE contact_external_ids SET contact_id = $1
WHERE workspace_id = $2 AND contact_id = $3
`

type MoveContactExternalIDsParams struct {
	ToContact   uuid.UUID
	WorkspaceID uuid.UUID
	FromContact uuid.UUID
}

func (q *Queries) MoveContactExternalIDs(ctx context.Context, arg MoveContactExternalIDsParams) error {
	_, err := q.db.Exec(ctx, moveContactExternalIDs, arg.ToContact, arg.WorkspaceID, arg.FromContact)
	return err
}

const refreshContactSearch = `-- name: RefreshContactSearch :exec
UPDATE contacts c SET search = to_tsvector('simple', translate(concat_ws(' ',
    c.name,
    (SELECT string_agg(e.email || ' ' || translate(e.email, '@.', '  '), ' ')
     FROM contact_emails e WHERE e.workspace_id = c.workspace_id AND e.contact_id = c.id),
    (SELECT string_agg(x.external_id, ' ')
     FROM contact_external_ids x WHERE x.workspace_id = c.workspace_id AND x.contact_id = c.id)
), 'İı', 'ii'))
WHERE c.workspace_id = $1 AND c.id = $2
`

type RefreshContactSearchParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) RefreshContactSearch(ctx context.Context, arg RefreshContactSearchParams) error {
	_, err := q.db.Exec(ctx, refreshContactSearch, arg.WorkspaceID, arg.ID)
	return err
}

const updateContact = `-- name: UpdateContact :one
UPDATE contacts SET name = $1, attributes = $2, blocked = $3, updated_at = $4
WHERE workspace_id = $5 AND id = $6
RETURNING id, workspace_id, name, attributes, blocked, created_at, updated_at, locale, typed_email
`

type UpdateContactParams struct {
	Name        string
	Attributes  []byte
	Blocked     bool
	Now         time.Time
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

type UpdateContactRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Attributes  []byte
	Blocked     bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Locale      *string
	TypedEmail  *string
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (UpdateContactRow, error) {
	row := q.db.QueryRow(ctx, updateContact,
		arg.Name,
		arg.Attributes,
		arg.Blocked,
		arg.Now,
		arg.WorkspaceID,
		arg.ID,
	)
	var i UpdateContactRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Attributes,
		&i.Blocked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Locale,
		&i.TypedEmail,
	)
	return i, err
}
