// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const addConversationLabel = `-- name: AddConversationLabel :exec
INSERT INTO conversation_labels (workspace_id, conversation_id, label_id) VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddConversationLabelParams struct {
	WorkspaceID    uuid.UUID
	ConversationID uuid.UUID
	LabelID        uuid.UUID
}

func (q *Queries) AddConversationLabel(ctx context.Context, arg AddConversationLabelParams) error {
	_, err := q.db.Exec(ctx, addConversationLabel, arg.WorkspaceID, arg.ConversationID, arg.LabelID)
	return err
}

const countOpenConversations = `-- name: CountOpenConversations :many
SELECT c.inbox_id, coalesce(c.assignee_id = $1::uuid, false)::bool AS mine,
       (c.assignee_id IS NULL)::bool AS unassigned, c.spam, count(*) AS n
FROM conversations c
WHERE c.workspace_id = $2 AND c.status = 'open'
  AND ($3::bool OR EXISTS (
      SELECT 1 FROM inbox_members im
      WHERE im.workspace_id = c.workspace_id AND im.inbox_id = c.inbox_id AND im.member_id = $1::uuid))
GROUP BY 1, 2, 3, 4
`

type CountOpenConversationsParams struct {
	MemberID    *uuid.UUID
	WorkspaceID uuid.UUID
	AllInboxes  bool
}

type CountOpenConversationsRow struct {
	InboxID    uuid.UUID
	Mine       bool
	Unassigned bool
	Spam       bool
	N          int64
}

func (q *Queries) CountOpenConversations(ctx context.Context, arg CountOpenConversationsParams) ([]CountOpenConversationsRow, error) {
	rows, err := q.db.Query(ctx, countOpenConversations, arg.MemberID, arg.WorkspaceID, arg.AllInboxes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountOpenConversationsRow
	for rows.Next() {
		var i CountOpenConversationsRow
		if err := rows.Scan(
			&i.InboxID,
			&i.Mine,
			&i.Unassigned,
			&i.Spam,
			&i.N,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOpenConversationsByLabel = `-- name: CountOpenConversationsByLabel :many
SELECT cl.label_id, count(*) AS n
FROM conversations c
JOIN conversation_labels cl ON cl.workspace_id = c.workspace_id AND cl.conversation_id = c.id
WHERE c.workspace_id = $1 AND c.status = 'open' AND NOT c.spam
  AND ($2::bool OR EXISTS (
      SELECT 1 FROM inbox_members im
      WHERE im.workspace_id = c.workspace_id AND im.inbox_id = c.inbox_id AND im.member_id = $3::uuid))
GROUP BY cl.label_id
ORDER BY cl.label_id
`

type CountOpenConversationsByLabelParams struct {
	WorkspaceID uuid.UUID
	AllInboxes  bool
	MemberID    *uuid.UUID
}

type CountOpenConversationsByLabelRow struct {
	LabelID uuid.UUID
	N       int64
}

func (q *Queries) CountOpenConversationsByLabel(ctx context.Context, arg CountOpenConversationsByLabelParams) ([]CountOpenConversationsByLabelRow, error) {
	rows, err := q.db.Query(ctx, countOpenConversationsByLabel, arg.WorkspaceID, arg.AllInboxes, arg.MemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountOpenConversationsByLabelRow
	for rows.Next() {
		var i CountOpenConversationsByLabelRow
		if err := rows.Scan(&i.LabelID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (id, workspace_id, inbox_id, contact_id, channel_id, subject, priority,
                           assignee_id, spam, email_token, last_activity_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11, $11, $11)
RETURNING id, workspace_id, inbox_id, contact_id, channel_id, subject, status, snooze_until, priority, assignee_id, last_message_at, last_activity_at, created_at, updated_at, spam, email_token
`

type CreateConversationParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	InboxID     uuid.UUID
	ContactID   uuid.UUID
	ChannelID   *uuid.UUID
	Subject     string
	Priority    string
	AssigneeID  *uuid.UUID
	Spam        bool
	EmailToken  *string
	Now         time.Time
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation,
		arg.ID,
		arg.WorkspaceID,
		arg.InboxID,
		arg.ContactID,
		arg.ChannelID,
		arg.Subject,
		arg.Priority,
		arg.AssigneeID,
		arg.Spam,
		arg.EmailToken,
		arg.Now,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InboxID,
		&i.ContactID,
		&i.ChannelID,
		&i.Subject,
		&i.Status,
		&i.SnoozeUntil,
		&i.Priority,
		&i.AssigneeID,
		&i.LastMessageAt,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Spam,
		&i.EmailToken,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, workspace_id, inbox_id, contact_id, channel_id, subject, status, snooze_until, priority, assignee_id, last_message_at, last_activity_at, created_at, updated_at, spam, email_token FROM conversations WHERE workspace_id = $1 AND id = $2
`

type GetConversationParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetConversation(ctx context.Context, arg GetConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, arg.WorkspaceID, arg.ID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InboxID,
		&i.ContactID,
		&i.ChannelID,
		&i.Subject,
		&i.Status,
		&i.SnoozeUntil,
		&i.Priority,
		&i.AssigneeID,
		&i.LastMessageAt,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Spam,
		&i.EmailToken,
	)
	return i, err
}

const listConversationLabels = `-- name: ListConversationLabels :many
SELECT conversation_id, label_id FROM conversation_labels
WHERE workspace_id = $1 AND conversation_id = ANY($2::uuid[])
ORDER BY conversation_id, label_id
`

type ListConversationLabelsParams struct {
	WorkspaceID     uuid.UUID
	ConversationIds []uuid.UUID
}

type ListConversationLabelsRow struct {
	ConversationID uuid.UUID
	LabelID        uuid.UUID
}

func (q *Queries) ListConversationLabels(ctx context.Context, arg ListConversationLabelsParams) ([]ListConversationLabelsRow, error) {
	rows, err := q.db.Query(ctx, listConversationLabels, arg.WorkspaceID, arg.ConversationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationLabelsRow
	for rows.Next() {
		var i ListConversationLabelsRow
		if err := rows.Scan(&i.ConversationID, &i.LabelID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationPreviews = `-- name: ListConversationPreviews :many
SELECT c.id AS conversation_id, m.id, m.kind, m.author_type, left(m.body, 1000)::text AS body, m.created_at
FROM conversations c
CROSS JOIN LATERAL (
    SELECT lm.id, lm.kind, lm.author_type, lm.body, lm.created_at FROM messages lm
    WHERE lm.workspace_id = c.workspace_id AND lm.conversation_id = c.id AND lm.kind = 'message'
    ORDER BY lm.created_at DESC, lm.id DESC
    LIMIT 1) m
WHERE c.workspace_id = $1 AND c.id = ANY($2::uuid[])
`

type ListConversationPreviewsParams struct {
	WorkspaceID     uuid.UUID
	ConversationIds []uuid.UUID
}

type ListConversationPreviewsRow struct {
	ConversationID uuid.UUID
	ID             uuid.UUID
	Kind           string
	AuthorType     string
	Body           string
	CreatedAt      time.Time
}

func (q *Queries) ListConversationPreviews(ctx context.Context, arg ListConversationPreviewsParams) ([]ListConversationPreviewsRow, error) {
	rows, err := q.db.Query(ctx, listConversationPreviews, arg.WorkspaceID, arg.ConversationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationPreviewsRow
	for rows.Next() {
		var i ListConversationPreviewsRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.ID,
			&i.Kind,
			&i.AuthorType,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversations = `-- name: ListConversations :many
SELECT c.id, c.workspace_id, c.inbox_id, c.contact_id, c.channel_id, c.subject, c.status, c.snooze_until, c.priority, c.assignee_id, c.last_message_at, c.last_activity_at, c.created_at, c.updated_at, c.spam, c.email_token FROM conversations c
WHERE c.workspace_id = $1
  AND ($2::bool OR EXISTS (
      SELECT 1 FROM inbox_members im
      WHERE im.workspace_id = c.workspace_id AND im.inbox_id = c.inbox_id AND im.member_id = $3))
  AND ($4::uuid IS NULL OR c.inbox_id = $4::uuid)
  AND ($5::uuid IS NULL OR c.contact_id = $5::uuid)
  AND c.spam = $6::bool
  AND ($7::text IS NULL OR c.status = $7::text)
  AND (NOT $8::bool OR c.assignee_id IS NULL)
  AND ($9::uuid IS NULL OR c.assignee_id = $9::uuid)
  AND ($10::uuid IS NULL OR EXISTS (
      SELECT 1 FROM conversation_labels cl
      WHERE cl.workspace_id = c.workspace_id AND cl.conversation_id = c.id AND cl.label_id = $10::uuid))
  AND ($11::text IS NULL OR (
      to_tsvector('simple', translate(c.subject, 'İı', 'ii')) @@ websearch_to_tsquery('simple', translate($11::text, 'İı', 'ii'))
      OR EXISTS (
          SELECT 1 FROM messages m
          WHERE m.workspace_id = c.workspace_id AND m.conversation_id = c.id
            AND m.search @@ websearch_to_tsquery('simple', translate($11::text, 'İı', 'ii')))
      OR EXISTS (
          SELECT 1 FROM contacts ct
          WHERE ct.workspace_id = c.workspace_id AND ct.id = c.contact_id
            AND ct.search @@ websearch_to_tsquery('simple', translate($11::text, 'İı', 'ii')))))
  AND ($12::text IS NULL OR NOT (
      to_tsvector('simple', translate(c.subject, 'İı', 'ii')) @@ websearch_to_tsquery('simple', translate($12::text, 'İı', 'ii'))
      OR EXISTS (
          SELECT 1 FROM messages m
          WHERE m.workspace_id = c.workspace_id AND m.conversation_id = c.id
            AND m.search @@ websearch_to_tsquery('simple', translate($12::text, 'İı', 'ii')))
      OR EXISTS (
          SELECT 1 FROM contacts ct
          WHERE ct.workspace_id = c.workspace_id AND ct.id = c.contact_id
            AND ct.search @@ websearch_to_tsquery('simple', translate($12::text, 'İı', 'ii')))))
  AND ($13::timestamptz IS NULL
       OR (c.last_activity_at, c.id) < ($13::timestamptz, $14::uuid))
ORDER BY c.last_activity_at DESC, c.id DESC
LIMIT $15
`

type ListConversationsParams struct {
	WorkspaceID uuid.UUID
	AllInboxes  bool
	MemberID    uuid.UUID
	InboxID     *uuid.UUID
	ContactID   *uuid.UUID
	Spam        bool
	Status      *string
	Unassigned  bool
	AssigneeID  *uuid.UUID
	LabelID     *uuid.UUID
	Q           *string
	QNot        *string
	CursorAt    *time.Time
	CursorID    *uuid.UUID
	Lim         int32
}

func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversations,
		arg.WorkspaceID,
		arg.AllInboxes,
		arg.MemberID,
		arg.InboxID,
		arg.ContactID,
		arg.Spam,
		arg.Status,
		arg.Unassigned,
		arg.AssigneeID,
		arg.LabelID,
		arg.Q,
		arg.QNot,
		arg.CursorAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.InboxID,
			&i.ContactID,
			&i.ChannelID,
			&i.Subject,
			&i.Status,
			&i.SnoozeUntil,
			&i.Priority,
			&i.AssigneeID,
			&i.LastMessageAt,
			&i.LastActivityAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Spam,
			&i.EmailToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockConversation = `-- name: LockConversation :one
SELECT id, workspace_id, inbox_id, contact_id, channel_id, subject, status, snooze_until, priority, assignee_id, last_message_at, last_activity_at, created_at, updated_at, spam, email_token FROM conversations WHERE workspace_id = $1 AND id = $2 FOR UPDATE
`

type LockConversationParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) LockConversation(ctx context.Context, arg LockConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, lockConversation, arg.WorkspaceID, arg.ID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InboxID,
		&i.ContactID,
		&i.ChannelID,
		&i.Subject,
		&i.Status,
		&i.SnoozeUntil,
		&i.Priority,
		&i.AssigneeID,
		&i.LastMessageAt,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Spam,
		&i.EmailToken,
	)
	return i, err
}

const removeConversationLabel = `-- name: RemoveConversationLabel :exec
DELETE FROM conversation_labels WHERE workspace_id = $1 AND conversation_id = $2 AND label_id = $3
`

type RemoveConversationLabelParams struct {
	WorkspaceID    uuid.UUID
	ConversationID uuid.UUID
	LabelID        uuid.UUID
}

func (q *Queries) RemoveConversationLabel(ctx context.Context, arg RemoveConversationLabelParams) error {
	_, err := q.db.Exec(ctx, removeConversationLabel, arg.WorkspaceID, arg.ConversationID, arg.LabelID)
	return err
}

const touchConversation = `-- name: TouchConversation :exec
UPDATE conversations SET
    last_activity_at = greatest(last_activity_at, $1::timestamptz),
    last_message_at = CASE WHEN $2::bool THEN greatest(coalesce(last_message_at, $1::timestamptz), $1::timestamptz) ELSE last_message_at END,
    updated_at = $1::timestamptz
WHERE workspace_id = $3 AND id = $4
`

type TouchConversationParams struct {
	Now         time.Time
	IsMessage   bool
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) TouchConversation(ctx context.Context, arg TouchConversationParams) error {
	_, err := q.db.Exec(ctx, touchConversation,
		arg.Now,
		arg.IsMessage,
		arg.WorkspaceID,
		arg.ID,
	)
	return err
}

const updateConversation = `-- name: UpdateConversation :one
UPDATE conversations SET subject = $1, status = $2, snooze_until = $3,
    priority = $4, assignee_id = $5, spam = $6, updated_at = $7
WHERE workspace_id = $8 AND id = $9
RETURNING id, workspace_id, inbox_id, contact_id, channel_id, subject, status, snooze_until, priority, assignee_id, last_message_at, last_activity_at, created_at, updated_at, spam, email_token
`

type UpdateConversationParams struct {
	Subject     string
	Status      string
	SnoozeUntil *time.Time
	Priority    string
	AssigneeID  *uuid.UUID
	Spam        bool
	Now         time.Time
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) UpdateConversation(ctx context.Context, arg UpdateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, updateConversation,
		arg.Subject,
		arg.Status,
		arg.SnoozeUntil,
		arg.Priority,
		arg.AssigneeID,
		arg.Spam,
		arg.Now,
		arg.WorkspaceID,
		arg.ID,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InboxID,
		&i.ContactID,
		&i.ChannelID,
		&i.Subject,
		&i.Status,
		&i.SnoozeUntil,
		&i.Priority,
		&i.AssigneeID,
		&i.LastMessageAt,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Spam,
		&i.EmailToken,
	)
	return i, err
}
