// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation_reads.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const getConversationRead = `-- name: GetConversationRead :one
SELECT workspace_id, member_id, conversation_id, last_read_message_id, last_read_at, updated_at FROM conversation_reads WHERE workspace_id = $1 AND member_id = $2 AND conversation_id = $3
`

type GetConversationReadParams struct {
	WorkspaceID    uuid.UUID
	MemberID       uuid.UUID
	ConversationID uuid.UUID
}

func (q *Queries) GetConversationRead(ctx context.Context, arg GetConversationReadParams) (ConversationRead, error) {
	row := q.db.QueryRow(ctx, getConversationRead, arg.WorkspaceID, arg.MemberID, arg.ConversationID)
	var i ConversationRead
	err := row.Scan(
		&i.WorkspaceID,
		&i.MemberID,
		&i.ConversationID,
		&i.LastReadMessageID,
		&i.LastReadAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUnreadConversations = `-- name: ListUnreadConversations :many
SELECT c.id FROM conversations c
LEFT JOIN conversation_reads r
       ON r.workspace_id = c.workspace_id AND r.conversation_id = c.id AND r.member_id = $1
WHERE c.workspace_id = $2 AND c.id = ANY($3::uuid[])
  AND EXISTS (
      SELECT 1 FROM messages m
      WHERE m.workspace_id = c.workspace_id AND m.conversation_id = c.id
        AND m.kind IN ('message', 'note') AND NOT m.draft
        AND m.author_member_id IS DISTINCT FROM $1::uuid
        AND (r.last_read_at IS NULL OR (m.created_at, m.id) > (r.last_read_at, r.last_read_message_id)))
`

type ListUnreadConversationsParams struct {
	MemberID        uuid.UUID
	WorkspaceID     uuid.UUID
	ConversationIds []uuid.UUID
}

func (q *Queries) ListUnreadConversations(ctx context.Context, arg ListUnreadConversationsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUnreadConversations, arg.MemberID, arg.WorkspaceID, arg.ConversationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markConversationRead = `-- name: MarkConversationRead :one
INSERT INTO conversation_reads (workspace_id, member_id, conversation_id, last_read_message_id, last_read_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (workspace_id, member_id, conversation_id) DO UPDATE
SET last_read_message_id = excluded.last_read_message_id, last_read_at = excluded.last_read_at, updated_at = excluded.updated_at
WHERE (conversation_reads.last_read_at, conversation_reads.last_read_message_id) < (excluded.last_read_at, excluded.last_read_message_id)
RETURNING workspace_id, member_id, conversation_id, last_read_message_id, last_read_at, updated_at
`

type MarkConversationReadParams struct {
	WorkspaceID    uuid.UUID
	MemberID       uuid.UUID
	ConversationID uuid.UUID
	MessageID      uuid.UUID
	MessageAt      time.Time
	Now            time.Time
}

func (q *Queries) MarkConversationRead(ctx context.Context, arg MarkConversationReadParams) (ConversationRead, error) {
	row := q.db.QueryRow(ctx, markConversationRead,
		arg.WorkspaceID,
		arg.MemberID,
		arg.ConversationID,
		arg.MessageID,
		arg.MessageAt,
		arg.Now,
	)
	var i ConversationRead
	err := row.Scan(
		&i.WorkspaceID,
		&i.MemberID,
		&i.ConversationID,
		&i.LastReadMessageID,
		&i.LastReadAt,
		&i.UpdatedAt,
	)
	return i, err
}
