// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const claimAutoReply = `-- name: ClaimAutoReply :one
INSERT INTO email_auto_replies (workspace_id, channel_id, contact_id, sent_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (workspace_id, channel_id, contact_id) DO UPDATE SET sent_at = excluded.sent_at
WHERE email_auto_replies.sent_at <= $5
RETURNING sent_at
`

type ClaimAutoReplyParams struct {
	WorkspaceID uuid.UUID
	ChannelID   uuid.UUID
	ContactID   uuid.UUID
	Now         time.Time
	NotAfter    time.Time
}

func (q *Queries) ClaimAutoReply(ctx context.Context, arg ClaimAutoReplyParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, claimAutoReply,
		arg.WorkspaceID,
		arg.ChannelID,
		arg.ContactID,
		arg.Now,
		arg.NotAfter,
	)
	var sent_at time.Time
	err := row.Scan(&sent_at)
	return sent_at, err
}

const clearRawKeys = `-- name: ClearRawKeys :execrows
UPDATE message_emails SET raw_key = NULL, raw_size = NULL
WHERE workspace_id = $1 AND raw_key = ANY($2::text[])
`

type ClearRawKeysParams struct {
	WorkspaceID uuid.UUID
	Keys        []string
}

func (q *Queries) ClearRawKeys(ctx context.Context, arg ClearRawKeysParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearRawKeys, arg.WorkspaceID, arg.Keys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearSuppression = `-- name: ClearSuppression :exec
DELETE FROM email_suppressions WHERE workspace_id = $1 AND email = $2
`

type ClearSuppressionParams struct {
	WorkspaceID uuid.UUID
	Email       string
}

func (q *Queries) ClearSuppression(ctx context.Context, arg ClearSuppressionParams) error {
	_, err := q.db.Exec(ctx, clearSuppression, arg.WorkspaceID, arg.Email)
	return err
}

const contactReplyAddress = `-- name: ContactReplyAddress :one
SELECT e.from_address FROM message_emails e
JOIN conversations c ON c.workspace_id = e.workspace_id AND c.id = e.conversation_id
JOIN contact_emails ce ON ce.workspace_id = e.workspace_id AND ce.contact_id = c.contact_id AND ce.email = e.from_address
WHERE e.workspace_id = $1 AND e.conversation_id = $2 AND e.direction = 'in'
ORDER BY e.created_at DESC, e.message_id DESC
LIMIT 1
`

type ContactReplyAddressParams struct {
	WorkspaceID    uuid.UUID
	ConversationID uuid.UUID
}

// Replies go only to an address of the conversation's contact, never to another sender in the thread.
func (q *Queries) ContactReplyAddress(ctx context.Context, arg ContactReplyAddressParams) (string, error) {
	row := q.db.QueryRow(ctx, contactReplyAddress, arg.WorkspaceID, arg.ConversationID)
	var from_address string
	err := row.Scan(&from_address)
	return from_address, err
}

const countRecentConversations = `-- name: CountRecentConversations :one
SELECT count(*) FROM conversations
WHERE workspace_id = $1 AND channel_id = $2 AND contact_id = $3 AND created_at > $4
`

type CountRecentConversationsParams struct {
	WorkspaceID uuid.UUID
	ChannelID   *uuid.UUID
	ContactID   uuid.UUID
	Since       time.Time
}

func (q *Queries) CountRecentConversations(ctx context.Context, arg CountRecentConversationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentConversations,
		arg.WorkspaceID,
		arg.ChannelID,
		arg.ContactID,
		arg.Since,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentInboundEmails = `-- name: CountRecentInboundEmails :one
SELECT count(*) FROM message_emails e
JOIN conversations c ON c.workspace_id = e.workspace_id AND c.id = e.conversation_id
WHERE e.workspace_id = $1 AND c.contact_id = $2 AND e.direction = 'in' AND e.created_at > $3
`

type CountRecentInboundEmailsParams struct {
	WorkspaceID uuid.UUID
	ContactID   uuid.UUID
	Since       time.Time
}

func (q *Queries) CountRecentInboundEmails(ctx context.Context, arg CountRecentInboundEmailsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentInboundEmails, arg.WorkspaceID, arg.ContactID, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmailChannel = `-- name: CreateEmailChannel :one
INSERT INTO email_channels (workspace_id, channel_id, address, display_name, from_address, smtp_host, smtp_port,
                            smtp_username, smtp_password, smtp_tls, auto_reply_enabled, auto_reply_text,
                            auto_reply_interval_hours)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11, $12, $13)
ON CONFLICT (workspace_id, channel_id) DO UPDATE SET
    address = excluded.address, display_name = excluded.display_name, from_address = excluded.from_address,
    smtp_host = excluded.smtp_host, smtp_port = excluded.smtp_port, smtp_username = excluded.smtp_username,
    smtp_password = excluded.smtp_password, smtp_tls = excluded.smtp_tls,
    auto_reply_enabled = excluded.auto_reply_enabled, auto_reply_text = excluded.auto_reply_text,
    auto_reply_interval_hours = excluded.auto_reply_interval_hours
RETURNING workspace_id, channel_id, address, display_name, from_address, smtp_host, smtp_port, smtp_username, smtp_password, smtp_tls, auto_reply_enabled, auto_reply_text, auto_reply_interval_hours
`

type CreateEmailChannelParams struct {
	WorkspaceID            uuid.UUID
	ChannelID              uuid.UUID
	Address                string
	DisplayName            string
	FromAddress            *string
	SmtpHost               string
	SmtpPort               int32
	SmtpUsername           string
	SmtpPassword           []byte
	SmtpTls                string
	AutoReplyEnabled       bool
	AutoReplyText          string
	AutoReplyIntervalHours int32
}

func (q *Queries) CreateEmailChannel(ctx context.Context, arg CreateEmailChannelParams) (EmailChannel, error) {
	row := q.db.QueryRow(ctx, createEmailChannel,
		arg.WorkspaceID,
		arg.ChannelID,
		arg.Address,
		arg.DisplayName,
		arg.FromAddress,
		arg.SmtpHost,
		arg.SmtpPort,
		arg.SmtpUsername,
		arg.SmtpPassword,
		arg.SmtpTls,
		arg.AutoReplyEnabled,
		arg.AutoReplyText,
		arg.AutoReplyIntervalHours,
	)
	var i EmailChannel
	err := row.Scan(
		&i.WorkspaceID,
		&i.ChannelID,
		&i.Address,
		&i.DisplayName,
		&i.FromAddress,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpUsername,
		&i.SmtpPassword,
		&i.SmtpTls,
		&i.AutoReplyEnabled,
		&i.AutoReplyText,
		&i.AutoReplyIntervalHours,
	)
	return i, err
}

const createMessageEmail = `-- name: CreateMessageEmail :exec
INSERT INTO message_emails (workspace_id, message_id, conversation_id, channel_id, direction, header_message_id,
                            in_reply_to, references_ids, from_address, to_addresses, cc_addresses, subject,
                            full_text, full_html, quoted, headers, raw_key, raw_size, authentication_results,
                            dmarc, auto, created_at)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10, $11, $12,
        $13, $14, $15, $16, $17, $18, $19,
        $20, $21, $22)
`

type CreateMessageEmailParams struct {
	WorkspaceID           uuid.UUID
	MessageID             uuid.UUID
	ConversationID        uuid.UUID
	ChannelID             *uuid.UUID
	Direction             string
	HeaderMessageID       string
	InReplyTo             *string
	ReferencesIds         []string
	FromAddress           string
	ToAddresses           []string
	CcAddresses           []string
	Subject               string
	FullText              string
	FullHtml              *string
	Quoted                bool
	Headers               []byte
	RawKey                *string
	RawSize               *int64
	AuthenticationResults *string
	Dmarc                 string
	Auto                  bool
	CreatedAt             time.Time
}

func (q *Queries) CreateMessageEmail(ctx context.Context, arg CreateMessageEmailParams) error {
	_, err := q.db.Exec(ctx, createMessageEmail,
		arg.WorkspaceID,
		arg.MessageID,
		arg.ConversationID,
		arg.ChannelID,
		arg.Direction,
		arg.HeaderMessageID,
		arg.InReplyTo,
		arg.ReferencesIds,
		arg.FromAddress,
		arg.ToAddresses,
		arg.CcAddresses,
		arg.Subject,
		arg.FullText,
		arg.FullHtml,
		arg.Quoted,
		arg.Headers,
		arg.RawKey,
		arg.RawSize,
		arg.AuthenticationResults,
		arg.Dmarc,
		arg.Auto,
		arg.CreatedAt,
	)
	return err
}

const findConversationByEmailToken = `-- name: FindConversationByEmailToken :one
SELECT id, workspace_id, inbox_id, contact_id, channel_id, subject, status, snooze_until, priority, assignee_id, last_message_at, last_activity_at, created_at, updated_at, spam, email_token, related_conversation_id, continuity_through, continuity_sent_at, kind, feedback, email_address FROM conversations WHERE workspace_id = $1 AND inbox_id = $2 AND email_token = ANY($3::text[])
ORDER BY (contact_id = $4) DESC, created_at DESC
LIMIT 1
`

type FindConversationByEmailTokenParams struct {
	WorkspaceID uuid.UUID
	InboxID     uuid.UUID
	Tokens      []string
	ContactID   uuid.UUID
}

func (q *Queries) FindConversationByEmailToken(ctx context.Context, arg FindConversationByEmailTokenParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, findConversationByEmailToken,
		arg.WorkspaceID,
		arg.InboxID,
		arg.Tokens,
		arg.ContactID,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InboxID,
		&i.ContactID,
		&i.ChannelID,
		&i.Subject,
		&i.Status,
		&i.SnoozeUntil,
		&i.Priority,
		&i.AssigneeID,
		&i.LastMessageAt,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Spam,
		&i.EmailToken,
		&i.RelatedConversationID,
		&i.ContinuityThrough,
		&i.ContinuitySentAt,
		&i.Kind,
		&i.Feedback,
		&i.EmailAddress,
	)
	return i, err
}

const findConversationByHeaders = `-- name: FindConversationByHeaders :one
SELECT c.id, c.workspace_id, c.inbox_id, c.contact_id, c.channel_id, c.subject, c.status, c.snooze_until, c.priority, c.assignee_id, c.last_message_at, c.last_activity_at, c.created_at, c.updated_at, c.spam, c.email_token, c.related_conversation_id, c.continuity_through, c.continuity_sent_at, c.kind, c.feedback, c.email_address FROM message_emails e
JOIN conversations c ON c.workspace_id = e.workspace_id AND c.id = e.conversation_id
WHERE e.workspace_id = $1 AND c.inbox_id = $2 AND e.header_message_id = ANY($3::text[])
ORDER BY (c.contact_id = $4) DESC, e.created_at DESC, e.message_id DESC
LIMIT 1
`

type FindConversationByHeadersParams struct {
	WorkspaceID uuid.UUID
	InboxID     uuid.UUID
	Ids         []string
	ContactID   uuid.UUID
}

func (q *Queries) FindConversationByHeaders(ctx context.Context, arg FindConversationByHeadersParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, findConversationByHeaders,
		arg.WorkspaceID,
		arg.InboxID,
		arg.Ids,
		arg.ContactID,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InboxID,
		&i.ContactID,
		&i.ChannelID,
		&i.Subject,
		&i.Status,
		&i.SnoozeUntil,
		&i.Priority,
		&i.AssigneeID,
		&i.LastMessageAt,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Spam,
		&i.EmailToken,
		&i.RelatedConversationID,
		&i.ContinuityThrough,
		&i.ContinuitySentAt,
		&i.Kind,
		&i.Feedback,
		&i.EmailAddress,
	)
	return i, err
}

const findEmailChannelByAddress = `-- name: FindEmailChannelByAddress :one
SELECT e.workspace_id, e.channel_id, e.address, e.display_name, e.from_address, e.smtp_host, e.smtp_port, e.smtp_username, e.smtp_password, e.smtp_tls, e.auto_reply_enabled, e.auto_reply_text, e.auto_reply_interval_hours, c.inbox_id, c.name AS channel_name FROM email_channels e
JOIN channels c ON c.workspace_id = e.workspace_id AND c.id = e.channel_id
WHERE e.address = $1
`

type FindEmailChannelByAddressRow struct {
	WorkspaceID            uuid.UUID
	ChannelID              uuid.UUID
	Address                string
	DisplayName            string
	FromAddress            *string
	SmtpHost               string
	SmtpPort               int32
	SmtpUsername           string
	SmtpPassword           []byte
	SmtpTls                string
	AutoReplyEnabled       bool
	AutoReplyText          string
	AutoReplyIntervalHours int32
	InboxID                uuid.UUID
	ChannelName            string
}

// Inbound mail names only its recipient, so the channel is found before the workspace is known
// (see "Hosting for others later" in docs/architecture.md).
func (q *Queries) FindEmailChannelByAddress(ctx context.Context, address string) (FindEmailChannelByAddressRow, error) {
	row := q.db.QueryRow(ctx, findEmailChannelByAddress, address)
	var i FindEmailChannelByAddressRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.ChannelID,
		&i.Address,
		&i.DisplayName,
		&i.FromAddress,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpUsername,
		&i.SmtpPassword,
		&i.SmtpTls,
		&i.AutoReplyEnabled,
		&i.AutoReplyText,
		&i.AutoReplyIntervalHours,
		&i.InboxID,
		&i.ChannelName,
	)
	return i, err
}

const findInboundEmailByHeader = `-- name: FindInboundEmailByHeader :one
SELECT message_id, conversation_id FROM message_emails
WHERE workspace_id = $1 AND channel_id = $2 AND direction = 'in' AND header_message_id = $3
`

type FindInboundEmailByHeaderParams struct {
	WorkspaceID     uuid.UUID
	ChannelID       *uuid.UUID
	HeaderMessageID string
}

type FindInboundEmailByHeaderRow struct {
	MessageID      uuid.UUID
	ConversationID uuid.UUID
}

func (q *Queries) FindInboundEmailByHeader(ctx context.Context, arg FindInboundEmailByHeaderParams) (FindInboundEmailByHeaderRow, error) {
	row := q.db.QueryRow(ctx, findInboundEmailByHeader, arg.WorkspaceID, arg.ChannelID, arg.HeaderMessageID)
	var i FindInboundEmailByHeaderRow
	err := row.Scan(&i.MessageID, &i.ConversationID)
	return i, err
}

const findOutboundEmailAnyWorkspace = `-- name: FindOutboundEmailAnyWorkspace :one
SELECT e.workspace_id, e.message_id, e.conversation_id, e.to_addresses FROM message_emails e
WHERE e.direction = 'out' AND e.header_message_id = $1
LIMIT 1
`

type FindOutboundEmailAnyWorkspaceRow struct {
	WorkspaceID    uuid.UUID
	MessageID      uuid.UUID
	ConversationID uuid.UUID
	ToAddresses    []string
}

// SES reports name only our Message-ID, so the message is found before the workspace is known
// (see "Hosting for others later" in docs/architecture.md).
func (q *Queries) FindOutboundEmailAnyWorkspace(ctx context.Context, headerMessageID string) (FindOutboundEmailAnyWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, findOutboundEmailAnyWorkspace, headerMessageID)
	var i FindOutboundEmailAnyWorkspaceRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.MessageID,
		&i.ConversationID,
		&i.ToAddresses,
	)
	return i, err
}

const findOutboundEmailByHeader = `-- name: FindOutboundEmailByHeader :one
SELECT e.message_id, e.conversation_id, e.to_addresses FROM message_emails e
WHERE e.workspace_id = $1 AND e.direction = 'out' AND e.header_message_id = $2
`

type FindOutboundEmailByHeaderParams struct {
	WorkspaceID     uuid.UUID
	HeaderMessageID string
}

type FindOutboundEmailByHeaderRow struct {
	MessageID      uuid.UUID
	ConversationID uuid.UUID
	ToAddresses    []string
}

func (q *Queries) FindOutboundEmailByHeader(ctx context.Context, arg FindOutboundEmailByHeaderParams) (FindOutboundEmailByHeaderRow, error) {
	row := q.db.QueryRow(ctx, findOutboundEmailByHeader, arg.WorkspaceID, arg.HeaderMessageID)
	var i FindOutboundEmailByHeaderRow
	err := row.Scan(&i.MessageID, &i.ConversationID, &i.ToAddresses)
	return i, err
}

const getContactIDByEmail = `-- name: GetContactIDByEmail :one
SELECT contact_id FROM contact_emails WHERE workspace_id = $1 AND email = $2
`

type GetContactIDByEmailParams struct {
	WorkspaceID uuid.UUID
	Email       string
}

func (q *Queries) GetContactIDByEmail(ctx context.Context, arg GetContactIDByEmailParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getContactIDByEmail, arg.WorkspaceID, arg.Email)
	var contact_id uuid.UUID
	err := row.Scan(&contact_id)
	return contact_id, err
}

const getEmailChannel = `-- name: GetEmailChannel :one
SELECT workspace_id, channel_id, address, display_name, from_address, smtp_host, smtp_port, smtp_username, smtp_password, smtp_tls, auto_reply_enabled, auto_reply_text, auto_reply_interval_hours FROM email_channels WHERE workspace_id = $1 AND channel_id = $2
`

type GetEmailChannelParams struct {
	WorkspaceID uuid.UUID
	ChannelID   uuid.UUID
}

func (q *Queries) GetEmailChannel(ctx context.Context, arg GetEmailChannelParams) (EmailChannel, error) {
	row := q.db.QueryRow(ctx, getEmailChannel, arg.WorkspaceID, arg.ChannelID)
	var i EmailChannel
	err := row.Scan(
		&i.WorkspaceID,
		&i.ChannelID,
		&i.Address,
		&i.DisplayName,
		&i.FromAddress,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpUsername,
		&i.SmtpPassword,
		&i.SmtpTls,
		&i.AutoReplyEnabled,
		&i.AutoReplyText,
		&i.AutoReplyIntervalHours,
	)
	return i, err
}

const getMessageEmail = `-- name: GetMessageEmail :one
SELECT workspace_id, message_id, conversation_id, channel_id, direction, header_message_id, in_reply_to, references_ids, from_address, to_addresses, cc_addresses, subject, full_text, full_html, quoted, headers, raw_key, raw_size, authentication_results, dmarc, auto, created_at FROM message_emails WHERE workspace_id = $1 AND message_id = $2
`

type GetMessageEmailParams struct {
	WorkspaceID uuid.UUID
	MessageID   uuid.UUID
}

func (q *Queries) GetMessageEmail(ctx context.Context, arg GetMessageEmailParams) (MessageEmail, error) {
	row := q.db.QueryRow(ctx, getMessageEmail, arg.WorkspaceID, arg.MessageID)
	var i MessageEmail
	err := row.Scan(
		&i.WorkspaceID,
		&i.MessageID,
		&i.ConversationID,
		&i.ChannelID,
		&i.Direction,
		&i.HeaderMessageID,
		&i.InReplyTo,
		&i.ReferencesIds,
		&i.FromAddress,
		&i.ToAddresses,
		&i.CcAddresses,
		&i.Subject,
		&i.FullText,
		&i.FullHtml,
		&i.Quoted,
		&i.Headers,
		&i.RawKey,
		&i.RawSize,
		&i.AuthenticationResults,
		&i.Dmarc,
		&i.Auto,
		&i.CreatedAt,
	)
	return i, err
}

const isEmailChannelSender = `-- name: IsEmailChannelSender :one
SELECT EXISTS (SELECT 1 FROM email_channels WHERE address = $1::text OR from_address = $1::text)
`

// Mail from an address the server sends from is dropped, whichever workspace it belongs to.
func (q *Queries) IsEmailChannelSender(ctx context.Context, address string) (bool, error) {
	row := q.db.QueryRow(ctx, isEmailChannelSender, address)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isEmailSuppressed = `-- name: IsEmailSuppressed :one
SELECT EXISTS (SELECT 1 FROM email_suppressions WHERE workspace_id = $1 AND email = $2) AS suppressed
`

type IsEmailSuppressedParams struct {
	WorkspaceID uuid.UUID
	Email       string
}

func (q *Queries) IsEmailSuppressed(ctx context.Context, arg IsEmailSuppressedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isEmailSuppressed, arg.WorkspaceID, arg.Email)
	var suppressed bool
	err := row.Scan(&suppressed)
	return suppressed, err
}

const latestContactConversation = `-- name: LatestContactConversation :one
SELECT id, workspace_id, inbox_id, contact_id, channel_id, subject, status, snooze_until, priority, assignee_id, last_message_at, last_activity_at, created_at, updated_at, spam, email_token, related_conversation_id, continuity_through, continuity_sent_at, kind, feedback, email_address FROM conversations
WHERE workspace_id = $1 AND channel_id = $2 AND contact_id = $3
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type LatestContactConversationParams struct {
	WorkspaceID uuid.UUID
	ChannelID   *uuid.UUID
	ContactID   uuid.UUID
}

func (q *Queries) LatestContactConversation(ctx context.Context, arg LatestContactConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, latestContactConversation, arg.WorkspaceID, arg.ChannelID, arg.ContactID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InboxID,
		&i.ContactID,
		&i.ChannelID,
		&i.Subject,
		&i.Status,
		&i.SnoozeUntil,
		&i.Priority,
		&i.AssigneeID,
		&i.LastMessageAt,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Spam,
		&i.EmailToken,
		&i.RelatedConversationID,
		&i.ContinuityThrough,
		&i.ContinuitySentAt,
		&i.Kind,
		&i.Feedback,
		&i.EmailAddress,
	)
	return i, err
}

const latestThreadEmail = `-- name: LatestThreadEmail :one
SELECT header_message_id, in_reply_to, references_ids, from_address, direction FROM message_emails
WHERE workspace_id = $1 AND conversation_id = $2 AND message_id <> $3
ORDER BY created_at DESC, message_id DESC
LIMIT 1
`

type LatestThreadEmailParams struct {
	WorkspaceID      uuid.UUID
	ConversationID   uuid.UUID
	ExcludeMessageID uuid.UUID
}

type LatestThreadEmailRow struct {
	HeaderMessageID string
	InReplyTo       *string
	ReferencesIds   []string
	FromAddress     string
	Direction       string
}

func (q *Queries) LatestThreadEmail(ctx context.Context, arg LatestThreadEmailParams) (LatestThreadEmailRow, error) {
	row := q.db.QueryRow(ctx, latestThreadEmail, arg.WorkspaceID, arg.ConversationID, arg.ExcludeMessageID)
	var i LatestThreadEmailRow
	err := row.Scan(
		&i.HeaderMessageID,
		&i.InReplyTo,
		&i.ReferencesIds,
		&i.FromAddress,
		&i.Direction,
	)
	return i, err
}

const listContactRawKeys = `-- name: ListContactRawKeys :many
SELECT e.raw_key::text FROM message_emails e
JOIN conversations c ON c.workspace_id = e.workspace_id AND c.id = e.conversation_id
WHERE e.workspace_id = $1 AND c.contact_id = $2 AND e.raw_key IS NOT NULL
`

type ListContactRawKeysParams struct {
	WorkspaceID uuid.UUID
	ContactID   uuid.UUID
}

func (q *Queries) ListContactRawKeys(ctx context.Context, arg ListContactRawKeysParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listContactRawKeys, arg.WorkspaceID, arg.ContactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var e_raw_key string
		if err := rows.Scan(&e_raw_key); err != nil {
			return nil, err
		}
		items = append(items, e_raw_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactSuppressions = `-- name: ListContactSuppressions :many
SELECT e.contact_id, s.email, s.reason, s.detail, s.created_at FROM email_suppressions s
JOIN contact_emails e ON e.workspace_id = s.workspace_id AND e.email = s.email
WHERE s.workspace_id = $1 AND e.contact_id = ANY($2::uuid[])
ORDER BY e.contact_id, e.position
`

type ListContactSuppressionsParams struct {
	WorkspaceID uuid.UUID
	ContactIds  []uuid.UUID
}

type ListContactSuppressionsRow struct {
	ContactID uuid.UUID
	Email     string
	Reason    string
	Detail    string
	CreatedAt time.Time
}

func (q *Queries) ListContactSuppressions(ctx context.Context, arg ListContactSuppressionsParams) ([]ListContactSuppressionsRow, error) {
	rows, err := q.db.Query(ctx, listContactSuppressions, arg.WorkspaceID, arg.ContactIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContactSuppressionsRow
	for rows.Next() {
		var i ListContactSuppressionsRow
		if err := rows.Scan(
			&i.ContactID,
			&i.Email,
			&i.Reason,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationsRawKeys = `-- name: ListConversationsRawKeys :many
SELECT raw_key::text FROM message_emails
WHERE workspace_id = $1 AND conversation_id = ANY($2::uuid[]) AND raw_key IS NOT NULL
`

type ListConversationsRawKeysParams struct {
	WorkspaceID uuid.UUID
	Ids         []uuid.UUID
}

func (q *Queries) ListConversationsRawKeys(ctx context.Context, arg ListConversationsRawKeysParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listConversationsRawKeys, arg.WorkspaceID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var raw_key string
		if err := rows.Scan(&raw_key); err != nil {
			return nil, err
		}
		items = append(items, raw_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailChannels = `-- name: ListEmailChannels :many
SELECT workspace_id, channel_id, address, display_name, from_address, smtp_host, smtp_port, smtp_username, smtp_password, smtp_tls, auto_reply_enabled, auto_reply_text, auto_reply_interval_hours FROM email_channels WHERE workspace_id = $1 AND channel_id = ANY($2::uuid[])
`

type ListEmailChannelsParams struct {
	WorkspaceID uuid.UUID
	ChannelIds  []uuid.UUID
}

func (q *Queries) ListEmailChannels(ctx context.Context, arg ListEmailChannelsParams) ([]EmailChannel, error) {
	rows, err := q.db.Query(ctx, listEmailChannels, arg.WorkspaceID, arg.ChannelIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailChannel
	for rows.Next() {
		var i EmailChannel
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ChannelID,
			&i.Address,
			&i.DisplayName,
			&i.FromAddress,
			&i.SmtpHost,
			&i.SmtpPort,
			&i.SmtpUsername,
			&i.SmtpPassword,
			&i.SmtpTls,
			&i.AutoReplyEnabled,
			&i.AutoReplyText,
			&i.AutoReplyIntervalHours,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredRawKeys = `-- name: ListExpiredRawKeys :many
SELECT raw_key::text FROM message_emails
WHERE workspace_id = $1 AND raw_key IS NOT NULL AND created_at < $2
ORDER BY created_at
LIMIT $3
`

type ListExpiredRawKeysParams struct {
	WorkspaceID uuid.UUID
	Before      time.Time
	MaxRows     int32
}

func (q *Queries) ListExpiredRawKeys(ctx context.Context, arg ListExpiredRawKeysParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listExpiredRawKeys, arg.WorkspaceID, arg.Before, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var raw_key string
		if err := rows.Scan(&raw_key); err != nil {
			return nil, err
		}
		items = append(items, raw_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInboxRawKeys = `-- name: ListInboxRawKeys :many
SELECT e.raw_key::text FROM message_emails e
JOIN conversations c ON c.workspace_id = e.workspace_id AND c.id = e.conversation_id
WHERE e.workspace_id = $1 AND c.inbox_id = $2 AND e.raw_key IS NOT NULL
`

type ListInboxRawKeysParams struct {
	WorkspaceID uuid.UUID
	InboxID     uuid.UUID
}

func (q *Queries) ListInboxRawKeys(ctx context.Context, arg ListInboxRawKeysParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listInboxRawKeys, arg.WorkspaceID, arg.InboxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var e_raw_key string
		if err := rows.Scan(&e_raw_key); err != nil {
			return nil, err
		}
		items = append(items, e_raw_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessageEmails = `-- name: ListMessageEmails :many
SELECT e.message_id, e.direction, e.header_message_id, e.from_address, e.to_addresses, e.cc_addresses, e.subject, e.quoted,
       (e.raw_key IS NOT NULL)::bool AS has_raw, e.auto, e.dmarc,
       (e.direction = 'in' AND NOT EXISTS (
           SELECT 1 FROM contact_emails ce
           WHERE ce.workspace_id = e.workspace_id AND ce.contact_id = c.contact_id AND ce.email = e.from_address
       ))::bool AS unverified_sender
FROM message_emails e
JOIN conversations c ON c.workspace_id = e.workspace_id AND c.id = e.conversation_id
WHERE e.workspace_id = $1 AND e.message_id = ANY($2::uuid[])
`

type ListMessageEmailsParams struct {
	WorkspaceID uuid.UUID
	MessageIds  []uuid.UUID
}

type ListMessageEmailsRow struct {
	MessageID        uuid.UUID
	Direction        string
	HeaderMessageID  string
	FromAddress      string
	ToAddresses      []string
	CcAddresses      []string
	Subject          string
	Quoted           bool
	HasRaw           bool
	Auto             bool
	Dmarc            string
	UnverifiedSender bool
}

func (q *Queries) ListMessageEmails(ctx context.Context, arg ListMessageEmailsParams) ([]ListMessageEmailsRow, error) {
	rows, err := q.db.Query(ctx, listMessageEmails, arg.WorkspaceID, arg.MessageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessageEmailsRow
	for rows.Next() {
		var i ListMessageEmailsRow
		if err := rows.Scan(
			&i.MessageID,
			&i.Direction,
			&i.HeaderMessageID,
			&i.FromAddress,
			&i.ToAddresses,
			&i.CcAddresses,
			&i.Subject,
			&i.Quoted,
			&i.HasRaw,
			&i.Auto,
			&i.Dmarc,
			&i.UnverifiedSender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setConversationEmailToken = `-- name: SetConversationEmailToken :one
UPDATE conversations SET email_token = coalesce(email_token, $1::text)
WHERE workspace_id = $2 AND id = $3
RETURNING email_token::text
`

type SetConversationEmailTokenParams struct {
	Token       string
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) SetConversationEmailToken(ctx context.Context, arg SetConversationEmailTokenParams) (string, error) {
	row := q.db.QueryRow(ctx, setConversationEmailToken, arg.Token, arg.WorkspaceID, arg.ID)
	var email_token string
	err := row.Scan(&email_token)
	return email_token, err
}

const setConversationSpam = `-- name: SetConversationSpam :exec
UPDATE conversations SET spam = $1 WHERE workspace_id = $2 AND id = $3
`

type SetConversationSpamParams struct {
	Spam        bool
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) SetConversationSpam(ctx context.Context, arg SetConversationSpamParams) error {
	_, err := q.db.Exec(ctx, setConversationSpam, arg.Spam, arg.WorkspaceID, arg.ID)
	return err
}

const suppressEmail = `-- name: SuppressEmail :exec
INSERT INTO email_suppressions (workspace_id, email, reason, detail, created_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (workspace_id, email) DO UPDATE SET reason = excluded.reason, detail = excluded.detail, created_at = excluded.created_at
`

type SuppressEmailParams struct {
	WorkspaceID uuid.UUID
	Email       string
	Reason      string
	Detail      string
	Now         time.Time
}

func (q *Queries) SuppressEmail(ctx context.Context, arg SuppressEmailParams) error {
	_, err := q.db.Exec(ctx, suppressEmail,
		arg.WorkspaceID,
		arg.Email,
		arg.Reason,
		arg.Detail,
		arg.Now,
	)
	return err
}
