// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const deleteEventsBefore = `-- name: DeleteEventsBefore :execrows
DELETE FROM events WHERE workspace_id = $1 AND created_at < $2
`

type DeleteEventsBeforeParams struct {
	WorkspaceID uuid.UUID
	Before      time.Time
}

func (q *Queries) DeleteEventsBefore(ctx context.Context, arg DeleteEventsBeforeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEventsBefore, arg.WorkspaceID, arg.Before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const eventExists = `-- name: EventExists :one
SELECT EXISTS (SELECT 1 FROM events WHERE workspace_id = $1 AND id = $2) AS found
`

type EventExistsParams struct {
	WorkspaceID uuid.UUID
	ID          int64
}

func (q *Queries) EventExists(ctx context.Context, arg EventExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, eventExists, arg.WorkspaceID, arg.ID)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const getEvent = `-- name: GetEvent :one
SELECT id, workspace_id, type, inbox_id, conversation_id, payload, created_at FROM events WHERE workspace_id = $1 AND id = $2
`

type GetEventParams struct {
	WorkspaceID uuid.UUID
	ID          int64
}

func (q *Queries) GetEvent(ctx context.Context, arg GetEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, arg.WorkspaceID, arg.ID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Type,
		&i.InboxID,
		&i.ConversationID,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (workspace_id, type, inbox_id, conversation_id, payload)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertEventParams struct {
	WorkspaceID    uuid.UUID
	Type           string
	InboxID        *uuid.UUID
	ConversationID *uuid.UUID
	Payload        []byte
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.WorkspaceID,
		arg.Type,
		arg.InboxID,
		arg.ConversationID,
		arg.Payload,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lastEventID = `-- name: LastEventID :one
SELECT coalesce(max(id), 0)::bigint AS id FROM events WHERE workspace_id = $1
`

func (q *Queries) LastEventID(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, lastEventID, workspaceID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listEventsAfter = `-- name: ListEventsAfter :many
SELECT id, workspace_id, type, inbox_id, conversation_id, payload, created_at FROM events WHERE workspace_id = $1 AND id > $2 ORDER BY id LIMIT $3
`

type ListEventsAfterParams struct {
	WorkspaceID uuid.UUID
	After       int64
	Lim         int32
}

func (q *Queries) ListEventsAfter(ctx context.Context, arg ListEventsAfterParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsAfter, arg.WorkspaceID, arg.After, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Type,
			&i.InboxID,
			&i.ConversationID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEventStream = `-- name: LockEventStream :exec
SELECT pg_advisory_xact_lock(hashtextextended('yuva_events:' || $1::uuid::text, 0))
`

func (q *Queries) LockEventStream(ctx context.Context, workspaceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockEventStream, workspaceID)
	return err
}

const notifyEvent = `-- name: NotifyEvent :exec
SELECT pg_notify($1::text, $2::uuid::text || ':' || $3::bigint::text)
`

type NotifyEventParams struct {
	Channel     string
	WorkspaceID uuid.UUID
	ID          int64
}

func (q *Queries) NotifyEvent(ctx context.Context, arg NotifyEventParams) error {
	_, err := q.db.Exec(ctx, notifyEvent, arg.Channel, arg.WorkspaceID, arg.ID)
	return err
}

const notifySignal = `-- name: NotifySignal :exec
SELECT pg_notify($1::text, $2::text)
`

type NotifySignalParams struct {
	Channel string
	Payload string
}

func (q *Queries) NotifySignal(ctx context.Context, arg NotifySignalParams) error {
	_, err := q.db.Exec(ctx, notifySignal, arg.Channel, arg.Payload)
	return err
}
