// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const claimIdempotencyKey = `-- name: ClaimIdempotencyKey :execrows
INSERT INTO idempotency_keys (workspace_id, caller_type, caller_id, key, method, path, body_sha256, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (workspace_id, caller_type, caller_id, key) DO UPDATE
SET method = excluded.method, path = excluded.path, body_sha256 = excluded.body_sha256, status = NULL,
    headers = NULL, body = NULL, created_at = excluded.created_at
WHERE idempotency_keys.created_at < $9::timestamptz
`

type ClaimIdempotencyKeyParams struct {
	WorkspaceID uuid.UUID
	CallerType  string
	CallerID    uuid.UUID
	Key         string
	Method      string
	Path        string
	BodySha256  []byte
	Now         time.Time
	StaleBefore time.Time
}

func (q *Queries) ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimIdempotencyKey,
		arg.WorkspaceID,
		arg.CallerType,
		arg.CallerID,
		arg.Key,
		arg.Method,
		arg.Path,
		arg.BodySha256,
		arg.Now,
		arg.StaleBefore,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :exec
UPDATE idempotency_keys SET status = $1, headers = $2, body = $3
WHERE workspace_id = $4 AND caller_type = $5 AND caller_id = $6 AND key = $7
`

type CompleteIdempotencyKeyParams struct {
	Status      *int32
	Headers     []byte
	Body        []byte
	WorkspaceID uuid.UUID
	CallerType  string
	CallerID    uuid.UUID
	Key         string
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, completeIdempotencyKey,
		arg.Status,
		arg.Headers,
		arg.Body,
		arg.WorkspaceID,
		arg.CallerType,
		arg.CallerID,
		arg.Key,
	)
	return err
}

const deleteIdempotencyKeysBefore = `-- name: DeleteIdempotencyKeysBefore :execrows
DELETE FROM idempotency_keys WHERE workspace_id = $1 AND created_at < $2
`

type DeleteIdempotencyKeysBeforeParams struct {
	WorkspaceID uuid.UUID
	Before      time.Time
}

func (q *Queries) DeleteIdempotencyKeysBefore(ctx context.Context, arg DeleteIdempotencyKeysBeforeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIdempotencyKeysBefore, arg.WorkspaceID, arg.Before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT workspace_id, caller_type, caller_id, key, method, path, body_sha256, status, headers, body, created_at FROM idempotency_keys
WHERE workspace_id = $1 AND caller_type = $2 AND caller_id = $3 AND key = $4
`

type GetIdempotencyKeyParams struct {
	WorkspaceID uuid.UUID
	CallerType  string
	CallerID    uuid.UUID
	Key         string
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey,
		arg.WorkspaceID,
		arg.CallerType,
		arg.CallerID,
		arg.Key,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.WorkspaceID,
		&i.CallerType,
		&i.CallerID,
		&i.Key,
		&i.Method,
		&i.Path,
		&i.BodySha256,
		&i.Status,
		&i.Headers,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const releaseIdempotencyKey = `-- name: ReleaseIdempotencyKey :exec
DELETE FROM idempotency_keys
WHERE workspace_id = $1 AND caller_type = $2 AND caller_id = $3 AND key = $4
  AND status IS NULL
`

type ReleaseIdempotencyKeyParams struct {
	WorkspaceID uuid.UUID
	CallerType  string
	CallerID    uuid.UUID
	Key         string
}

func (q *Queries) ReleaseIdempotencyKey(ctx context.Context, arg ReleaseIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, releaseIdempotencyKey,
		arg.WorkspaceID,
		arg.CallerType,
		arg.CallerID,
		arg.Key,
	)
	return err
}
