// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inboxes.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const createInbox = `-- name: CreateInbox :one
INSERT INTO inboxes (id, workspace_id, name, slug, branding, default_locale, timezone, mode,
                     expected_reply_minutes, business_hours, identity_secret, ask_for_rating, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        $9, $10, $11, coalesce($12::bool, false), $13, $13)
RETURNING id, workspace_id, name, slug, branding, default_locale, timezone, mode, expected_reply_minutes, business_hours, identity_secret, created_at, updated_at, ask_for_rating
`

type CreateInboxParams struct {
	ID                   uuid.UUID
	WorkspaceID          uuid.UUID
	Name                 string
	Slug                 string
	Branding             []byte
	DefaultLocale        string
	Timezone             string
	Mode                 string
	ExpectedReplyMinutes *int32
	BusinessHours        []byte
	IdentitySecret       []byte
	AskForRating         *bool
	Now                  time.Time
}

func (q *Queries) CreateInbox(ctx context.Context, arg CreateInboxParams) (Inbox, error) {
	row := q.db.QueryRow(ctx, createInbox,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Slug,
		arg.Branding,
		arg.DefaultLocale,
		arg.Timezone,
		arg.Mode,
		arg.ExpectedReplyMinutes,
		arg.BusinessHours,
		arg.IdentitySecret,
		arg.AskForRating,
		arg.Now,
	)
	var i Inbox
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.Branding,
		&i.DefaultLocale,
		&i.Timezone,
		&i.Mode,
		&i.ExpectedReplyMinutes,
		&i.BusinessHours,
		&i.IdentitySecret,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AskForRating,
	)
	return i, err
}

const deleteInbox = `-- name: DeleteInbox :execrows
DELETE FROM inboxes WHERE workspace_id = $1 AND id = $2
`

type DeleteInboxParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) DeleteInbox(ctx context.Context, arg DeleteInboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInbox, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInbox = `-- name: GetInbox :one
SELECT id, workspace_id, name, slug, branding, default_locale, timezone, mode, expected_reply_minutes, business_hours, identity_secret, created_at, updated_at, ask_for_rating FROM inboxes WHERE workspace_id = $1 AND id = $2
`

type GetInboxParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetInbox(ctx context.Context, arg GetInboxParams) (Inbox, error) {
	row := q.db.QueryRow(ctx, getInbox, arg.WorkspaceID, arg.ID)
	var i Inbox
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.Branding,
		&i.DefaultLocale,
		&i.Timezone,
		&i.Mode,
		&i.ExpectedReplyMinutes,
		&i.BusinessHours,
		&i.IdentitySecret,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AskForRating,
	)
	return i, err
}

const grantInboxAccess = `-- name: GrantInboxAccess :execrows
INSERT INTO inbox_members (workspace_id, inbox_id, member_id, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type GrantInboxAccessParams struct {
	WorkspaceID uuid.UUID
	InboxID     uuid.UUID
	MemberID    uuid.UUID
	Now         time.Time
}

func (q *Queries) GrantInboxAccess(ctx context.Context, arg GrantInboxAccessParams) (int64, error) {
	result, err := q.db.Exec(ctx, grantInboxAccess,
		arg.WorkspaceID,
		arg.InboxID,
		arg.MemberID,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const hasInboxAccess = `-- name: HasInboxAccess :one
SELECT EXISTS (
    SELECT 1 FROM inbox_members WHERE workspace_id = $1 AND inbox_id = $2 AND member_id = $3
) AS access
`

type HasInboxAccessParams struct {
	WorkspaceID uuid.UUID
	InboxID     uuid.UUID
	MemberID    uuid.UUID
}

func (q *Queries) HasInboxAccess(ctx context.Context, arg HasInboxAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasInboxAccess, arg.WorkspaceID, arg.InboxID, arg.MemberID)
	var access bool
	err := row.Scan(&access)
	return access, err
}

const listInboxMembers = `-- name: ListInboxMembers :many
SELECT m.id, m.workspace_id, m.person_id, m.role, m.created_at, p.email, p.name
FROM inbox_members im
JOIN members m ON m.workspace_id = im.workspace_id AND m.id = im.member_id
JOIN people p ON p.id = m.person_id
WHERE im.workspace_id = $1 AND im.inbox_id = $2
ORDER BY m.created_at, m.id
`

type ListInboxMembersParams struct {
	WorkspaceID uuid.UUID
	InboxID     uuid.UUID
}

type ListInboxMembersRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	PersonID    uuid.UUID
	Role        string
	CreatedAt   time.Time
	Email       string
	Name        string
}

func (q *Queries) ListInboxMembers(ctx context.Context, arg ListInboxMembersParams) ([]ListInboxMembersRow, error) {
	rows, err := q.db.Query(ctx, listInboxMembers, arg.WorkspaceID, arg.InboxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInboxMembersRow
	for rows.Next() {
		var i ListInboxMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.PersonID,
			&i.Role,
			&i.CreatedAt,
			&i.Email,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInboxStorageKeys = `-- name: ListInboxStorageKeys :many
SELECT a.storage_key FROM attachments a
JOIN conversations c ON c.workspace_id = a.workspace_id AND c.id = a.conversation_id
WHERE a.workspace_id = $1 AND c.inbox_id = $2
`

type ListInboxStorageKeysParams struct {
	WorkspaceID uuid.UUID
	InboxID     uuid.UUID
}

func (q *Queries) ListInboxStorageKeys(ctx context.Context, arg ListInboxStorageKeysParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listInboxStorageKeys, arg.WorkspaceID, arg.InboxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var storage_key string
		if err := rows.Scan(&storage_key); err != nil {
			return nil, err
		}
		items = append(items, storage_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInboxes = `-- name: ListInboxes :many
SELECT i.id, i.workspace_id, i.name, i.slug, i.branding, i.default_locale, i.timezone, i.mode, i.expected_reply_minutes, i.business_hours, i.identity_secret, i.created_at, i.updated_at, i.ask_for_rating FROM inboxes i
WHERE i.workspace_id = $1
  AND ($2::bool OR EXISTS (
      SELECT 1 FROM inbox_viewers iv
      WHERE iv.workspace_id = i.workspace_id AND iv.inbox_id = i.id AND iv.viewer_id = $3))
ORDER BY i.name, i.id
`

type ListInboxesParams struct {
	WorkspaceID uuid.UUID
	AllInboxes  bool
	ViewerID    uuid.UUID
}

func (q *Queries) ListInboxes(ctx context.Context, arg ListInboxesParams) ([]Inbox, error) {
	rows, err := q.db.Query(ctx, listInboxes, arg.WorkspaceID, arg.AllInboxes, arg.ViewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Inbox
	for rows.Next() {
		var i Inbox
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Slug,
			&i.Branding,
			&i.DefaultLocale,
			&i.Timezone,
			&i.Mode,
			&i.ExpectedReplyMinutes,
			&i.BusinessHours,
			&i.IdentitySecret,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AskForRating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listViewerInboxIDs = `-- name: ListViewerInboxIDs :many
SELECT inbox_id FROM inbox_viewers WHERE workspace_id = $1 AND viewer_id = $2
`

type ListViewerInboxIDsParams struct {
	WorkspaceID uuid.UUID
	ViewerID    uuid.UUID
}

func (q *Queries) ListViewerInboxIDs(ctx context.Context, arg ListViewerInboxIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listViewerInboxIDs, arg.WorkspaceID, arg.ViewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var inbox_id uuid.UUID
		if err := rows.Scan(&inbox_id); err != nil {
			return nil, err
		}
		items = append(items, inbox_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockInbox = `-- name: LockInbox :one
SELECT id, workspace_id, name, slug, branding, default_locale, timezone, mode, expected_reply_minutes, business_hours, identity_secret, created_at, updated_at, ask_for_rating FROM inboxes WHERE workspace_id = $1 AND id = $2 FOR UPDATE
`

type LockInboxParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) LockInbox(ctx context.Context, arg LockInboxParams) (Inbox, error) {
	row := q.db.QueryRow(ctx, lockInbox, arg.WorkspaceID, arg.ID)
	var i Inbox
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.Branding,
		&i.DefaultLocale,
		&i.Timezone,
		&i.Mode,
		&i.ExpectedReplyMinutes,
		&i.BusinessHours,
		&i.IdentitySecret,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AskForRating,
	)
	return i, err
}

const revokeInboxAccess = `-- name: RevokeInboxAccess :execrows
DELETE FROM inbox_members WHERE workspace_id = $1 AND inbox_id = $2 AND member_id = $3
`

type RevokeInboxAccessParams struct {
	WorkspaceID uuid.UUID
	InboxID     uuid.UUID
	MemberID    uuid.UUID
}

func (q *Queries) RevokeInboxAccess(ctx context.Context, arg RevokeInboxAccessParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeInboxAccess, arg.WorkspaceID, arg.InboxID, arg.MemberID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setInboxIdentitySecret = `-- name: SetInboxIdentitySecret :execrows
UPDATE inboxes SET identity_secret = $1, updated_at = $2
WHERE workspace_id = $3 AND id = $4
`

type SetInboxIdentitySecretParams struct {
	IdentitySecret []byte
	Now            time.Time
	WorkspaceID    uuid.UUID
	ID             uuid.UUID
}

func (q *Queries) SetInboxIdentitySecret(ctx context.Context, arg SetInboxIdentitySecretParams) (int64, error) {
	result, err := q.db.Exec(ctx, setInboxIdentitySecret,
		arg.IdentitySecret,
		arg.Now,
		arg.WorkspaceID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateInbox = `-- name: UpdateInbox :one
UPDATE inboxes SET name = $1, slug = $2, branding = $3, default_locale = $4,
    timezone = $5, mode = $6, expected_reply_minutes = $7,
    business_hours = $8, ask_for_rating = $9, updated_at = $10
WHERE workspace_id = $11 AND id = $12
RETURNING id, workspace_id, name, slug, branding, default_locale, timezone, mode, expected_reply_minutes, business_hours, identity_secret, created_at, updated_at, ask_for_rating
`

type UpdateInboxParams struct {
	Name                 string
	Slug                 string
	Branding             []byte
	DefaultLocale        string
	Timezone             string
	Mode                 string
	ExpectedReplyMinutes *int32
	BusinessHours        []byte
	AskForRating         bool
	Now                  time.Time
	WorkspaceID          uuid.UUID
	ID                   uuid.UUID
}

func (q *Queries) UpdateInbox(ctx context.Context, arg UpdateInboxParams) (Inbox, error) {
	row := q.db.QueryRow(ctx, updateInbox,
		arg.Name,
		arg.Slug,
		arg.Branding,
		arg.DefaultLocale,
		arg.Timezone,
		arg.Mode,
		arg.ExpectedReplyMinutes,
		arg.BusinessHours,
		arg.AskForRating,
		arg.Now,
		arg.WorkspaceID,
		arg.ID,
	)
	var i Inbox
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.Branding,
		&i.DefaultLocale,
		&i.Timezone,
		&i.Mode,
		&i.ExpectedReplyMinutes,
		&i.BusinessHours,
		&i.IdentitySecret,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AskForRating,
	)
	return i, err
}

const viewerHasInbox = `-- name: ViewerHasInbox :one
SELECT EXISTS (
    SELECT 1 FROM inbox_viewers WHERE workspace_id = $1 AND inbox_id = $2 AND viewer_id = $3
) AS access
`

type ViewerHasInboxParams struct {
	WorkspaceID uuid.UUID
	InboxID     uuid.UUID
	ViewerID    uuid.UUID
}

func (q *Queries) ViewerHasInbox(ctx context.Context, arg ViewerHasInboxParams) (bool, error) {
	row := q.db.QueryRow(ctx, viewerHasInbox, arg.WorkspaceID, arg.InboxID, arg.ViewerID)
	var access bool
	err := row.Scan(&access)
	return access, err
}
