// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const deleteInvite = `-- name: DeleteInvite :execrows
DELETE FROM invites WHERE workspace_id = $1 AND id = $2
`

type DeleteInviteParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) DeleteInvite(ctx context.Context, arg DeleteInviteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInvite, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const latestPendingInvite = `-- name: LatestPendingInvite :one
SELECT i.id, i.workspace_id, i.email, i.role, i.locale, i.invited_by, i.created_at, i.expires_at FROM invites i JOIN workspaces w ON w.id = i.workspace_id
WHERE i.email = $1 AND i.expires_at > $2 AND w.deleted_at IS NULL
ORDER BY i.created_at DESC LIMIT 1
`

type LatestPendingInviteParams struct {
	Email string
	Now   time.Time
}

func (q *Queries) LatestPendingInvite(ctx context.Context, arg LatestPendingInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, latestPendingInvite, arg.Email, arg.Now)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.Locale,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listInvites = `-- name: ListInvites :many
SELECT id, workspace_id, email, role, locale, invited_by, created_at, expires_at FROM invites WHERE workspace_id = $1 AND expires_at > $2 ORDER BY created_at, id
`

type ListInvitesParams struct {
	WorkspaceID uuid.UUID
	ExpiresAt   time.Time
}

func (q *Queries) ListInvites(ctx context.Context, arg ListInvitesParams) ([]Invite, error) {
	rows, err := q.db.Query(ctx, listInvites, arg.WorkspaceID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invite
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Email,
			&i.Role,
			&i.Locale,
			&i.InvitedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const takePendingInvites = `-- name: TakePendingInvites :many
DELETE FROM invites WHERE email = $1 AND expires_at > $2
  AND workspace_id IN (SELECT id FROM workspaces WHERE deleted_at IS NULL)
RETURNING id, workspace_id, email, role, locale, invited_by, created_at, expires_at
`

type TakePendingInvitesParams struct {
	Email string
	Now   time.Time
}

func (q *Queries) TakePendingInvites(ctx context.Context, arg TakePendingInvitesParams) ([]Invite, error) {
	rows, err := q.db.Query(ctx, takePendingInvites, arg.Email, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invite
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Email,
			&i.Role,
			&i.Locale,
			&i.InvitedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertInvite = `-- name: UpsertInvite :one
INSERT INTO invites (id, workspace_id, email, role, locale, invited_by, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (workspace_id, email) DO UPDATE SET
    role = excluded.role,
    locale = excluded.locale,
    invited_by = excluded.invited_by,
    created_at = excluded.created_at,
    expires_at = excluded.expires_at
RETURNING id, workspace_id, email, role, locale, invited_by, created_at, expires_at
`

type UpsertInviteParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Email       string
	Role        string
	Locale      string
	InvitedBy   *uuid.UUID
	CreatedAt   time.Time
	ExpiresAt   time.Time
}

func (q *Queries) UpsertInvite(ctx context.Context, arg UpsertInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, upsertInvite,
		arg.ID,
		arg.WorkspaceID,
		arg.Email,
		arg.Role,
		arg.Locale,
		arg.InvitedBy,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.Locale,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
