// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: labels.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const countLabels = `-- name: CountLabels :one
SELECT count(*) FROM labels WHERE workspace_id = $1 AND id = ANY($2::uuid[])
`

type CountLabelsParams struct {
	WorkspaceID uuid.UUID
	Ids         []uuid.UUID
}

func (q *Queries) CountLabels(ctx context.Context, arg CountLabelsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLabels, arg.WorkspaceID, arg.Ids)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLabel = `-- name: CreateLabel :one
INSERT INTO labels (id, workspace_id, name, color, created_at) VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, name, color, created_at
`

type CreateLabelParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Color       string
	Now         time.Time
}

func (q *Queries) CreateLabel(ctx context.Context, arg CreateLabelParams) (Label, error) {
	row := q.db.QueryRow(ctx, createLabel,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Color,
		arg.Now,
	)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLabel = `-- name: DeleteLabel :execrows
DELETE FROM labels WHERE workspace_id = $1 AND id = $2
`

type DeleteLabelParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) DeleteLabel(ctx context.Context, arg DeleteLabelParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLabel, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLabel = `-- name: GetLabel :one
SELECT id, workspace_id, name, color, created_at FROM labels WHERE workspace_id = $1 AND id = $2
`

type GetLabelParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetLabel(ctx context.Context, arg GetLabelParams) (Label, error) {
	row := q.db.QueryRow(ctx, getLabel, arg.WorkspaceID, arg.ID)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const listLabels = `-- name: ListLabels :many
SELECT id, workspace_id, name, color, created_at FROM labels WHERE workspace_id = $1 ORDER BY name, id
`

func (q *Queries) ListLabels(ctx context.Context, workspaceID uuid.UUID) ([]Label, error) {
	rows, err := q.db.Query(ctx, listLabels, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLabel = `-- name: UpdateLabel :one
UPDATE labels SET name = $1, color = $2 WHERE workspace_id = $3 AND id = $4
RETURNING id, workspace_id, name, color, created_at
`

type UpdateLabelParams struct {
	Name        string
	Color       string
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) UpdateLabel(ctx context.Context, arg UpdateLabelParams) (Label, error) {
	row := q.db.QueryRow(ctx, updateLabel,
		arg.Name,
		arg.Color,
		arg.WorkspaceID,
		arg.ID,
	)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}
