// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login_codes.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const addLoginCodeAttempt = `-- name: AddLoginCodeAttempt :one
UPDATE login_codes SET attempts = attempts + 1 WHERE id = $1 RETURNING attempts
`

func (q *Queries) AddLoginCodeAttempt(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, addLoginCodeAttempt, id)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const consumeLoginCode = `-- name: ConsumeLoginCode :exec
UPDATE login_codes SET consumed_at = $2 WHERE id = $1
`

type ConsumeLoginCodeParams struct {
	ID         uuid.UUID
	ConsumedAt *time.Time
}

func (q *Queries) ConsumeLoginCode(ctx context.Context, arg ConsumeLoginCodeParams) error {
	_, err := q.db.Exec(ctx, consumeLoginCode, arg.ID, arg.ConsumedAt)
	return err
}

const countLoginCodesByEmail = `-- name: CountLoginCodesByEmail :one
SELECT count(*) FROM login_codes WHERE email = $1 AND created_at > $2
`

type CountLoginCodesByEmailParams struct {
	Email     string
	CreatedAt time.Time
}

func (q *Queries) CountLoginCodesByEmail(ctx context.Context, arg CountLoginCodesByEmailParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLoginCodesByEmail, arg.Email, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLoginCodesByIP = `-- name: CountLoginCodesByIP :one
SELECT count(*) FROM login_codes WHERE ip = $1 AND created_at > $2
`

type CountLoginCodesByIPParams struct {
	Ip        string
	CreatedAt time.Time
}

func (q *Queries) CountLoginCodesByIP(ctx context.Context, arg CountLoginCodesByIPParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLoginCodesByIP, arg.Ip, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLoginCode = `-- name: CreateLoginCode :exec
INSERT INTO login_codes (id, email, code_hash, ip, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateLoginCodeParams struct {
	ID        uuid.UUID
	Email     string
	CodeHash  []byte
	Ip        string
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) CreateLoginCode(ctx context.Context, arg CreateLoginCodeParams) error {
	_, err := q.db.Exec(ctx, createLoginCode,
		arg.ID,
		arg.Email,
		arg.CodeHash,
		arg.Ip,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const latestLoginCode = `-- name: LatestLoginCode :one
SELECT id, email, code_hash, ip, attempts, created_at, expires_at, consumed_at FROM login_codes WHERE email = $1 AND consumed_at IS NULL
ORDER BY created_at DESC LIMIT 1
FOR UPDATE
`

func (q *Queries) LatestLoginCode(ctx context.Context, email string) (LoginCode, error) {
	row := q.db.QueryRow(ctx, latestLoginCode, email)
	var i LoginCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.Ip,
		&i.Attempts,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}
