// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const countOwners = `-- name: CountOwners :one
SELECT count(*) FROM members WHERE workspace_id = $1 AND role = 'owner'
`

func (q *Queries) CountOwners(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOwners, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMember = `-- name: CreateMember :one
INSERT INTO members (id, workspace_id, person_id, role) VALUES ($1, $2, $3, $4)
ON CONFLICT (workspace_id, person_id) DO NOTHING
RETURNING id, workspace_id, person_id, role, created_at, notification_events, notification_email_delay
`

type CreateMemberParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	PersonID    uuid.UUID
	Role        string
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.ID,
		arg.WorkspaceID,
		arg.PersonID,
		arg.Role,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PersonID,
		&i.Role,
		&i.CreatedAt,
		&i.NotificationEvents,
		&i.NotificationEmailDelay,
	)
	return i, err
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM members WHERE workspace_id = $1 AND id = $2
`

type DeleteMemberParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) DeleteMember(ctx context.Context, arg DeleteMemberParams) error {
	_, err := q.db.Exec(ctx, deleteMember, arg.WorkspaceID, arg.ID)
	return err
}

const getMember = `-- name: GetMember :one
SELECT m.id, m.workspace_id, m.person_id, m.role, m.created_at, p.email, p.name
FROM members m JOIN people p ON p.id = m.person_id
WHERE m.workspace_id = $1 AND m.id = $2
`

type GetMemberParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

type GetMemberRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	PersonID    uuid.UUID
	Role        string
	CreatedAt   time.Time
	Email       string
	Name        string
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (GetMemberRow, error) {
	row := q.db.QueryRow(ctx, getMember, arg.WorkspaceID, arg.ID)
	var i GetMemberRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PersonID,
		&i.Role,
		&i.CreatedAt,
		&i.Email,
		&i.Name,
	)
	return i, err
}

const getMemberByPerson = `-- name: GetMemberByPerson :one
SELECT m.id, m.workspace_id, m.person_id, m.role, m.created_at, m.notification_events, m.notification_email_delay FROM members m JOIN workspaces w ON w.id = m.workspace_id
WHERE m.workspace_id = $1 AND m.person_id = $2 AND w.deleted_at IS NULL
`

type GetMemberByPersonParams struct {
	WorkspaceID uuid.UUID
	PersonID    uuid.UUID
}

func (q *Queries) GetMemberByPerson(ctx context.Context, arg GetMemberByPersonParams) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberByPerson, arg.WorkspaceID, arg.PersonID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PersonID,
		&i.Role,
		&i.CreatedAt,
		&i.NotificationEvents,
		&i.NotificationEmailDelay,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT m.id, m.workspace_id, m.person_id, m.role, m.created_at, p.email, p.name
FROM members m JOIN people p ON p.id = m.person_id
WHERE m.workspace_id = $1
ORDER BY m.created_at, m.id
`

type ListMembersRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	PersonID    uuid.UUID
	Role        string
	CreatedAt   time.Time
	Email       string
	Name        string
}

func (q *Queries) ListMembers(ctx context.Context, workspaceID uuid.UUID) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersRow
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.PersonID,
			&i.Role,
			&i.CreatedAt,
			&i.Email,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberships = `-- name: ListMemberships :many
SELECT m.id AS member_id, m.role, w.id AS workspace_id, w.name AS workspace_name, w.created_at AS workspace_created_at,
       w.retention_days AS workspace_retention_days, w.bots_may_send AS workspace_bots_may_send
FROM members m JOIN workspaces w ON w.id = m.workspace_id
WHERE m.person_id = $1 AND w.deleted_at IS NULL
ORDER BY m.created_at, m.id
`

type ListMembershipsRow struct {
	MemberID               uuid.UUID
	Role                   string
	WorkspaceID            uuid.UUID
	WorkspaceName          string
	WorkspaceCreatedAt     time.Time
	WorkspaceRetentionDays *int32
	WorkspaceBotsMaySend   bool
}

func (q *Queries) ListMemberships(ctx context.Context, personID uuid.UUID) ([]ListMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listMemberships, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembershipsRow
	for rows.Next() {
		var i ListMembershipsRow
		if err := rows.Scan(
			&i.MemberID,
			&i.Role,
			&i.WorkspaceID,
			&i.WorkspaceName,
			&i.WorkspaceCreatedAt,
			&i.WorkspaceRetentionDays,
			&i.WorkspaceBotsMaySend,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const memberExistsByEmail = `-- name: MemberExistsByEmail :one
SELECT EXISTS (
    SELECT 1 FROM members m JOIN people p ON p.id = m.person_id
    WHERE m.workspace_id = $1 AND p.email = $2
) AS member
`

type MemberExistsByEmailParams struct {
	WorkspaceID uuid.UUID
	Email       string
}

func (q *Queries) MemberExistsByEmail(ctx context.Context, arg MemberExistsByEmailParams) (bool, error) {
	row := q.db.QueryRow(ctx, memberExistsByEmail, arg.WorkspaceID, arg.Email)
	var member bool
	err := row.Scan(&member)
	return member, err
}

const updateMemberRole = `-- name: UpdateMemberRole :exec
UPDATE members SET role = $3 WHERE workspace_id = $1 AND id = $2
`

type UpdateMemberRoleParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
	Role        string
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateMemberRole, arg.WorkspaceID, arg.ID, arg.Role)
	return err
}
