// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (id, workspace_id, conversation_id, message_id, storage_key, filename,
                         content_type, size_bytes, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9)
RETURNING id, workspace_id, conversation_id, message_id, storage_key, filename, content_type, size_bytes, created_at
`

type CreateAttachmentParams struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	ConversationID uuid.UUID
	MessageID      uuid.UUID
	StorageKey     string
	Filename       string
	ContentType    string
	SizeBytes      int64
	CreatedAt      time.Time
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.ID,
		arg.WorkspaceID,
		arg.ConversationID,
		arg.MessageID,
		arg.StorageKey,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
		arg.CreatedAt,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ConversationID,
		&i.MessageID,
		&i.StorageKey,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (id, workspace_id, conversation_id, kind, direction, author_type, author_member_id,
                      author_contact_id, body, html, client_id, event, created_at, delivery_state, delivery_updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11, $12, $13, $14,
        CASE WHEN $14::text IS NULL THEN NULL ELSE $13::timestamptz END)
ON CONFLICT (workspace_id, conversation_id, client_id) DO NOTHING
RETURNING id, workspace_id, conversation_id, kind, direction, author_type, author_member_id,
          author_contact_id, body, html, client_id, event, created_at, delivery_state, delivery_error, delivery_updated_at
`

type CreateMessageParams struct {
	ID              uuid.UUID
	WorkspaceID     uuid.UUID
	ConversationID  uuid.UUID
	Kind            string
	Direction       *string
	AuthorType      string
	AuthorMemberID  *uuid.UUID
	AuthorContactID *uuid.UUID
	Body            string
	Html            *string
	ClientID        *string
	Event           []byte
	CreatedAt       time.Time
	DeliveryState   *string
}

type CreateMessageRow struct {
	ID                uuid.UUID
	WorkspaceID       uuid.UUID
	ConversationID    uuid.UUID
	Kind              string
	Direction         *string
	AuthorType        string
	AuthorMemberID    *uuid.UUID
	AuthorContactID   *uuid.UUID
	Body              string
	Html              *string
	ClientID          *string
	Event             []byte
	CreatedAt         time.Time
	DeliveryState     *string
	DeliveryError     *string
	DeliveryUpdatedAt *time.Time
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (CreateMessageRow, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.WorkspaceID,
		arg.ConversationID,
		arg.Kind,
		arg.Direction,
		arg.AuthorType,
		arg.AuthorMemberID,
		arg.AuthorContactID,
		arg.Body,
		arg.Html,
		arg.ClientID,
		arg.Event,
		arg.CreatedAt,
		arg.DeliveryState,
	)
	var i CreateMessageRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ConversationID,
		&i.Kind,
		&i.Direction,
		&i.AuthorType,
		&i.AuthorMemberID,
		&i.AuthorContactID,
		&i.Body,
		&i.Html,
		&i.ClientID,
		&i.Event,
		&i.CreatedAt,
		&i.DeliveryState,
		&i.DeliveryError,
		&i.DeliveryUpdatedAt,
	)
	return i, err
}

const getAttachment = `-- name: GetAttachment :one
SELECT a.id, a.workspace_id, a.conversation_id, a.message_id, a.storage_key, a.filename, a.content_type, a.size_bytes, a.created_at, c.inbox_id FROM attachments a
JOIN conversations c ON c.workspace_id = a.workspace_id AND c.id = a.conversation_id
WHERE a.workspace_id = $1 AND a.id = $2
`

type GetAttachmentParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

type GetAttachmentRow struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	ConversationID uuid.UUID
	MessageID      uuid.UUID
	StorageKey     string
	Filename       string
	ContentType    string
	SizeBytes      int64
	CreatedAt      time.Time
	InboxID        uuid.UUID
}

func (q *Queries) GetAttachment(ctx context.Context, arg GetAttachmentParams) (GetAttachmentRow, error) {
	row := q.db.QueryRow(ctx, getAttachment, arg.WorkspaceID, arg.ID)
	var i GetAttachmentRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ConversationID,
		&i.MessageID,
		&i.StorageKey,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.InboxID,
	)
	return i, err
}

const getLatestMessagePosition = `-- name: GetLatestMessagePosition :one
SELECT id, created_at FROM messages WHERE workspace_id = $1 AND conversation_id = $2
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type GetLatestMessagePositionParams struct {
	WorkspaceID    uuid.UUID
	ConversationID uuid.UUID
}

type GetLatestMessagePositionRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) GetLatestMessagePosition(ctx context.Context, arg GetLatestMessagePositionParams) (GetLatestMessagePositionRow, error) {
	row := q.db.QueryRow(ctx, getLatestMessagePosition, arg.WorkspaceID, arg.ConversationID)
	var i GetLatestMessagePositionRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT m.id, m.workspace_id, m.conversation_id, m.kind, m.direction, m.author_type, m.author_member_id,
       m.author_contact_id, m.body, m.html, m.client_id, m.event, m.created_at, m.delivery_state, m.delivery_error,
       m.delivery_updated_at
FROM messages m WHERE m.workspace_id = $1 AND m.id = $2
`

type GetMessageParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

type GetMessageRow struct {
	ID                uuid.UUID
	WorkspaceID       uuid.UUID
	ConversationID    uuid.UUID
	Kind              string
	Direction         *string
	AuthorType        string
	AuthorMemberID    *uuid.UUID
	AuthorContactID   *uuid.UUID
	Body              string
	Html              *string
	ClientID          *string
	Event             []byte
	CreatedAt         time.Time
	DeliveryState     *string
	DeliveryError     *string
	DeliveryUpdatedAt *time.Time
}

func (q *Queries) GetMessage(ctx context.Context, arg GetMessageParams) (GetMessageRow, error) {
	row := q.db.QueryRow(ctx, getMessage, arg.WorkspaceID, arg.ID)
	var i GetMessageRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ConversationID,
		&i.Kind,
		&i.Direction,
		&i.AuthorType,
		&i.AuthorMemberID,
		&i.AuthorContactID,
		&i.Body,
		&i.Html,
		&i.ClientID,
		&i.Event,
		&i.CreatedAt,
		&i.DeliveryState,
		&i.DeliveryError,
		&i.DeliveryUpdatedAt,
	)
	return i, err
}

const getMessageByClientID = `-- name: GetMessageByClientID :one
SELECT id, workspace_id, conversation_id, kind, direction, author_type, author_member_id,
       author_contact_id, body, html, client_id, event, created_at, delivery_state, delivery_error, delivery_updated_at
FROM messages WHERE workspace_id = $1 AND conversation_id = $2 AND client_id = $3
`

type GetMessageByClientIDParams struct {
	WorkspaceID    uuid.UUID
	ConversationID uuid.UUID
	ClientID       *string
}

type GetMessageByClientIDRow struct {
	ID                uuid.UUID
	WorkspaceID       uuid.UUID
	ConversationID    uuid.UUID
	Kind              string
	Direction         *string
	AuthorType        string
	AuthorMemberID    *uuid.UUID
	AuthorContactID   *uuid.UUID
	Body              string
	Html              *string
	ClientID          *string
	Event             []byte
	CreatedAt         time.Time
	DeliveryState     *string
	DeliveryError     *string
	DeliveryUpdatedAt *time.Time
}

func (q *Queries) GetMessageByClientID(ctx context.Context, arg GetMessageByClientIDParams) (GetMessageByClientIDRow, error) {
	row := q.db.QueryRow(ctx, getMessageByClientID, arg.WorkspaceID, arg.ConversationID, arg.ClientID)
	var i GetMessageByClientIDRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ConversationID,
		&i.Kind,
		&i.Direction,
		&i.AuthorType,
		&i.AuthorMemberID,
		&i.AuthorContactID,
		&i.Body,
		&i.Html,
		&i.ClientID,
		&i.Event,
		&i.CreatedAt,
		&i.DeliveryState,
		&i.DeliveryError,
		&i.DeliveryUpdatedAt,
	)
	return i, err
}

const getMessagePosition = `-- name: GetMessagePosition :one
SELECT id, created_at FROM messages WHERE workspace_id = $1 AND conversation_id = $2 AND id = $3
`

type GetMessagePositionParams struct {
	WorkspaceID    uuid.UUID
	ConversationID uuid.UUID
	ID             uuid.UUID
}

type GetMessagePositionRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) GetMessagePosition(ctx context.Context, arg GetMessagePositionParams) (GetMessagePositionRow, error) {
	row := q.db.QueryRow(ctx, getMessagePosition, arg.WorkspaceID, arg.ConversationID, arg.ID)
	var i GetMessagePositionRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listAttachments = `-- name: ListAttachments :many
SELECT id, workspace_id, conversation_id, message_id, storage_key, filename, content_type, size_bytes, created_at FROM attachments
WHERE workspace_id = $1 AND message_id = ANY($2::uuid[])
ORDER BY message_id, created_at, id
`

type ListAttachmentsParams struct {
	WorkspaceID uuid.UUID
	MessageIds  []uuid.UUID
}

func (q *Queries) ListAttachments(ctx context.Context, arg ListAttachmentsParams) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachments, arg.WorkspaceID, arg.MessageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ConversationID,
			&i.MessageID,
			&i.StorageKey,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachmentsOfMessage = `-- name: ListAttachmentsOfMessage :many
SELECT id, workspace_id, conversation_id, message_id, storage_key, filename, content_type, size_bytes, created_at FROM attachments WHERE workspace_id = $1 AND message_id = $2 ORDER BY created_at, id
`

type ListAttachmentsOfMessageParams struct {
	WorkspaceID uuid.UUID
	MessageID   uuid.UUID
}

func (q *Queries) ListAttachmentsOfMessage(ctx context.Context, arg ListAttachmentsOfMessageParams) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsOfMessage, arg.WorkspaceID, arg.MessageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ConversationID,
			&i.MessageID,
			&i.StorageKey,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, workspace_id, conversation_id, kind, direction, author_type, author_member_id,
       author_contact_id, body, html, client_id, event, created_at, delivery_state, delivery_error, delivery_updated_at
FROM messages m
WHERE m.workspace_id = $1 AND m.conversation_id = $2
  AND ($3::timestamptz IS NULL
       OR (m.created_at, m.id) > ($3::timestamptz, $4::uuid))
ORDER BY m.created_at, m.id
LIMIT $5
`

type ListMessagesParams struct {
	WorkspaceID    uuid.UUID
	ConversationID uuid.UUID
	CursorAt       *time.Time
	CursorID       *uuid.UUID
	Lim            int32
}

type ListMessagesRow struct {
	ID                uuid.UUID
	WorkspaceID       uuid.UUID
	ConversationID    uuid.UUID
	Kind              string
	Direction         *string
	AuthorType        string
	AuthorMemberID    *uuid.UUID
	AuthorContactID   *uuid.UUID
	Body              string
	Html              *string
	ClientID          *string
	Event             []byte
	CreatedAt         time.Time
	DeliveryState     *string
	DeliveryError     *string
	DeliveryUpdatedAt *time.Time
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error) {
	rows, err := q.db.Query(ctx, listMessages,
		arg.WorkspaceID,
		arg.ConversationID,
		arg.CursorAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesRow
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ConversationID,
			&i.Kind,
			&i.Direction,
			&i.AuthorType,
			&i.AuthorMemberID,
			&i.AuthorContactID,
			&i.Body,
			&i.Html,
			&i.ClientID,
			&i.Event,
			&i.CreatedAt,
			&i.DeliveryState,
			&i.DeliveryError,
			&i.DeliveryUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesDesc = `-- name: ListMessagesDesc :many
SELECT id, workspace_id, conversation_id, kind, direction, author_type, author_member_id,
       author_contact_id, body, html, client_id, event, created_at, delivery_state, delivery_error, delivery_updated_at
FROM messages m
WHERE m.workspace_id = $1 AND m.conversation_id = $2
  AND ($3::timestamptz IS NULL
       OR (m.created_at, m.id) < ($3::timestamptz, $4::uuid))
ORDER BY m.created_at DESC, m.id DESC
LIMIT $5
`

type ListMessagesDescParams struct {
	WorkspaceID    uuid.UUID
	ConversationID uuid.UUID
	CursorAt       *time.Time
	CursorID       *uuid.UUID
	Lim            int32
}

type ListMessagesDescRow struct {
	ID                uuid.UUID
	WorkspaceID       uuid.UUID
	ConversationID    uuid.UUID
	Kind              string
	Direction         *string
	AuthorType        string
	AuthorMemberID    *uuid.UUID
	AuthorContactID   *uuid.UUID
	Body              string
	Html              *string
	ClientID          *string
	Event             []byte
	CreatedAt         time.Time
	DeliveryState     *string
	DeliveryError     *string
	DeliveryUpdatedAt *time.Time
}

func (q *Queries) ListMessagesDesc(ctx context.Context, arg ListMessagesDescParams) ([]ListMessagesDescRow, error) {
	rows, err := q.db.Query(ctx, listMessagesDesc,
		arg.WorkspaceID,
		arg.ConversationID,
		arg.CursorAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesDescRow
	for rows.Next() {
		var i ListMessagesDescRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ConversationID,
			&i.Kind,
			&i.Direction,
			&i.AuthorType,
			&i.AuthorMemberID,
			&i.AuthorContactID,
			&i.Body,
			&i.Html,
			&i.ClientID,
			&i.Event,
			&i.CreatedAt,
			&i.DeliveryState,
			&i.DeliveryError,
			&i.DeliveryUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMessageDelivery = `-- name: SetMessageDelivery :one
UPDATE messages SET delivery_state = $1::text, delivery_error = $2, delivery_updated_at = $3::timestamptz
WHERE workspace_id = $4 AND id = $5
RETURNING id, workspace_id, conversation_id, kind, direction, author_type, author_member_id,
          author_contact_id, body, html, client_id, event, created_at, delivery_state, delivery_error, delivery_updated_at
`

type SetMessageDeliveryParams struct {
	State       string
	Error       *string
	Now         time.Time
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

type SetMessageDeliveryRow struct {
	ID                uuid.UUID
	WorkspaceID       uuid.UUID
	ConversationID    uuid.UUID
	Kind              string
	Direction         *string
	AuthorType        string
	AuthorMemberID    *uuid.UUID
	AuthorContactID   *uuid.UUID
	Body              string
	Html              *string
	ClientID          *string
	Event             []byte
	CreatedAt         time.Time
	DeliveryState     *string
	DeliveryError     *string
	DeliveryUpdatedAt *time.Time
}

func (q *Queries) SetMessageDelivery(ctx context.Context, arg SetMessageDeliveryParams) (SetMessageDeliveryRow, error) {
	row := q.db.QueryRow(ctx, setMessageDelivery,
		arg.State,
		arg.Error,
		arg.Now,
		arg.WorkspaceID,
		arg.ID,
	)
	var i SetMessageDeliveryRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ConversationID,
		&i.Kind,
		&i.Direction,
		&i.AuthorType,
		&i.AuthorMemberID,
		&i.AuthorContactID,
		&i.Body,
		&i.Html,
		&i.ClientID,
		&i.Event,
		&i.CreatedAt,
		&i.DeliveryState,
		&i.DeliveryError,
		&i.DeliveryUpdatedAt,
	)
	return i, err
}
