// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const callerDraftInConversation = `-- name: CallerDraftInConversation :one
SELECT id FROM messages
WHERE workspace_id = $1 AND conversation_id = $2 AND draft
  AND (author_api_key_id = $3
       OR (author_member_id = $4 AND via IS NOT DISTINCT FROM $5))
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type CallerDraftInConversationParams struct {
	WorkspaceID    uuid.UUID
	ConversationID uuid.UUID
	ApiKeyID       *uuid.UUID
	MemberID       *uuid.UUID
	Via            *string
}

func (q *Queries) CallerDraftInConversation(ctx context.Context, arg CallerDraftInConversationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, callerDraftInConversation,
		arg.WorkspaceID,
		arg.ConversationID,
		arg.ApiKeyID,
		arg.MemberID,
		arg.Via,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const countDrafts = `-- name: CountDrafts :one
SELECT count(*) FROM messages m
JOIN conversations c ON c.workspace_id = m.workspace_id AND c.id = m.conversation_id
WHERE m.workspace_id = $1 AND m.draft
  AND ($2::bool OR EXISTS (
      SELECT 1 FROM inbox_viewers iv
      WHERE iv.workspace_id = c.workspace_id AND iv.inbox_id = c.inbox_id AND iv.viewer_id = $3))
  AND ($4::uuid IS NULL OR c.inbox_id = $4::uuid)
  AND ($5::text IS NULL
       OR ($5::text = 'bot' AND m.author_type = 'bot')
       OR ($5::text = 'assistant' AND m.author_type = 'member' AND m.via IS NOT NULL)
       OR ($5::text = 'member' AND m.author_type = 'member' AND m.via IS NULL))
`

type CountDraftsParams struct {
	WorkspaceID uuid.UUID
	AllInboxes  bool
	ViewerID    uuid.UUID
	InboxID     *uuid.UUID
	AuthorKind  *string
}

func (q *Queries) CountDrafts(ctx context.Context, arg CountDraftsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDrafts,
		arg.WorkspaceID,
		arg.AllInboxes,
		arg.ViewerID,
		arg.InboxID,
		arg.AuthorKind,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnseenMentions = `-- name: CountUnseenMentions :one
SELECT count(*) FROM messages m
JOIN conversations c ON c.workspace_id = m.workspace_id AND c.id = m.conversation_id
LEFT JOIN conversation_reads r
       ON r.workspace_id = m.workspace_id AND r.conversation_id = m.conversation_id AND r.member_id = $1
WHERE m.workspace_id = $2 AND m.kind = 'note' AND NOT m.draft
  AND m.mentions @> ARRAY[$1::uuid]
  AND m.author_member_id IS DISTINCT FROM $1::uuid
  AND ($3::bool OR EXISTS (
      SELECT 1 FROM inbox_viewers iv
      WHERE iv.workspace_id = c.workspace_id AND iv.inbox_id = c.inbox_id AND iv.viewer_id = $1))
  AND (r.last_read_at IS NULL OR (r.last_read_at, r.last_read_message_id) < (m.created_at, m.id))
`

type CountUnseenMentionsParams struct {
	MemberID    uuid.UUID
	WorkspaceID uuid.UUID
	AllInboxes  bool
}

func (q *Queries) CountUnseenMentions(ctx context.Context, arg CountUnseenMentionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnseenMentions, arg.MemberID, arg.WorkspaceID, arg.AllInboxes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (id, workspace_id, conversation_id, message_id, storage_key, filename,
                         content_type, size_bytes, content_id, inline, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11)
RETURNING id, workspace_id, conversation_id, message_id, storage_key, filename, content_type, size_bytes, created_at, content_id, inline
`

type CreateAttachmentParams struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	ConversationID uuid.UUID
	MessageID      uuid.UUID
	StorageKey     string
	Filename       string
	ContentType    string
	SizeBytes      int64
	ContentID      *string
	Inline         bool
	CreatedAt      time.Time
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.ID,
		arg.WorkspaceID,
		arg.ConversationID,
		arg.MessageID,
		arg.StorageKey,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
		arg.ContentID,
		arg.Inline,
		arg.CreatedAt,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ConversationID,
		&i.MessageID,
		&i.StorageKey,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.ContentID,
		&i.Inline,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
WITH m AS (
    INSERT INTO messages (id, workspace_id, conversation_id, kind, direction, author_type, author_member_id,
                          author_contact_id, author_api_key_id, body, html, client_id, event, created_at, draft,
                          delivery_state, delivery_updated_at, via, mentions)
    VALUES ($1, $2, $3, $4, $5, $6, $7,
            $8, $9, $10, $11, $12, $13, $14, $15,
            $16,
            CASE WHEN $16::text IS NULL THEN NULL ELSE $14::timestamptz END,
            $17, coalesce($18::uuid[], '{}'))
    ON CONFLICT (workspace_id, conversation_id, client_id) DO NOTHING
    RETURNING id, workspace_id, conversation_id, kind, direction, author_type, author_member_id, author_contact_id, body, html, client_id, event, search, created_at, delivery_state, delivery_error, delivery_updated_at, author_api_key_id, draft, sent_by_member_id, sent_by_api_key_id, via, sent_via, mentions),
seen AS (
    UPDATE contacts SET last_active_at = greatest(coalesce(contacts.last_active_at, m.created_at), m.created_at)
    FROM m WHERE contacts.workspace_id = m.workspace_id AND contacts.id = m.author_contact_id)
SELECT m.id, m.workspace_id, m.conversation_id, m.kind, m.direction, m.author_type, m.author_member_id,
       m.author_contact_id, m.body, m.html, m.client_id, m.event, m.created_at, m.delivery_state, m.delivery_error,
       m.delivery_updated_at, m.author_api_key_id, m.draft, m.sent_by_member_id, m.sent_by_api_key_id, m.via, m.sent_via, m.mentions,
       coalesce(ak.bot_name, ak.name, '')::text AS bot_name, coalesce(ak.bot_avatar_url, '')::text AS bot_avatar_url,
       coalesce(sk.bot_name, sk.name, '')::text AS sent_by_bot_name
FROM m
LEFT JOIN api_keys ak ON ak.workspace_id = m.workspace_id AND ak.id = m.author_api_key_id
LEFT JOIN api_keys sk ON sk.workspace_id = m.workspace_id AND sk.id = m.sent_by_api_key_id
`

type CreateMessageParams struct {
	ID              uuid.UUID
	WorkspaceID     uuid.UUID
	ConversationID  uuid.UUID
	Kind            string
	Direction       *string
	AuthorType      string
	AuthorMemberID  *uuid.UUID
	AuthorContactID *uuid.UUID
	AuthorApiKeyID  *uuid.UUID
	Body            string
	Html            *string
	ClientID        *string
	Event           []byte
	CreatedAt       time.Time
	Draft           bool
	DeliveryState   *string
	Via             *string
	Mentions        []uuid.UUID
}

type CreateMessageRow struct {
	ID                uuid.UUID
	WorkspaceID       uuid.UUID
	ConversationID    uuid.UUID
	Kind              string
	Direction         *string
	AuthorType        string
	AuthorMemberID    *uuid.UUID
	AuthorContactID   *uuid.UUID
	Body              string
	Html              *string
	ClientID          *string
	Event             []byte
	CreatedAt         time.Time
	DeliveryState     *string
	DeliveryError     *string
	DeliveryUpdatedAt *time.Time
	AuthorApiKeyID    *uuid.UUID
	Draft             bool
	SentByMemberID    *uuid.UUID
	SentByApiKeyID    *uuid.UUID
	Via               *string
	SentVia           *string
	Mentions          []uuid.UUID
	BotName           string
	BotAvatarUrl      string
	SentByBotName     string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (CreateMessageRow, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.WorkspaceID,
		arg.ConversationID,
		arg.Kind,
		arg.Direction,
		arg.AuthorType,
		arg.AuthorMemberID,
		arg.AuthorContactID,
		arg.AuthorApiKeyID,
		arg.Body,
		arg.Html,
		arg.ClientID,
		arg.Event,
		arg.CreatedAt,
		arg.Draft,
		arg.DeliveryState,
		arg.Via,
		arg.Mentions,
	)
	var i CreateMessageRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ConversationID,
		&i.Kind,
		&i.Direction,
		&i.AuthorType,
		&i.AuthorMemberID,
		&i.AuthorContactID,
		&i.Body,
		&i.Html,
		&i.ClientID,
		&i.Event,
		&i.CreatedAt,
		&i.DeliveryState,
		&i.DeliveryError,
		&i.DeliveryUpdatedAt,
		&i.AuthorApiKeyID,
		&i.Draft,
		&i.SentByMemberID,
		&i.SentByApiKeyID,
		&i.Via,
		&i.SentVia,
		&i.Mentions,
		&i.BotName,
		&i.BotAvatarUrl,
		&i.SentByBotName,
	)
	return i, err
}

const deleteDraft = `-- name: DeleteDraft :execrows
DELETE FROM messages WHERE workspace_id = $1 AND id = $2 AND draft
`

type DeleteDraftParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) DeleteDraft(ctx context.Context, arg DeleteDraftParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDraft, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAttachment = `-- name: GetAttachment :one
SELECT a.id, a.workspace_id, a.conversation_id, a.message_id, a.storage_key, a.filename, a.content_type, a.size_bytes, a.created_at, a.content_id, a.inline, c.inbox_id FROM attachments a
JOIN conversations c ON c.workspace_id = a.workspace_id AND c.id = a.conversation_id
WHERE a.workspace_id = $1 AND a.id = $2
`

type GetAttachmentParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

type GetAttachmentRow struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	ConversationID uuid.UUID
	MessageID      uuid.UUID
	StorageKey     string
	Filename       string
	ContentType    string
	SizeBytes      int64
	CreatedAt      time.Time
	ContentID      *string
	Inline         bool
	InboxID        uuid.UUID
}

func (q *Queries) GetAttachment(ctx context.Context, arg GetAttachmentParams) (GetAttachmentRow, error) {
	row := q.db.QueryRow(ctx, getAttachment, arg.WorkspaceID, arg.ID)
	var i GetAttachmentRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ConversationID,
		&i.MessageID,
		&i.StorageKey,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.ContentID,
		&i.Inline,
		&i.InboxID,
	)
	return i, err
}

const getLatestMessagePosition = `-- name: GetLatestMessagePosition :one
SELECT id, created_at FROM messages WHERE workspace_id = $1 AND conversation_id = $2
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type GetLatestMessagePositionParams struct {
	WorkspaceID    uuid.UUID
	ConversationID uuid.UUID
}

type GetLatestMessagePositionRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) GetLatestMessagePosition(ctx context.Context, arg GetLatestMessagePositionParams) (GetLatestMessagePositionRow, error) {
	row := q.db.QueryRow(ctx, getLatestMessagePosition, arg.WorkspaceID, arg.ConversationID)
	var i GetLatestMessagePositionRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT m.id, m.workspace_id, m.conversation_id, m.kind, m.direction, m.author_type, m.author_member_id,
       m.author_contact_id, m.body, m.html, m.client_id, m.event, m.created_at, m.delivery_state, m.delivery_error,
       m.delivery_updated_at, m.author_api_key_id, m.draft, m.sent_by_member_id, m.sent_by_api_key_id, m.via, m.sent_via, m.mentions,
       coalesce(ak.bot_name, ak.name, '')::text AS bot_name, coalesce(ak.bot_avatar_url, '')::text AS bot_avatar_url,
       coalesce(sk.bot_name, sk.name, '')::text AS sent_by_bot_name
FROM messages m
LEFT JOIN api_keys ak ON ak.workspace_id = m.workspace_id AND ak.id = m.author_api_key_id
LEFT JOIN api_keys sk ON sk.workspace_id = m.workspace_id AND sk.id = m.sent_by_api_key_id
WHERE m.workspace_id = $1 AND m.id = $2
`

type GetMessageParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

type GetMessageRow struct {
	ID                uuid.UUID
	WorkspaceID       uuid.UUID
	ConversationID    uuid.UUID
	Kind              string
	Direction         *string
	AuthorType        string
	AuthorMemberID    *uuid.UUID
	AuthorContactID   *uuid.UUID
	Body              string
	Html              *string
	ClientID          *string
	Event             []byte
	CreatedAt         time.Time
	DeliveryState     *string
	DeliveryError     *string
	DeliveryUpdatedAt *time.Time
	AuthorApiKeyID    *uuid.UUID
	Draft             bool
	SentByMemberID    *uuid.UUID
	SentByApiKeyID    *uuid.UUID
	Via               *string
	SentVia           *string
	Mentions          []uuid.UUID
	BotName           string
	BotAvatarUrl      string
	SentByBotName     string
}

func (q *Queries) GetMessage(ctx context.Context, arg GetMessageParams) (GetMessageRow, error) {
	row := q.db.QueryRow(ctx, getMessage, arg.WorkspaceID, arg.ID)
	var i GetMessageRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ConversationID,
		&i.Kind,
		&i.Direction,
		&i.AuthorType,
		&i.AuthorMemberID,
		&i.AuthorContactID,
		&i.Body,
		&i.Html,
		&i.ClientID,
		&i.Event,
		&i.CreatedAt,
		&i.DeliveryState,
		&i.DeliveryError,
		&i.DeliveryUpdatedAt,
		&i.AuthorApiKeyID,
		&i.Draft,
		&i.SentByMemberID,
		&i.SentByApiKeyID,
		&i.Via,
		&i.SentVia,
		&i.Mentions,
		&i.BotName,
		&i.BotAvatarUrl,
		&i.SentByBotName,
	)
	return i, err
}

const getMessageByClientID = `-- name: GetMessageByClientID :one
SELECT m.id, m.workspace_id, m.conversation_id, m.kind, m.direction, m.author_type, m.author_member_id,
       m.author_contact_id, m.body, m.html, m.client_id, m.event, m.created_at, m.delivery_state, m.delivery_error,
       m.delivery_updated_at, m.author_api_key_id, m.draft, m.sent_by_member_id, m.sent_by_api_key_id, m.via, m.sent_via, m.mentions,
       coalesce(ak.bot_name, ak.name, '')::text AS bot_name, coalesce(ak.bot_avatar_url, '')::text AS bot_avatar_url,
       coalesce(sk.bot_name, sk.name, '')::text AS sent_by_bot_name
FROM messages m
LEFT JOIN api_keys ak ON ak.workspace_id = m.workspace_id AND ak.id = m.author_api_key_id
LEFT JOIN api_keys sk ON sk.workspace_id = m.workspace_id AND sk.id = m.sent_by_api_key_id
WHERE m.workspace_id = $1 AND m.conversation_id = $2 AND m.client_id = $3
`

type GetMessageByClientIDParams struct {
	WorkspaceID    uuid.UUID
	ConversationID uuid.UUID
	ClientID       *string
}

type GetMessageByClientIDRow struct {
	ID                uuid.UUID
	WorkspaceID       uuid.UUID
	ConversationID    uuid.UUID
	Kind              string
	Direction         *string
	AuthorType        string
	AuthorMemberID    *uuid.UUID
	AuthorContactID   *uuid.UUID
	Body              string
	Html              *string
	ClientID          *string
	Event             []byte
	CreatedAt         time.Time
	DeliveryState     *string
	DeliveryError     *string
	DeliveryUpdatedAt *time.Time
	AuthorApiKeyID    *uuid.UUID
	Draft             bool
	SentByMemberID    *uuid.UUID
	SentByApiKeyID    *uuid.UUID
	Via               *string
	SentVia           *string
	Mentions          []uuid.UUID
	BotName           string
	BotAvatarUrl      string
	SentByBotName     string
}

func (q *Queries) GetMessageByClientID(ctx context.Context, arg GetMessageByClientIDParams) (GetMessageByClientIDRow, error) {
	row := q.db.QueryRow(ctx, getMessageByClientID, arg.WorkspaceID, arg.ConversationID, arg.ClientID)
	var i GetMessageByClientIDRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ConversationID,
		&i.Kind,
		&i.Direction,
		&i.AuthorType,
		&i.AuthorMemberID,
		&i.AuthorContactID,
		&i.Body,
		&i.Html,
		&i.ClientID,
		&i.Event,
		&i.CreatedAt,
		&i.DeliveryState,
		&i.DeliveryError,
		&i.DeliveryUpdatedAt,
		&i.AuthorApiKeyID,
		&i.Draft,
		&i.SentByMemberID,
		&i.SentByApiKeyID,
		&i.Via,
		&i.SentVia,
		&i.Mentions,
		&i.BotName,
		&i.BotAvatarUrl,
		&i.SentByBotName,
	)
	return i, err
}

const getMessagePosition = `-- name: GetMessagePosition :one
SELECT id, created_at FROM messages WHERE workspace_id = $1 AND conversation_id = $2 AND id = $3
`

type GetMessagePositionParams struct {
	WorkspaceID    uuid.UUID
	ConversationID uuid.UUID
	ID             uuid.UUID
}

type GetMessagePositionRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) GetMessagePosition(ctx context.Context, arg GetMessagePositionParams) (GetMessagePositionRow, error) {
	row := q.db.QueryRow(ctx, getMessagePosition, arg.WorkspaceID, arg.ConversationID, arg.ID)
	var i GetMessagePositionRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listAttachments = `-- name: ListAttachments :many
SELECT id, workspace_id, conversation_id, message_id, storage_key, filename, content_type, size_bytes, created_at, content_id, inline FROM attachments
WHERE workspace_id = $1 AND message_id = ANY($2::uuid[])
ORDER BY message_id, created_at, id
`

type ListAttachmentsParams struct {
	WorkspaceID uuid.UUID
	MessageIds  []uuid.UUID
}

func (q *Queries) ListAttachments(ctx context.Context, arg ListAttachmentsParams) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachments, arg.WorkspaceID, arg.MessageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ConversationID,
			&i.MessageID,
			&i.StorageKey,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.ContentID,
			&i.Inline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachmentsOfMessage = `-- name: ListAttachmentsOfMessage :many
SELECT id, workspace_id, conversation_id, message_id, storage_key, filename, content_type, size_bytes, created_at, content_id, inline FROM attachments WHERE workspace_id = $1 AND message_id = $2 ORDER BY created_at, id
`

type ListAttachmentsOfMessageParams struct {
	WorkspaceID uuid.UUID
	MessageID   uuid.UUID
}

func (q *Queries) ListAttachmentsOfMessage(ctx context.Context, arg ListAttachmentsOfMessageParams) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsOfMessage, arg.WorkspaceID, arg.MessageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ConversationID,
			&i.MessageID,
			&i.StorageKey,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.ContentID,
			&i.Inline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationSummaries = `-- name: ListConversationSummaries :many
SELECT id, inbox_id, subject, status, contact_id FROM conversations
WHERE workspace_id = $1 AND id = ANY($2::uuid[])
`

type ListConversationSummariesParams struct {
	WorkspaceID uuid.UUID
	Ids         []uuid.UUID
}

type ListConversationSummariesRow struct {
	ID        uuid.UUID
	InboxID   uuid.UUID
	Subject   string
	Status    string
	ContactID uuid.UUID
}

func (q *Queries) ListConversationSummaries(ctx context.Context, arg ListConversationSummariesParams) ([]ListConversationSummariesRow, error) {
	rows, err := q.db.Query(ctx, listConversationSummaries, arg.WorkspaceID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationSummariesRow
	for rows.Next() {
		var i ListConversationSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.InboxID,
			&i.Subject,
			&i.Status,
			&i.ContactID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDrafts = `-- name: ListDrafts :many
SELECT m.id, m.workspace_id, m.conversation_id, m.kind, m.direction, m.author_type, m.author_member_id,
       m.author_contact_id, m.body, m.html, m.client_id, m.event, m.created_at, m.delivery_state, m.delivery_error,
       m.delivery_updated_at, m.author_api_key_id, m.draft, m.sent_by_member_id, m.sent_by_api_key_id, m.via, m.sent_via, m.mentions,
       coalesce(ak.bot_name, ak.name, '')::text AS bot_name, coalesce(ak.bot_avatar_url, '')::text AS bot_avatar_url,
       coalesce(sk.bot_name, sk.name, '')::text AS sent_by_bot_name
FROM messages m
JOIN conversations c ON c.workspace_id = m.workspace_id AND c.id = m.conversation_id
LEFT JOIN api_keys ak ON ak.workspace_id = m.workspace_id AND ak.id = m.author_api_key_id
LEFT JOIN api_keys sk ON sk.workspace_id = m.workspace_id AND sk.id = m.sent_by_api_key_id
WHERE m.workspace_id = $1 AND m.draft
  AND ($2::bool OR EXISTS (
      SELECT 1 FROM inbox_viewers iv
      WHERE iv.workspace_id = c.workspace_id AND iv.inbox_id = c.inbox_id AND iv.viewer_id = $3))
  AND ($4::uuid IS NULL OR c.inbox_id = $4::uuid)
  AND ($5::text IS NULL
       OR ($5::text = 'bot' AND m.author_type = 'bot')
       OR ($5::text = 'assistant' AND m.author_type = 'member' AND m.via IS NOT NULL)
       OR ($5::text = 'member' AND m.author_type = 'member' AND m.via IS NULL))
  AND ($6::timestamptz IS NULL
       OR (m.created_at, m.id) < ($6::timestamptz, $7::uuid))
ORDER BY m.created_at DESC, m.id DESC
LIMIT $8
`

type ListDraftsParams struct {
	WorkspaceID uuid.UUID
	AllInboxes  bool
	ViewerID    uuid.UUID
	InboxID     *uuid.UUID
	AuthorKind  *string
	CursorAt    *time.Time
	CursorID    *uuid.UUID
	Lim         int32
}

type ListDraftsRow struct {
	ID                uuid.UUID
	WorkspaceID       uuid.UUID
	ConversationID    uuid.UUID
	Kind              string
	Direction         *string
	AuthorType        string
	AuthorMemberID    *uuid.UUID
	AuthorContactID   *uuid.UUID
	Body              string
	Html              *string
	ClientID          *string
	Event             []byte
	CreatedAt         time.Time
	DeliveryState     *string
	DeliveryError     *string
	DeliveryUpdatedAt *time.Time
	AuthorApiKeyID    *uuid.UUID
	Draft             bool
	SentByMemberID    *uuid.UUID
	SentByApiKeyID    *uuid.UUID
	Via               *string
	SentVia           *string
	Mentions          []uuid.UUID
	BotName           string
	BotAvatarUrl      string
	SentByBotName     string
}

func (q *Queries) ListDrafts(ctx context.Context, arg ListDraftsParams) ([]ListDraftsRow, error) {
	rows, err := q.db.Query(ctx, listDrafts,
		arg.WorkspaceID,
		arg.AllInboxes,
		arg.ViewerID,
		arg.InboxID,
		arg.AuthorKind,
		arg.CursorAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDraftsRow
	for rows.Next() {
		var i ListDraftsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ConversationID,
			&i.Kind,
			&i.Direction,
			&i.AuthorType,
			&i.AuthorMemberID,
			&i.AuthorContactID,
			&i.Body,
			&i.Html,
			&i.ClientID,
			&i.Event,
			&i.CreatedAt,
			&i.DeliveryState,
			&i.DeliveryError,
			&i.DeliveryUpdatedAt,
			&i.AuthorApiKeyID,
			&i.Draft,
			&i.SentByMemberID,
			&i.SentByApiKeyID,
			&i.Via,
			&i.SentVia,
			&i.Mentions,
			&i.BotName,
			&i.BotAvatarUrl,
			&i.SentByBotName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMentions = `-- name: ListMentions :many
SELECT m.id, m.conversation_id, m.author_type, m.author_member_id, m.author_api_key_id, m.via,
       left(m.body, 1000)::text AS body, m.created_at,
       coalesce(ak.bot_name, ak.name, '')::text AS bot_name, coalesce(ak.bot_avatar_url, '')::text AS bot_avatar_url,
       (r.last_read_at IS NOT NULL AND (r.last_read_at, r.last_read_message_id) >= (m.created_at, m.id))::bool AS seen
FROM messages m
JOIN conversations c ON c.workspace_id = m.workspace_id AND c.id = m.conversation_id
LEFT JOIN conversation_reads r
       ON r.workspace_id = m.workspace_id AND r.conversation_id = m.conversation_id AND r.member_id = $1
LEFT JOIN api_keys ak ON ak.workspace_id = m.workspace_id AND ak.id = m.author_api_key_id
WHERE m.workspace_id = $2 AND m.kind = 'note' AND NOT m.draft
  AND m.mentions @> ARRAY[$1::uuid]
  AND m.author_member_id IS DISTINCT FROM $1::uuid
  AND ($3::bool OR EXISTS (
      SELECT 1 FROM inbox_viewers iv
      WHERE iv.workspace_id = c.workspace_id AND iv.inbox_id = c.inbox_id AND iv.viewer_id = $1))
  AND ($4::timestamptz IS NULL
       OR (m.created_at, m.id) < ($4::timestamptz, $5::uuid))
ORDER BY m.created_at DESC, m.id DESC
LIMIT $6
`

type ListMentionsParams struct {
	MemberID    uuid.UUID
	WorkspaceID uuid.UUID
	AllInboxes  bool
	CursorAt    *time.Time
	CursorID    *uuid.UUID
	Lim         int32
}

type ListMentionsRow struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
	AuthorType     string
	AuthorMemberID *uuid.UUID
	AuthorApiKeyID *uuid.UUID
	Via            *string
	Body           string
	CreatedAt      time.Time
	BotName        string
	BotAvatarUrl   string
	Seen           bool
}

func (q *Queries) ListMentions(ctx context.Context, arg ListMentionsParams) ([]ListMentionsRow, error) {
	rows, err := q.db.Query(ctx, listMentions,
		arg.MemberID,
		arg.WorkspaceID,
		arg.AllInboxes,
		arg.CursorAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMentionsRow
	for rows.Next() {
		var i ListMentionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.AuthorType,
			&i.AuthorMemberID,
			&i.AuthorApiKeyID,
			&i.Via,
			&i.Body,
			&i.CreatedAt,
			&i.BotName,
			&i.BotAvatarUrl,
			&i.Seen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT m.id, m.workspace_id, m.conversation_id, m.kind, m.direction, m.author_type, m.author_member_id,
       m.author_contact_id, m.body, m.html, m.client_id, m.event, m.created_at, m.delivery_state, m.delivery_error,
       m.delivery_updated_at, m.author_api_key_id, m.draft, m.sent_by_member_id, m.sent_by_api_key_id, m.via, m.sent_via, m.mentions,
       coalesce(ak.bot_name, ak.name, '')::text AS bot_name, coalesce(ak.bot_avatar_url, '')::text AS bot_avatar_url,
       coalesce(sk.bot_name, sk.name, '')::text AS sent_by_bot_name
FROM messages m
LEFT JOIN api_keys ak ON ak.workspace_id = m.workspace_id AND ak.id = m.author_api_key_id
LEFT JOIN api_keys sk ON sk.workspace_id = m.workspace_id AND sk.id = m.sent_by_api_key_id
WHERE m.workspace_id = $1 AND m.conversation_id = $2
  AND ($3::timestamptz IS NULL
       OR (m.created_at, m.id) > ($3::timestamptz, $4::uuid))
ORDER BY m.created_at, m.id
LIMIT $5
`

type ListMessagesParams struct {
	WorkspaceID    uuid.UUID
	ConversationID uuid.UUID
	CursorAt       *time.Time
	CursorID       *uuid.UUID
	Lim            int32
}

type ListMessagesRow struct {
	ID                uuid.UUID
	WorkspaceID       uuid.UUID
	ConversationID    uuid.UUID
	Kind              string
	Direction         *string
	AuthorType        string
	AuthorMemberID    *uuid.UUID
	AuthorContactID   *uuid.UUID
	Body              string
	Html              *string
	ClientID          *string
	Event             []byte
	CreatedAt         time.Time
	DeliveryState     *string
	DeliveryError     *string
	DeliveryUpdatedAt *time.Time
	AuthorApiKeyID    *uuid.UUID
	Draft             bool
	SentByMemberID    *uuid.UUID
	SentByApiKeyID    *uuid.UUID
	Via               *string
	SentVia           *string
	Mentions          []uuid.UUID
	BotName           string
	BotAvatarUrl      string
	SentByBotName     string
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error) {
	rows, err := q.db.Query(ctx, listMessages,
		arg.WorkspaceID,
		arg.ConversationID,
		arg.CursorAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesRow
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ConversationID,
			&i.Kind,
			&i.Direction,
			&i.AuthorType,
			&i.AuthorMemberID,
			&i.AuthorContactID,
			&i.Body,
			&i.Html,
			&i.ClientID,
			&i.Event,
			&i.CreatedAt,
			&i.DeliveryState,
			&i.DeliveryError,
			&i.DeliveryUpdatedAt,
			&i.AuthorApiKeyID,
			&i.Draft,
			&i.SentByMemberID,
			&i.SentByApiKeyID,
			&i.Via,
			&i.SentVia,
			&i.Mentions,
			&i.BotName,
			&i.BotAvatarUrl,
			&i.SentByBotName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesDesc = `-- name: ListMessagesDesc :many
SELECT m.id, m.workspace_id, m.conversation_id, m.kind, m.direction, m.author_type, m.author_member_id,
       m.author_contact_id, m.body, m.html, m.client_id, m.event, m.created_at, m.delivery_state, m.delivery_error,
       m.delivery_updated_at, m.author_api_key_id, m.draft, m.sent_by_member_id, m.sent_by_api_key_id, m.via, m.sent_via, m.mentions,
       coalesce(ak.bot_name, ak.name, '')::text AS bot_name, coalesce(ak.bot_avatar_url, '')::text AS bot_avatar_url,
       coalesce(sk.bot_name, sk.name, '')::text AS sent_by_bot_name
FROM messages m
LEFT JOIN api_keys ak ON ak.workspace_id = m.workspace_id AND ak.id = m.author_api_key_id
LEFT JOIN api_keys sk ON sk.workspace_id = m.workspace_id AND sk.id = m.sent_by_api_key_id
WHERE m.workspace_id = $1 AND m.conversation_id = $2
  AND ($3::timestamptz IS NULL
       OR (m.created_at, m.id) < ($3::timestamptz, $4::uuid))
ORDER BY m.created_at DESC, m.id DESC
LIMIT $5
`

type ListMessagesDescParams struct {
	WorkspaceID    uuid.UUID
	ConversationID uuid.UUID
	CursorAt       *time.Time
	CursorID       *uuid.UUID
	Lim            int32
}

type ListMessagesDescRow struct {
	ID                uuid.UUID
	WorkspaceID       uuid.UUID
	ConversationID    uuid.UUID
	Kind              string
	Direction         *string
	AuthorType        string
	AuthorMemberID    *uuid.UUID
	AuthorContactID   *uuid.UUID
	Body              string
	Html              *string
	ClientID          *string
	Event             []byte
	CreatedAt         time.Time
	DeliveryState     *string
	DeliveryError     *string
	DeliveryUpdatedAt *time.Time
	AuthorApiKeyID    *uuid.UUID
	Draft             bool
	SentByMemberID    *uuid.UUID
	SentByApiKeyID    *uuid.UUID
	Via               *string
	SentVia           *string
	Mentions          []uuid.UUID
	BotName           string
	BotAvatarUrl      string
	SentByBotName     string
}

func (q *Queries) ListMessagesDesc(ctx context.Context, arg ListMessagesDescParams) ([]ListMessagesDescRow, error) {
	rows, err := q.db.Query(ctx, listMessagesDesc,
		arg.WorkspaceID,
		arg.ConversationID,
		arg.CursorAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesDescRow
	for rows.Next() {
		var i ListMessagesDescRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ConversationID,
			&i.Kind,
			&i.Direction,
			&i.AuthorType,
			&i.AuthorMemberID,
			&i.AuthorContactID,
			&i.Body,
			&i.Html,
			&i.ClientID,
			&i.Event,
			&i.CreatedAt,
			&i.DeliveryState,
			&i.DeliveryError,
			&i.DeliveryUpdatedAt,
			&i.AuthorApiKeyID,
			&i.Draft,
			&i.SentByMemberID,
			&i.SentByApiKeyID,
			&i.Via,
			&i.SentVia,
			&i.Mentions,
			&i.BotName,
			&i.BotAvatarUrl,
			&i.SentByBotName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMessage = `-- name: LockMessage :one
SELECT id, conversation_id, draft FROM messages WHERE workspace_id = $1 AND id = $2 FOR UPDATE
`

type LockMessageParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

type LockMessageRow struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
	Draft          bool
}

func (q *Queries) LockMessage(ctx context.Context, arg LockMessageParams) (LockMessageRow, error) {
	row := q.db.QueryRow(ctx, lockMessage, arg.WorkspaceID, arg.ID)
	var i LockMessageRow
	err := row.Scan(&i.ID, &i.ConversationID, &i.Draft)
	return i, err
}

const sendDraft = `-- name: SendDraft :one
WITH m AS (
    UPDATE messages SET draft = false, created_at = $1::timestamptz,
        sent_by_member_id = $2, sent_by_api_key_id = $3,
        sent_via = $4,
        delivery_state = $5,
        delivery_updated_at = CASE WHEN $5::text IS NULL THEN NULL ELSE $1::timestamptz END
    WHERE messages.workspace_id = $6 AND messages.id = $7 AND draft
    RETURNING id, workspace_id, conversation_id, kind, direction, author_type, author_member_id, author_contact_id, body, html, client_id, event, search, created_at, delivery_state, delivery_error, delivery_updated_at, author_api_key_id, draft, sent_by_member_id, sent_by_api_key_id, via, sent_via, mentions)
SELECT m.id, m.workspace_id, m.conversation_id, m.kind, m.direction, m.author_type, m.author_member_id,
       m.author_contact_id, m.body, m.html, m.client_id, m.event, m.created_at, m.delivery_state, m.delivery_error,
       m.delivery_updated_at, m.author_api_key_id, m.draft, m.sent_by_member_id, m.sent_by_api_key_id, m.via, m.sent_via, m.mentions,
       coalesce(ak.bot_name, ak.name, '')::text AS bot_name, coalesce(ak.bot_avatar_url, '')::text AS bot_avatar_url,
       coalesce(sk.bot_name, sk.name, '')::text AS sent_by_bot_name
FROM m
LEFT JOIN api_keys ak ON ak.workspace_id = m.workspace_id AND ak.id = m.author_api_key_id
LEFT JOIN api_keys sk ON sk.workspace_id = m.workspace_id AND sk.id = m.sent_by_api_key_id
`

type SendDraftParams struct {
	Now            time.Time
	SentByMemberID *uuid.UUID
	SentByApiKeyID *uuid.UUID
	SentVia        *string
	DeliveryState  *string
	WorkspaceID    uuid.UUID
	ID             uuid.UUID
}

type SendDraftRow struct {
	ID                uuid.UUID
	WorkspaceID       uuid.UUID
	ConversationID    uuid.UUID
	Kind              string
	Direction         *string
	AuthorType        string
	AuthorMemberID    *uuid.UUID
	AuthorContactID   *uuid.UUID
	Body              string
	Html              *string
	ClientID          *string
	Event             []byte
	CreatedAt         time.Time
	DeliveryState     *string
	DeliveryError     *string
	DeliveryUpdatedAt *time.Time
	AuthorApiKeyID    *uuid.UUID
	Draft             bool
	SentByMemberID    *uuid.UUID
	SentByApiKeyID    *uuid.UUID
	Via               *string
	SentVia           *string
	Mentions          []uuid.UUID
	BotName           string
	BotAvatarUrl      string
	SentByBotName     string
}

func (q *Queries) SendDraft(ctx context.Context, arg SendDraftParams) (SendDraftRow, error) {
	row := q.db.QueryRow(ctx, sendDraft,
		arg.Now,
		arg.SentByMemberID,
		arg.SentByApiKeyID,
		arg.SentVia,
		arg.DeliveryState,
		arg.WorkspaceID,
		arg.ID,
	)
	var i SendDraftRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ConversationID,
		&i.Kind,
		&i.Direction,
		&i.AuthorType,
		&i.AuthorMemberID,
		&i.AuthorContactID,
		&i.Body,
		&i.Html,
		&i.ClientID,
		&i.Event,
		&i.CreatedAt,
		&i.DeliveryState,
		&i.DeliveryError,
		&i.DeliveryUpdatedAt,
		&i.AuthorApiKeyID,
		&i.Draft,
		&i.SentByMemberID,
		&i.SentByApiKeyID,
		&i.Via,
		&i.SentVia,
		&i.Mentions,
		&i.BotName,
		&i.BotAvatarUrl,
		&i.SentByBotName,
	)
	return i, err
}

const setMessageDelivery = `-- name: SetMessageDelivery :one
WITH m AS (
    UPDATE messages SET delivery_state = $1::text, delivery_error = $2, delivery_updated_at = $3::timestamptz
    WHERE messages.workspace_id = $4 AND messages.id = $5
    RETURNING id, workspace_id, conversation_id, kind, direction, author_type, author_member_id, author_contact_id, body, html, client_id, event, search, created_at, delivery_state, delivery_error, delivery_updated_at, author_api_key_id, draft, sent_by_member_id, sent_by_api_key_id, via, sent_via, mentions)
SELECT m.id, m.workspace_id, m.conversation_id, m.kind, m.direction, m.author_type, m.author_member_id,
       m.author_contact_id, m.body, m.html, m.client_id, m.event, m.created_at, m.delivery_state, m.delivery_error,
       m.delivery_updated_at, m.author_api_key_id, m.draft, m.sent_by_member_id, m.sent_by_api_key_id, m.via, m.sent_via, m.mentions,
       coalesce(ak.bot_name, ak.name, '')::text AS bot_name, coalesce(ak.bot_avatar_url, '')::text AS bot_avatar_url,
       coalesce(sk.bot_name, sk.name, '')::text AS sent_by_bot_name
FROM m
LEFT JOIN api_keys ak ON ak.workspace_id = m.workspace_id AND ak.id = m.author_api_key_id
LEFT JOIN api_keys sk ON sk.workspace_id = m.workspace_id AND sk.id = m.sent_by_api_key_id
`

type SetMessageDeliveryParams struct {
	State       string
	Error       *string
	Now         time.Time
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

type SetMessageDeliveryRow struct {
	ID                uuid.UUID
	WorkspaceID       uuid.UUID
	ConversationID    uuid.UUID
	Kind              string
	Direction         *string
	AuthorType        string
	AuthorMemberID    *uuid.UUID
	AuthorContactID   *uuid.UUID
	Body              string
	Html              *string
	ClientID          *string
	Event             []byte
	CreatedAt         time.Time
	DeliveryState     *string
	DeliveryError     *string
	DeliveryUpdatedAt *time.Time
	AuthorApiKeyID    *uuid.UUID
	Draft             bool
	SentByMemberID    *uuid.UUID
	SentByApiKeyID    *uuid.UUID
	Via               *string
	SentVia           *string
	Mentions          []uuid.UUID
	BotName           string
	BotAvatarUrl      string
	SentByBotName     string
}

func (q *Queries) SetMessageDelivery(ctx context.Context, arg SetMessageDeliveryParams) (SetMessageDeliveryRow, error) {
	row := q.db.QueryRow(ctx, setMessageDelivery,
		arg.State,
		arg.Error,
		arg.Now,
		arg.WorkspaceID,
		arg.ID,
	)
	var i SetMessageDeliveryRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ConversationID,
		&i.Kind,
		&i.Direction,
		&i.AuthorType,
		&i.AuthorMemberID,
		&i.AuthorContactID,
		&i.Body,
		&i.Html,
		&i.ClientID,
		&i.Event,
		&i.CreatedAt,
		&i.DeliveryState,
		&i.DeliveryError,
		&i.DeliveryUpdatedAt,
		&i.AuthorApiKeyID,
		&i.Draft,
		&i.SentByMemberID,
		&i.SentByApiKeyID,
		&i.Via,
		&i.SentVia,
		&i.Mentions,
		&i.BotName,
		&i.BotAvatarUrl,
		&i.SentByBotName,
	)
	return i, err
}

const updateDraft = `-- name: UpdateDraft :one
WITH m AS (
    UPDATE messages SET body = $1, html = $2
    WHERE messages.workspace_id = $3 AND messages.id = $4 AND draft
    RETURNING id, workspace_id, conversation_id, kind, direction, author_type, author_member_id, author_contact_id, body, html, client_id, event, search, created_at, delivery_state, delivery_error, delivery_updated_at, author_api_key_id, draft, sent_by_member_id, sent_by_api_key_id, via, sent_via, mentions)
SELECT m.id, m.workspace_id, m.conversation_id, m.kind, m.direction, m.author_type, m.author_member_id,
       m.author_contact_id, m.body, m.html, m.client_id, m.event, m.created_at, m.delivery_state, m.delivery_error,
       m.delivery_updated_at, m.author_api_key_id, m.draft, m.sent_by_member_id, m.sent_by_api_key_id, m.via, m.sent_via, m.mentions,
       coalesce(ak.bot_name, ak.name, '')::text AS bot_name, coalesce(ak.bot_avatar_url, '')::text AS bot_avatar_url,
       coalesce(sk.bot_name, sk.name, '')::text AS sent_by_bot_name
FROM m
LEFT JOIN api_keys ak ON ak.workspace_id = m.workspace_id AND ak.id = m.author_api_key_id
LEFT JOIN api_keys sk ON sk.workspace_id = m.workspace_id AND sk.id = m.sent_by_api_key_id
`

type UpdateDraftParams struct {
	Body        string
	Html        *string
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

type UpdateDraftRow struct {
	ID                uuid.UUID
	WorkspaceID       uuid.UUID
	ConversationID    uuid.UUID
	Kind              string
	Direction         *string
	AuthorType        string
	AuthorMemberID    *uuid.UUID
	AuthorContactID   *uuid.UUID
	Body              string
	Html              *string
	ClientID          *string
	Event             []byte
	CreatedAt         time.Time
	DeliveryState     *string
	DeliveryError     *string
	DeliveryUpdatedAt *time.Time
	AuthorApiKeyID    *uuid.UUID
	Draft             bool
	SentByMemberID    *uuid.UUID
	SentByApiKeyID    *uuid.UUID
	Via               *string
	SentVia           *string
	Mentions          []uuid.UUID
	BotName           string
	BotAvatarUrl      string
	SentByBotName     string
}

func (q *Queries) UpdateDraft(ctx context.Context, arg UpdateDraftParams) (UpdateDraftRow, error) {
	row := q.db.QueryRow(ctx, updateDraft,
		arg.Body,
		arg.Html,
		arg.WorkspaceID,
		arg.ID,
	)
	var i UpdateDraftRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ConversationID,
		&i.Kind,
		&i.Direction,
		&i.AuthorType,
		&i.AuthorMemberID,
		&i.AuthorContactID,
		&i.Body,
		&i.Html,
		&i.ClientID,
		&i.Event,
		&i.CreatedAt,
		&i.DeliveryState,
		&i.DeliveryError,
		&i.DeliveryUpdatedAt,
		&i.AuthorApiKeyID,
		&i.Draft,
		&i.SentByMemberID,
		&i.SentByApiKeyID,
		&i.Via,
		&i.SentVia,
		&i.Mentions,
		&i.BotName,
		&i.BotAvatarUrl,
		&i.SentByBotName,
	)
	return i, err
}
