// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"uuid"
)

type ApiKey struct {
	ID           uuid.UUID
	WorkspaceID  uuid.UUID
	Name         string
	Prefix       string
	SecretHash   []byte
	CreatedBy    *uuid.UUID
	CreatedAt    time.Time
	LastUsedAt   *time.Time
	RevokedAt    *time.Time
	Scopes       []string
	InboxLimited bool
	ExpiresAt    *time.Time
	BotName      *string
	BotAvatarUrl *string
}

type ApiKeyInbox struct {
	WorkspaceID uuid.UUID
	ApiKeyID    uuid.UUID
	InboxID     uuid.UUID
}

type Attachment struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	ConversationID uuid.UUID
	MessageID      uuid.UUID
	StorageKey     string
	Filename       string
	ContentType    string
	SizeBytes      int64
	CreatedAt      time.Time
	ContentID      *string
	Inline         bool
}

type CannedReply struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Shortcut    string
	Title       string
	Body        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Channel struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	InboxID     uuid.UUID
	Kind        string
	Name        string
	Settings    []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ChatChannel struct {
	WorkspaceID      uuid.UUID
	ChannelID        uuid.UUID
	PublicKey        string
	AllowedOrigins   []string
	AllowAnonymous   bool
	AskEmailOffline  bool
	Greeting         string
	LauncherPosition *string
	LauncherColor    *string
	Platforms        []string
}

type ChatVisitor struct {
	WorkspaceID uuid.UUID
	InboxID     uuid.UUID
	VisitorHash []byte
	ContactID   uuid.UUID
	CreatedAt   time.Time
}

type Contact struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Attributes  []byte
	Blocked     bool
	Search      interface{}
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Locale      *string
	TypedEmail  *string
}

type ContactEmail struct {
	WorkspaceID uuid.UUID
	ContactID   uuid.UUID
	Email       string
	Position    int32
}

type ContactExternalID struct {
	WorkspaceID uuid.UUID
	InboxID     uuid.UUID
	ExternalID  string
	ContactID   uuid.UUID
}

type ContactRead struct {
	WorkspaceID       uuid.UUID
	ConversationID    uuid.UUID
	LastReadMessageID uuid.UUID
	LastReadAt        time.Time
	UpdatedAt         time.Time
}

type ContactSession struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	ChannelID   uuid.UUID
	InboxID     uuid.UUID
	ContactID   uuid.UUID
	TokenHash   []byte
	Identified  bool
	CreatedAt   time.Time
	ExpiresAt   time.Time
	LastSeenAt  time.Time
}

type Conversation struct {
	ID                    uuid.UUID
	WorkspaceID           uuid.UUID
	InboxID               uuid.UUID
	ContactID             uuid.UUID
	ChannelID             *uuid.UUID
	Subject               string
	Status                string
	SnoozeUntil           *time.Time
	Priority              string
	AssigneeID            *uuid.UUID
	LastMessageAt         *time.Time
	LastActivityAt        time.Time
	CreatedAt             time.Time
	UpdatedAt             time.Time
	Spam                  bool
	EmailToken            *string
	RelatedConversationID *uuid.UUID
	ContinuityThrough     *time.Time
	ContinuitySentAt      *time.Time
	Kind                  string
	Feedback              []byte
	EmailAddress          *string
}

type ConversationLabel struct {
	WorkspaceID    uuid.UUID
	ConversationID uuid.UUID
	LabelID        uuid.UUID
}

type ConversationRead struct {
	WorkspaceID       uuid.UUID
	MemberID          uuid.UUID
	ConversationID    uuid.UUID
	LastReadMessageID uuid.UUID
	LastReadAt        time.Time
	UpdatedAt         time.Time
}

type EmailAutoReply struct {
	WorkspaceID uuid.UUID
	ChannelID   uuid.UUID
	ContactID   uuid.UUID
	SentAt      time.Time
}

type EmailChannel struct {
	WorkspaceID            uuid.UUID
	ChannelID              uuid.UUID
	Address                string
	DisplayName            string
	FromAddress            *string
	SmtpHost               string
	SmtpPort               int32
	SmtpUsername           string
	SmtpPassword           []byte
	SmtpTls                string
	AutoReplyEnabled       bool
	AutoReplyText          string
	AutoReplyIntervalHours int32
}

type EmailConfirmation struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
	ContactID   uuid.UUID
	InboxID     uuid.UUID
	Email       string
	TokenHash   []byte
	CreatedAt   time.Time
	ExpiresAt   time.Time
}

type EmailSuppression struct {
	WorkspaceID uuid.UUID
	Email       string
	Reason      string
	Detail      string
	CreatedAt   time.Time
}

type Event struct {
	ID             int64
	WorkspaceID    uuid.UUID
	Type           string
	InboxID        *uuid.UUID
	ConversationID *uuid.UUID
	Payload        []byte
	CreatedAt      time.Time
}

type IdempotencyKey struct {
	WorkspaceID uuid.UUID
	CallerType  string
	CallerID    uuid.UUID
	Key         string
	Method      string
	Path        string
	BodySha256  []byte
	Status      *int32
	Headers     []byte
	Body        []byte
	CreatedAt   time.Time
}

type IdentityTokenID struct {
	WorkspaceID uuid.UUID
	InboxID     uuid.UUID
	Jti         string
	ExpiresAt   time.Time
}

type Inbox struct {
	ID                   uuid.UUID
	WorkspaceID          uuid.UUID
	Name                 string
	Slug                 string
	Branding             []byte
	DefaultLocale        string
	Timezone             string
	Mode                 string
	ExpectedReplyMinutes *int32
	BusinessHours        []byte
	IdentitySecret       []byte
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type InboxMember struct {
	WorkspaceID uuid.UUID
	InboxID     uuid.UUID
	MemberID    uuid.UUID
	CreatedAt   time.Time
}

type InboxNotification struct {
	WorkspaceID uuid.UUID
	MemberID    uuid.UUID
	InboxID     uuid.UUID
	Events      []byte
	UpdatedAt   time.Time
}

type InboxViewer struct {
	WorkspaceID uuid.UUID
	InboxID     uuid.UUID
	ViewerID    uuid.UUID
}

type Invite struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Email       string
	Role        string
	Locale      string
	InvitedBy   *uuid.UUID
	CreatedAt   time.Time
	ExpiresAt   time.Time
}

type Label struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Color       string
	CreatedAt   time.Time
}

type LoginCode struct {
	ID         uuid.UUID
	Email      string
	CodeHash   []byte
	Ip         string
	Attempts   int32
	CreatedAt  time.Time
	ExpiresAt  time.Time
	ConsumedAt *time.Time
}

type Member struct {
	ID                     uuid.UUID
	WorkspaceID            uuid.UUID
	PersonID               uuid.UUID
	Role                   string
	CreatedAt              time.Time
	NotificationEvents     []byte
	NotificationEmailDelay *int32
}

type Message struct {
	ID                uuid.UUID
	WorkspaceID       uuid.UUID
	ConversationID    uuid.UUID
	Kind              string
	Direction         *string
	AuthorType        string
	AuthorMemberID    *uuid.UUID
	AuthorContactID   *uuid.UUID
	Body              string
	Html              *string
	ClientID          *string
	Event             []byte
	Search            interface{}
	CreatedAt         time.Time
	DeliveryState     *string
	DeliveryError     *string
	DeliveryUpdatedAt *time.Time
	AuthorApiKeyID    *uuid.UUID
	Draft             bool
	SentByMemberID    *uuid.UUID
	SentByApiKeyID    *uuid.UUID
}

type MessageEmail struct {
	WorkspaceID           uuid.UUID
	MessageID             uuid.UUID
	ConversationID        uuid.UUID
	ChannelID             *uuid.UUID
	Direction             string
	HeaderMessageID       string
	InReplyTo             *string
	ReferencesIds         []string
	FromAddress           string
	ToAddresses           []string
	CcAddresses           []string
	Subject               string
	FullText              string
	FullHtml              *string
	Quoted                bool
	Headers               []byte
	RawKey                *string
	RawSize               *int64
	AuthenticationResults *string
	Dmarc                 string
	Auto                  bool
	CreatedAt             time.Time
}

type NotificationEmail struct {
	WorkspaceID    uuid.UUID
	MemberID       uuid.UUID
	ConversationID uuid.UUID
	SentAt         time.Time
	Through        time.Time
}

type Passkey struct {
	ID           uuid.UUID
	PersonID     uuid.UUID
	RpID         string
	CredentialID []byte
	Name         string
	Credential   []byte
	CreatedAt    time.Time
	LastUsedAt   *time.Time
}

type Person struct {
	ID             uuid.UUID
	Email          string
	Name           string
	Locale         string
	WebauthnHandle []byte
	CreatedAt      time.Time
	Availability   string
}

type PushSubscription struct {
	ID            uuid.UUID
	PersonID      uuid.UUID
	SessionID     uuid.UUID
	Endpoint      string
	P256dh        string
	Auth          string
	UserAgent     string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	LastSuccessAt *time.Time
	LastFailureAt *time.Time
	LastError     *string
}

type RealtimeConnection struct {
	ID                    uuid.UUID
	WorkspaceID           uuid.UUID
	MemberID              *uuid.UUID
	ContactID             *uuid.UUID
	SeenAt                time.Time
	ViewingConversationID *uuid.UUID
}

type Session struct {
	ID         uuid.UUID
	PersonID   uuid.UUID
	TokenHash  []byte
	Method     string
	CreatedAt  time.Time
	ExpiresAt  time.Time
	LastSeenAt time.Time
}

type UsageCounter struct {
	WorkspaceID     uuid.UUID
	Month           time.Time
	Conversations   int64
	Messages        int64
	AttachmentBytes int64
}

type WebauthnCeremony struct {
	IDHash      []byte
	Kind        string
	PersonID    *uuid.UUID
	SessionData []byte
	ExpiresAt   time.Time
}

type WebhookAttempt struct {
	ID           uuid.UUID
	WorkspaceID  uuid.UUID
	EndpointID   uuid.UUID
	DeliveryID   uuid.UUID
	AttemptedAt  time.Time
	Manual       bool
	Success      bool
	StatusCode   *int32
	LatencyMs    int32
	ResponseBody string
	Error        *string
}

type WebhookDelivery struct {
	ID            uuid.UUID
	WorkspaceID   uuid.UUID
	EndpointID    uuid.UUID
	MessageID     string
	EventType     string
	Payload       string
	State         string
	Attempts      int32
	NextAttemptAt *time.Time
	LastAttemptAt *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type WebhookEndpoint struct {
	ID                  uuid.UUID
	WorkspaceID         uuid.UUID
	InboxID             *uuid.UUID
	Url                 string
	Description         string
	Events              []string
	IncludeNotes        bool
	Enabled             bool
	Secret              []byte
	PreviousSecret      []byte
	PreviousSecretUntil *time.Time
	FailingSince        *time.Time
	DisabledAt          *time.Time
	DisabledReason      *string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type Workspace struct {
	ID            uuid.UUID
	Name          string
	CreatedAt     time.Time
	RetentionDays *int32
	DeletedAt     *time.Time
	BotsMaySend   bool
}
