// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"uuid"
)

type Workspace struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}
