// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const countOtherPushSubscriptions = `-- name: CountOtherPushSubscriptions :one
SELECT count(*) FROM push_subscriptions WHERE person_id = $1 AND endpoint <> $2
`

type CountOtherPushSubscriptionsParams struct {
	PersonID uuid.UUID
	Endpoint string
}

func (q *Queries) CountOtherPushSubscriptions(ctx context.Context, arg CountOtherPushSubscriptionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOtherPushSubscriptions, arg.PersonID, arg.Endpoint)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteInboxNotifications = `-- name: DeleteInboxNotifications :execrows
DELETE FROM inbox_notifications WHERE workspace_id = $1 AND member_id = $2 AND inbox_id = $3
`

type DeleteInboxNotificationsParams struct {
	WorkspaceID uuid.UUID
	MemberID    uuid.UUID
	InboxID     uuid.UUID
}

func (q *Queries) DeleteInboxNotifications(ctx context.Context, arg DeleteInboxNotificationsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInboxNotifications, arg.WorkspaceID, arg.MemberID, arg.InboxID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePushSubscription = `-- name: DeletePushSubscription :execrows
DELETE FROM push_subscriptions WHERE person_id = $1 AND id = $2
`

type DeletePushSubscriptionParams struct {
	PersonID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) DeletePushSubscription(ctx context.Context, arg DeletePushSubscriptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePushSubscription, arg.PersonID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const dropPushSubscription = `-- name: DropPushSubscription :execrows
DELETE FROM push_subscriptions WHERE id = $1 AND endpoint = $2
`

type DropPushSubscriptionParams struct {
	ID       uuid.UUID
	Endpoint string
}

func (q *Queries) DropPushSubscription(ctx context.Context, arg DropPushSubscriptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, dropPushSubscription, arg.ID, arg.Endpoint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLivePushSubscription = `-- name: GetLivePushSubscription :one
SELECT ps.id, ps.person_id, ps.session_id, ps.endpoint, ps.p256dh, ps.auth, ps.user_agent, ps.created_at, ps.updated_at, ps.last_success_at, ps.last_failure_at, ps.last_error FROM push_subscriptions ps JOIN sessions s ON s.id = ps.session_id
WHERE ps.id = $1 AND s.expires_at > $2
`

type GetLivePushSubscriptionParams struct {
	ID  uuid.UUID
	Now time.Time
}

func (q *Queries) GetLivePushSubscription(ctx context.Context, arg GetLivePushSubscriptionParams) (PushSubscription, error) {
	row := q.db.QueryRow(ctx, getLivePushSubscription, arg.ID, arg.Now)
	var i PushSubscription
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.SessionID,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.LastError,
	)
	return i, err
}

const getNotificationEmail = `-- name: GetNotificationEmail :one
SELECT workspace_id, member_id, conversation_id, sent_at, through FROM notification_emails WHERE workspace_id = $1 AND member_id = $2 AND conversation_id = $3
`

type GetNotificationEmailParams struct {
	WorkspaceID    uuid.UUID
	MemberID       uuid.UUID
	ConversationID uuid.UUID
}

func (q *Queries) GetNotificationEmail(ctx context.Context, arg GetNotificationEmailParams) (NotificationEmail, error) {
	row := q.db.QueryRow(ctx, getNotificationEmail, arg.WorkspaceID, arg.MemberID, arg.ConversationID)
	var i NotificationEmail
	err := row.Scan(
		&i.WorkspaceID,
		&i.MemberID,
		&i.ConversationID,
		&i.SentAt,
		&i.Through,
	)
	return i, err
}

const getPushSubscription = `-- name: GetPushSubscription :one
SELECT id, person_id, session_id, endpoint, p256dh, auth, user_agent, created_at, updated_at, last_success_at, last_failure_at, last_error FROM push_subscriptions WHERE person_id = $1 AND id = $2
`

type GetPushSubscriptionParams struct {
	PersonID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetPushSubscription(ctx context.Context, arg GetPushSubscriptionParams) (PushSubscription, error) {
	row := q.db.QueryRow(ctx, getPushSubscription, arg.PersonID, arg.ID)
	var i PushSubscription
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.SessionID,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.LastError,
	)
	return i, err
}

const listInboxNotifications = `-- name: ListInboxNotifications :many
SELECT n.workspace_id, n.member_id, n.inbox_id, n.events, n.updated_at FROM inbox_notifications n
WHERE n.workspace_id = $1 AND n.member_id = $2
  AND ($3::bool OR EXISTS (
      SELECT 1 FROM inbox_members im
      WHERE im.workspace_id = n.workspace_id AND im.inbox_id = n.inbox_id AND im.member_id = n.member_id))
ORDER BY n.updated_at, n.inbox_id
`

type ListInboxNotificationsParams struct {
	WorkspaceID uuid.UUID
	MemberID    uuid.UUID
	AllInboxes  bool
}

func (q *Queries) ListInboxNotifications(ctx context.Context, arg ListInboxNotificationsParams) ([]InboxNotification, error) {
	rows, err := q.db.Query(ctx, listInboxNotifications, arg.WorkspaceID, arg.MemberID, arg.AllInboxes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InboxNotification
	for rows.Next() {
		var i InboxNotification
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.MemberID,
			&i.InboxID,
			&i.Events,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInboxNotificationsOfInbox = `-- name: ListInboxNotificationsOfInbox :many
SELECT workspace_id, member_id, inbox_id, events, updated_at FROM inbox_notifications WHERE workspace_id = $1 AND inbox_id = $2
`

type ListInboxNotificationsOfInboxParams struct {
	WorkspaceID uuid.UUID
	InboxID     uuid.UUID
}

func (q *Queries) ListInboxNotificationsOfInbox(ctx context.Context, arg ListInboxNotificationsOfInboxParams) ([]InboxNotification, error) {
	rows, err := q.db.Query(ctx, listInboxNotificationsOfInbox, arg.WorkspaceID, arg.InboxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InboxNotification
	for rows.Next() {
		var i InboxNotification
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.MemberID,
			&i.InboxID,
			&i.Events,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLivePushSubscriptionIDs = `-- name: ListLivePushSubscriptionIDs :many
SELECT ps.id FROM push_subscriptions ps JOIN sessions s ON s.id = ps.session_id
WHERE ps.person_id = $1 AND s.expires_at > $2
ORDER BY ps.created_at, ps.id
`

type ListLivePushSubscriptionIDsParams struct {
	PersonID uuid.UUID
	Now      time.Time
}

func (q *Queries) ListLivePushSubscriptionIDs(ctx context.Context, arg ListLivePushSubscriptionIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listLivePushSubscriptionIDs, arg.PersonID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifiableMessages = `-- name: ListNotifiableMessages :many
SELECT id, kind, body, author_member_id, created_at FROM messages
WHERE workspace_id = $1 AND conversation_id = $2 AND created_at > $3
  AND ((kind = 'message' AND author_type = 'contact')
       OR (kind = 'event' AND event->>'type' = 'assigned' AND (event->>'assignee_id')::uuid = $4::uuid
           AND author_member_id IS DISTINCT FROM $4::uuid))
ORDER BY created_at, id
LIMIT 50
`

type ListNotifiableMessagesParams struct {
	WorkspaceID    uuid.UUID
	ConversationID uuid.UUID
	After          time.Time
	MemberID       uuid.UUID
}

type ListNotifiableMessagesRow struct {
	ID             uuid.UUID
	Kind           string
	Body           string
	AuthorMemberID *uuid.UUID
	CreatedAt      time.Time
}

func (q *Queries) ListNotifiableMessages(ctx context.Context, arg ListNotifiableMessagesParams) ([]ListNotifiableMessagesRow, error) {
	rows, err := q.db.Query(ctx, listNotifiableMessages,
		arg.WorkspaceID,
		arg.ConversationID,
		arg.After,
		arg.MemberID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotifiableMessagesRow
	for rows.Next() {
		var i ListNotifiableMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Body,
			&i.AuthorMemberID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationCandidates = `-- name: ListNotificationCandidates :many
SELECT m.id, m.role, m.person_id, m.notification_events, m.notification_email_delay,
       p.email, p.locale, p.availability
FROM members m JOIN people p ON p.id = m.person_id
WHERE m.workspace_id = $1
  AND (m.role IN ('owner', 'admin') OR EXISTS (
      SELECT 1 FROM inbox_members im
      WHERE im.workspace_id = m.workspace_id AND im.inbox_id = $2 AND im.member_id = m.id))
ORDER BY m.id
`

type ListNotificationCandidatesParams struct {
	WorkspaceID uuid.UUID
	InboxID     uuid.UUID
}

type ListNotificationCandidatesRow struct {
	ID                     uuid.UUID
	Role                   string
	PersonID               uuid.UUID
	NotificationEvents     []byte
	NotificationEmailDelay *int32
	Email                  string
	Locale                 string
	Availability           string
}

func (q *Queries) ListNotificationCandidates(ctx context.Context, arg ListNotificationCandidatesParams) ([]ListNotificationCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listNotificationCandidates, arg.WorkspaceID, arg.InboxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationCandidatesRow
	for rows.Next() {
		var i ListNotificationCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.PersonID,
			&i.NotificationEvents,
			&i.NotificationEmailDelay,
			&i.Email,
			&i.Locale,
			&i.Availability,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPushSubscriptions = `-- name: ListPushSubscriptions :many
SELECT id, person_id, session_id, endpoint, p256dh, auth, user_agent, created_at, updated_at, last_success_at, last_failure_at, last_error FROM push_subscriptions WHERE person_id = $1 ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListPushSubscriptions(ctx context.Context, personID uuid.UUID) ([]PushSubscription, error) {
	rows, err := q.db.Query(ctx, listPushSubscriptions, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PushSubscription
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.SessionID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.UserAgent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastSuccessAt,
			&i.LastFailureAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listViewingMembers = `-- name: ListViewingMembers :many
SELECT DISTINCT member_id::uuid FROM realtime_connections
WHERE workspace_id = $1 AND viewing_conversation_id = $2
  AND member_id IS NOT NULL AND seen_at > $3
`

type ListViewingMembersParams struct {
	WorkspaceID    uuid.UUID
	ConversationID *uuid.UUID
	FreshAfter     time.Time
}

func (q *Queries) ListViewingMembers(ctx context.Context, arg ListViewingMembersParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listViewingMembers, arg.WorkspaceID, arg.ConversationID, arg.FreshAfter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var member_id uuid.UUID
		if err := rows.Scan(&member_id); err != nil {
			return nil, err
		}
		items = append(items, member_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pushFailed = `-- name: PushFailed :exec
UPDATE push_subscriptions SET last_failure_at = $1::timestamptz, last_error = $2 WHERE id = $3
`

type PushFailedParams struct {
	Now   time.Time
	Error *string
	ID    uuid.UUID
}

func (q *Queries) PushFailed(ctx context.Context, arg PushFailedParams) error {
	_, err := q.db.Exec(ctx, pushFailed, arg.Now, arg.Error, arg.ID)
	return err
}

const pushSucceeded = `-- name: PushSucceeded :exec
UPDATE push_subscriptions SET last_success_at = $1::timestamptz, last_error = NULL WHERE id = $2
`

type PushSucceededParams struct {
	Now time.Time
	ID  uuid.UUID
}

func (q *Queries) PushSucceeded(ctx context.Context, arg PushSucceededParams) error {
	_, err := q.db.Exec(ctx, pushSucceeded, arg.Now, arg.ID)
	return err
}

const recordNotificationEmail = `-- name: RecordNotificationEmail :exec
INSERT INTO notification_emails (workspace_id, member_id, conversation_id, sent_at, through)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (workspace_id, member_id, conversation_id) DO UPDATE SET sent_at = excluded.sent_at, through = excluded.through
`

type RecordNotificationEmailParams struct {
	WorkspaceID    uuid.UUID
	MemberID       uuid.UUID
	ConversationID uuid.UUID
	Now            time.Time
	Through        time.Time
}

func (q *Queries) RecordNotificationEmail(ctx context.Context, arg RecordNotificationEmailParams) error {
	_, err := q.db.Exec(ctx, recordNotificationEmail,
		arg.WorkspaceID,
		arg.MemberID,
		arg.ConversationID,
		arg.Now,
		arg.Through,
	)
	return err
}

const setConnectionViewing = `-- name: SetConnectionViewing :exec
UPDATE realtime_connections SET viewing_conversation_id = $1, seen_at = $2
WHERE workspace_id = $3 AND id = $4
`

type SetConnectionViewingParams struct {
	ConversationID *uuid.UUID
	Now            time.Time
	WorkspaceID    uuid.UUID
	ID             uuid.UUID
}

func (q *Queries) SetConnectionViewing(ctx context.Context, arg SetConnectionViewingParams) error {
	_, err := q.db.Exec(ctx, setConnectionViewing,
		arg.ConversationID,
		arg.Now,
		arg.WorkspaceID,
		arg.ID,
	)
	return err
}

const setMemberNotifications = `-- name: SetMemberNotifications :exec
UPDATE members SET notification_events = $1, notification_email_delay = $2
WHERE workspace_id = $3 AND id = $4
`

type SetMemberNotificationsParams struct {
	Events      []byte
	EmailDelay  *int32
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) SetMemberNotifications(ctx context.Context, arg SetMemberNotificationsParams) error {
	_, err := q.db.Exec(ctx, setMemberNotifications,
		arg.Events,
		arg.EmailDelay,
		arg.WorkspaceID,
		arg.ID,
	)
	return err
}

const upsertInboxNotifications = `-- name: UpsertInboxNotifications :one
INSERT INTO inbox_notifications (workspace_id, member_id, inbox_id, events, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (workspace_id, member_id, inbox_id) DO UPDATE SET events = excluded.events, updated_at = excluded.updated_at
RETURNING workspace_id, member_id, inbox_id, events, updated_at
`

type UpsertInboxNotificationsParams struct {
	WorkspaceID uuid.UUID
	MemberID    uuid.UUID
	InboxID     uuid.UUID
	Events      []byte
	Now         time.Time
}

func (q *Queries) UpsertInboxNotifications(ctx context.Context, arg UpsertInboxNotificationsParams) (InboxNotification, error) {
	row := q.db.QueryRow(ctx, upsertInboxNotifications,
		arg.WorkspaceID,
		arg.MemberID,
		arg.InboxID,
		arg.Events,
		arg.Now,
	)
	var i InboxNotification
	err := row.Scan(
		&i.WorkspaceID,
		&i.MemberID,
		&i.InboxID,
		&i.Events,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPushSubscription = `-- name: UpsertPushSubscription :one
INSERT INTO push_subscriptions (id, person_id, session_id, endpoint, p256dh, auth, user_agent, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $8)
ON CONFLICT (endpoint) DO UPDATE SET person_id = excluded.person_id, session_id = excluded.session_id,
    p256dh = excluded.p256dh, auth = excluded.auth, user_agent = excluded.user_agent, updated_at = excluded.updated_at,
    last_failure_at = NULL, last_error = NULL
RETURNING id, person_id, session_id, endpoint, p256dh, auth, user_agent, created_at, updated_at, last_success_at, last_failure_at, last_error
`

type UpsertPushSubscriptionParams struct {
	ID        uuid.UUID
	PersonID  uuid.UUID
	SessionID uuid.UUID
	Endpoint  string
	P256dh    string
	Auth      string
	UserAgent string
	Now       time.Time
}

func (q *Queries) UpsertPushSubscription(ctx context.Context, arg UpsertPushSubscriptionParams) (PushSubscription, error) {
	row := q.db.QueryRow(ctx, upsertPushSubscription,
		arg.ID,
		arg.PersonID,
		arg.SessionID,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
		arg.UserAgent,
		arg.Now,
	)
	var i PushSubscription
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.SessionID,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.LastError,
	)
	return i, err
}
