// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const countOAuthGrantRequest = `-- name: CountOAuthGrantRequest :exec
UPDATE oauth_grants SET last_used_at = $1::timestamptz,
    request_count = CASE WHEN request_month = $2::date THEN request_count + 1 ELSE 1 END,
    request_month = $2::date
WHERE workspace_id = $3 AND id = $4
`

type CountOAuthGrantRequestParams struct {
	Now         time.Time
	Month       time.Time
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) CountOAuthGrantRequest(ctx context.Context, arg CountOAuthGrantRequestParams) error {
	_, err := q.db.Exec(ctx, countOAuthGrantRequest,
		arg.Now,
		arg.Month,
		arg.WorkspaceID,
		arg.ID,
	)
	return err
}

const createOAuthClient = `-- name: CreateOAuthClient :one
INSERT INTO oauth_clients (id, client_id, kind, name, client_uri, redirect_uris, created_at, fetched_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, client_id, kind, name, client_uri, redirect_uris, created_at, fetched_at
`

type CreateOAuthClientParams struct {
	ID           uuid.UUID
	ClientID     string
	Kind         string
	Name         string
	ClientUri    *string
	RedirectUris []string
	CreatedAt    time.Time
	FetchedAt    *time.Time
}

func (q *Queries) CreateOAuthClient(ctx context.Context, arg CreateOAuthClientParams) (OauthClient, error) {
	row := q.db.QueryRow(ctx, createOAuthClient,
		arg.ID,
		arg.ClientID,
		arg.Kind,
		arg.Name,
		arg.ClientUri,
		arg.RedirectUris,
		arg.CreatedAt,
		arg.FetchedAt,
	)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Kind,
		&i.Name,
		&i.ClientUri,
		&i.RedirectUris,
		&i.CreatedAt,
		&i.FetchedAt,
	)
	return i, err
}

const createOAuthCode = `-- name: CreateOAuthCode :exec
INSERT INTO oauth_codes (workspace_id, id, grant_id, code_hash, redirect_uri, code_challenge, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateOAuthCodeParams struct {
	WorkspaceID   uuid.UUID
	ID            uuid.UUID
	GrantID       uuid.UUID
	CodeHash      []byte
	RedirectUri   string
	CodeChallenge string
	CreatedAt     time.Time
	ExpiresAt     time.Time
}

func (q *Queries) CreateOAuthCode(ctx context.Context, arg CreateOAuthCodeParams) error {
	_, err := q.db.Exec(ctx, createOAuthCode,
		arg.WorkspaceID,
		arg.ID,
		arg.GrantID,
		arg.CodeHash,
		arg.RedirectUri,
		arg.CodeChallenge,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const createOAuthRequest = `-- name: CreateOAuthRequest :exec
INSERT INTO oauth_requests (id, client_id, redirect_uri, state, code_challenge, scopes, resource, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateOAuthRequestParams struct {
	ID            uuid.UUID
	ClientID      uuid.UUID
	RedirectUri   string
	State         *string
	CodeChallenge string
	Scopes        []string
	Resource      string
	CreatedAt     time.Time
	ExpiresAt     time.Time
}

func (q *Queries) CreateOAuthRequest(ctx context.Context, arg CreateOAuthRequestParams) error {
	_, err := q.db.Exec(ctx, createOAuthRequest,
		arg.ID,
		arg.ClientID,
		arg.RedirectUri,
		arg.State,
		arg.CodeChallenge,
		arg.Scopes,
		arg.Resource,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const createOAuthToken = `-- name: CreateOAuthToken :exec
INSERT INTO oauth_tokens (workspace_id, id, grant_id, kind, token_hash, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateOAuthTokenParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
	GrantID     uuid.UUID
	Kind        string
	TokenHash   []byte
	CreatedAt   time.Time
	ExpiresAt   time.Time
}

func (q *Queries) CreateOAuthToken(ctx context.Context, arg CreateOAuthTokenParams) error {
	_, err := q.db.Exec(ctx, createOAuthToken,
		arg.WorkspaceID,
		arg.ID,
		arg.GrantID,
		arg.Kind,
		arg.TokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredOAuthCodes = `-- name: DeleteExpiredOAuthCodes :execrows
DELETE FROM oauth_codes WHERE workspace_id = $1 AND expires_at < $2::timestamptz
`

type DeleteExpiredOAuthCodesParams struct {
	WorkspaceID uuid.UUID
	Before      time.Time
}

func (q *Queries) DeleteExpiredOAuthCodes(ctx context.Context, arg DeleteExpiredOAuthCodesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredOAuthCodes, arg.WorkspaceID, arg.Before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredOAuthRequests = `-- name: DeleteExpiredOAuthRequests :execrows
DELETE FROM oauth_requests WHERE expires_at < $1::timestamptz
`

func (q *Queries) DeleteExpiredOAuthRequests(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredOAuthRequests, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredOAuthTokens = `-- name: DeleteExpiredOAuthTokens :execrows
DELETE FROM oauth_tokens WHERE workspace_id = $1 AND expires_at < $2::timestamptz
`

type DeleteExpiredOAuthTokensParams struct {
	WorkspaceID uuid.UUID
	Before      time.Time
}

func (q *Queries) DeleteExpiredOAuthTokens(ctx context.Context, arg DeleteExpiredOAuthTokensParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredOAuthTokens, arg.WorkspaceID, arg.Before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOAuthGrantCodes = `-- name: DeleteOAuthGrantCodes :exec
DELETE FROM oauth_codes WHERE workspace_id = $1 AND grant_id = $2
`

type DeleteOAuthGrantCodesParams struct {
	WorkspaceID uuid.UUID
	GrantID     uuid.UUID
}

func (q *Queries) DeleteOAuthGrantCodes(ctx context.Context, arg DeleteOAuthGrantCodesParams) error {
	_, err := q.db.Exec(ctx, deleteOAuthGrantCodes, arg.WorkspaceID, arg.GrantID)
	return err
}

const deleteOAuthGrantTokens = `-- name: DeleteOAuthGrantTokens :exec
DELETE FROM oauth_tokens WHERE workspace_id = $1 AND grant_id = $2
`

type DeleteOAuthGrantTokensParams struct {
	WorkspaceID uuid.UUID
	GrantID     uuid.UUID
}

func (q *Queries) DeleteOAuthGrantTokens(ctx context.Context, arg DeleteOAuthGrantTokensParams) error {
	_, err := q.db.Exec(ctx, deleteOAuthGrantTokens, arg.WorkspaceID, arg.GrantID)
	return err
}

const deleteOAuthRequest = `-- name: DeleteOAuthRequest :execrows
DELETE FROM oauth_requests WHERE id = $1
`

func (q *Queries) DeleteOAuthRequest(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOAuthRequest, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOAuthToken = `-- name: DeleteOAuthToken :exec
DELETE FROM oauth_tokens WHERE workspace_id = $1 AND id = $2
`

type DeleteOAuthTokenParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) DeleteOAuthToken(ctx context.Context, arg DeleteOAuthTokenParams) error {
	_, err := q.db.Exec(ctx, deleteOAuthToken, arg.WorkspaceID, arg.ID)
	return err
}

const deleteUnusedOAuthClients = `-- name: DeleteUnusedOAuthClients :execrows
DELETE FROM oauth_clients c
WHERE c.created_at < $1::timestamptz
  AND NOT EXISTS (SELECT 1 FROM oauth_grants g WHERE g.client_id = c.id)
  AND NOT EXISTS (SELECT 1 FROM oauth_requests r WHERE r.client_id = c.id)
`

func (q *Queries) DeleteUnusedOAuthClients(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUnusedOAuthClients, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOAuthAccess = `-- name: GetOAuthAccess :one
SELECT t.expires_at, g.workspace_id, g.id AS grant_id, g.scopes, g.resource, m.id AS member_id, m.role,
       cl.name AS client_name, w.bots_may_send
FROM oauth_tokens t
JOIN oauth_grants g ON g.workspace_id = t.workspace_id AND g.id = t.grant_id
JOIN members m ON m.workspace_id = g.workspace_id AND m.id = g.member_id
JOIN oauth_clients cl ON cl.id = g.client_id
JOIN workspaces w ON w.id = g.workspace_id
WHERE t.token_hash = $1 AND t.kind = 'access' AND g.revoked_at IS NULL AND w.deleted_at IS NULL
`

type GetOAuthAccessRow struct {
	ExpiresAt   time.Time
	WorkspaceID uuid.UUID
	GrantID     uuid.UUID
	Scopes      []string
	Resource    string
	MemberID    uuid.UUID
	Role        string
	ClientName  string
	BotsMaySend bool
}

func (q *Queries) GetOAuthAccess(ctx context.Context, tokenHash []byte) (GetOAuthAccessRow, error) {
	row := q.db.QueryRow(ctx, getOAuthAccess, tokenHash)
	var i GetOAuthAccessRow
	err := row.Scan(
		&i.ExpiresAt,
		&i.WorkspaceID,
		&i.GrantID,
		&i.Scopes,
		&i.Resource,
		&i.MemberID,
		&i.Role,
		&i.ClientName,
		&i.BotsMaySend,
	)
	return i, err
}

const getOAuthClientByClientID = `-- name: GetOAuthClientByClientID :one
SELECT id, client_id, kind, name, client_uri, redirect_uris, created_at, fetched_at FROM oauth_clients WHERE client_id = $1
`

func (q *Queries) GetOAuthClientByClientID(ctx context.Context, clientID string) (OauthClient, error) {
	row := q.db.QueryRow(ctx, getOAuthClientByClientID, clientID)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Kind,
		&i.Name,
		&i.ClientUri,
		&i.RedirectUris,
		&i.CreatedAt,
		&i.FetchedAt,
	)
	return i, err
}

const getOAuthGrant = `-- name: GetOAuthGrant :one
SELECT workspace_id, id, member_id, client_id, scopes, resource, created_at, last_used_at, request_month, request_count, revoked_at FROM oauth_grants WHERE workspace_id = $1 AND id = $2 AND revoked_at IS NULL
`

type GetOAuthGrantParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetOAuthGrant(ctx context.Context, arg GetOAuthGrantParams) (OauthGrant, error) {
	row := q.db.QueryRow(ctx, getOAuthGrant, arg.WorkspaceID, arg.ID)
	var i OauthGrant
	err := row.Scan(
		&i.WorkspaceID,
		&i.ID,
		&i.MemberID,
		&i.ClientID,
		&i.Scopes,
		&i.Resource,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RequestMonth,
		&i.RequestCount,
		&i.RevokedAt,
	)
	return i, err
}

const getOAuthRequest = `-- name: GetOAuthRequest :one
SELECT r.id, r.redirect_uri, r.state, r.code_challenge, r.scopes, r.resource, r.created_at, r.expires_at,
       c.id AS client_ref, c.client_id AS client_key, c.name AS client_name, c.client_uri
FROM oauth_requests r JOIN oauth_clients c ON c.id = r.client_id
WHERE r.id = $1 AND r.expires_at > $2::timestamptz
`

type GetOAuthRequestParams struct {
	ID  uuid.UUID
	Now time.Time
}

type GetOAuthRequestRow struct {
	ID            uuid.UUID
	RedirectUri   string
	State         *string
	CodeChallenge string
	Scopes        []string
	Resource      string
	CreatedAt     time.Time
	ExpiresAt     time.Time
	ClientRef     uuid.UUID
	ClientKey     string
	ClientName    string
	ClientUri     *string
}

func (q *Queries) GetOAuthRequest(ctx context.Context, arg GetOAuthRequestParams) (GetOAuthRequestRow, error) {
	row := q.db.QueryRow(ctx, getOAuthRequest, arg.ID, arg.Now)
	var i GetOAuthRequestRow
	err := row.Scan(
		&i.ID,
		&i.RedirectUri,
		&i.State,
		&i.CodeChallenge,
		&i.Scopes,
		&i.Resource,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ClientRef,
		&i.ClientKey,
		&i.ClientName,
		&i.ClientUri,
	)
	return i, err
}

const getOAuthTokenByHash = `-- name: GetOAuthTokenByHash :one
SELECT t.workspace_id, t.id, t.grant_id, t.kind, cl.client_id AS client_key
FROM oauth_tokens t
JOIN oauth_grants g ON g.workspace_id = t.workspace_id AND g.id = t.grant_id
JOIN oauth_clients cl ON cl.id = g.client_id
WHERE t.token_hash = $1
`

type GetOAuthTokenByHashRow struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
	GrantID     uuid.UUID
	Kind        string
	ClientKey   string
}

func (q *Queries) GetOAuthTokenByHash(ctx context.Context, tokenHash []byte) (GetOAuthTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getOAuthTokenByHash, tokenHash)
	var i GetOAuthTokenByHashRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.ID,
		&i.GrantID,
		&i.Kind,
		&i.ClientKey,
	)
	return i, err
}

const listOAuthGrants = `-- name: ListOAuthGrants :many
SELECT g.id, g.member_id, g.scopes, g.resource, g.created_at, g.last_used_at, g.request_month, g.request_count,
       cl.client_id AS client_key, cl.name AS client_name, cl.client_uri
FROM oauth_grants g JOIN oauth_clients cl ON cl.id = g.client_id
WHERE g.workspace_id = $1 AND g.revoked_at IS NULL
  AND ($2::uuid IS NULL OR g.member_id = $2::uuid)
ORDER BY g.created_at, g.id
`

type ListOAuthGrantsParams struct {
	WorkspaceID uuid.UUID
	MemberID    *uuid.UUID
}

type ListOAuthGrantsRow struct {
	ID           uuid.UUID
	MemberID     uuid.UUID
	Scopes       []string
	Resource     string
	CreatedAt    time.Time
	LastUsedAt   *time.Time
	RequestMonth *time.Time
	RequestCount int64
	ClientKey    string
	ClientName   string
	ClientUri    *string
}

func (q *Queries) ListOAuthGrants(ctx context.Context, arg ListOAuthGrantsParams) ([]ListOAuthGrantsRow, error) {
	rows, err := q.db.Query(ctx, listOAuthGrants, arg.WorkspaceID, arg.MemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOAuthGrantsRow
	for rows.Next() {
		var i ListOAuthGrantsRow
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Scopes,
			&i.Resource,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RequestMonth,
			&i.RequestCount,
			&i.ClientKey,
			&i.ClientName,
			&i.ClientUri,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOAuthCode = `-- name: LockOAuthCode :one
SELECT oc.workspace_id, oc.id, oc.grant_id, oc.redirect_uri, oc.code_challenge, oc.expires_at, oc.used_at,
       g.scopes, g.resource, cl.client_id AS client_key
FROM oauth_codes oc
JOIN oauth_grants g ON g.workspace_id = oc.workspace_id AND g.id = oc.grant_id
JOIN oauth_clients cl ON cl.id = g.client_id
WHERE oc.code_hash = $1 AND g.revoked_at IS NULL
FOR UPDATE OF oc
`

type LockOAuthCodeRow struct {
	WorkspaceID   uuid.UUID
	ID            uuid.UUID
	GrantID       uuid.UUID
	RedirectUri   string
	CodeChallenge string
	ExpiresAt     time.Time
	UsedAt        *time.Time
	Scopes        []string
	Resource      string
	ClientKey     string
}

func (q *Queries) LockOAuthCode(ctx context.Context, codeHash []byte) (LockOAuthCodeRow, error) {
	row := q.db.QueryRow(ctx, lockOAuthCode, codeHash)
	var i LockOAuthCodeRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.ID,
		&i.GrantID,
		&i.RedirectUri,
		&i.CodeChallenge,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.Scopes,
		&i.Resource,
		&i.ClientKey,
	)
	return i, err
}

const lockOAuthRefreshToken = `-- name: LockOAuthRefreshToken :one
SELECT t.workspace_id, t.id, t.grant_id, t.expires_at, t.used_at, g.scopes, g.resource, cl.client_id AS client_key
FROM oauth_tokens t
JOIN oauth_grants g ON g.workspace_id = t.workspace_id AND g.id = t.grant_id
JOIN oauth_clients cl ON cl.id = g.client_id
WHERE t.token_hash = $1 AND t.kind = 'refresh' AND g.revoked_at IS NULL
FOR UPDATE OF t
`

type LockOAuthRefreshTokenRow struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
	GrantID     uuid.UUID
	ExpiresAt   time.Time
	UsedAt      *time.Time
	Scopes      []string
	Resource    string
	ClientKey   string
}

func (q *Queries) LockOAuthRefreshToken(ctx context.Context, tokenHash []byte) (LockOAuthRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, lockOAuthRefreshToken, tokenHash)
	var i LockOAuthRefreshTokenRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.ID,
		&i.GrantID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.Scopes,
		&i.Resource,
		&i.ClientKey,
	)
	return i, err
}

const markOAuthCodeUsed = `-- name: MarkOAuthCodeUsed :exec
UPDATE oauth_codes SET used_at = $1::timestamptz WHERE workspace_id = $2 AND id = $3
`

type MarkOAuthCodeUsedParams struct {
	Now         time.Time
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) MarkOAuthCodeUsed(ctx context.Context, arg MarkOAuthCodeUsedParams) error {
	_, err := q.db.Exec(ctx, markOAuthCodeUsed, arg.Now, arg.WorkspaceID, arg.ID)
	return err
}

const markOAuthTokenUsed = `-- name: MarkOAuthTokenUsed :exec
UPDATE oauth_tokens SET used_at = $1::timestamptz WHERE workspace_id = $2 AND id = $3
`

type MarkOAuthTokenUsedParams struct {
	Now         time.Time
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) MarkOAuthTokenUsed(ctx context.Context, arg MarkOAuthTokenUsedParams) error {
	_, err := q.db.Exec(ctx, markOAuthTokenUsed, arg.Now, arg.WorkspaceID, arg.ID)
	return err
}

const revokeOAuthGrant = `-- name: RevokeOAuthGrant :execrows
UPDATE oauth_grants SET revoked_at = coalesce(revoked_at, $1::timestamptz)
WHERE workspace_id = $2 AND id = $3
`

type RevokeOAuthGrantParams struct {
	Now         time.Time
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) RevokeOAuthGrant(ctx context.Context, arg RevokeOAuthGrantParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeOAuthGrant, arg.Now, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveMetadataClient = `-- name: SaveMetadataClient :one
INSERT INTO oauth_clients (id, client_id, kind, name, client_uri, redirect_uris, created_at, fetched_at)
VALUES ($1, $2, 'metadata', $3, $4, $5, $6::timestamptz, $6::timestamptz)
ON CONFLICT (client_id) DO UPDATE SET name = EXCLUDED.name, client_uri = EXCLUDED.client_uri,
    redirect_uris = EXCLUDED.redirect_uris, fetched_at = EXCLUDED.fetched_at
RETURNING id, client_id, kind, name, client_uri, redirect_uris, created_at, fetched_at
`

type SaveMetadataClientParams struct {
	ID           uuid.UUID
	ClientID     string
	Name         string
	ClientUri    *string
	RedirectUris []string
	Now          time.Time
}

func (q *Queries) SaveMetadataClient(ctx context.Context, arg SaveMetadataClientParams) (OauthClient, error) {
	row := q.db.QueryRow(ctx, saveMetadataClient,
		arg.ID,
		arg.ClientID,
		arg.Name,
		arg.ClientUri,
		arg.RedirectUris,
		arg.Now,
	)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Kind,
		&i.Name,
		&i.ClientUri,
		&i.RedirectUris,
		&i.CreatedAt,
		&i.FetchedAt,
	)
	return i, err
}

const upsertOAuthGrant = `-- name: UpsertOAuthGrant :one
INSERT INTO oauth_grants (workspace_id, id, member_id, client_id, scopes, resource, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (workspace_id, member_id, client_id) WHERE revoked_at IS NULL
DO UPDATE SET scopes = EXCLUDED.scopes, resource = EXCLUDED.resource
RETURNING workspace_id, id, member_id, client_id, scopes, resource, created_at, last_used_at, request_month, request_count, revoked_at
`

type UpsertOAuthGrantParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
	MemberID    uuid.UUID
	ClientID    uuid.UUID
	Scopes      []string
	Resource    string
	CreatedAt   time.Time
}

func (q *Queries) UpsertOAuthGrant(ctx context.Context, arg UpsertOAuthGrantParams) (OauthGrant, error) {
	row := q.db.QueryRow(ctx, upsertOAuthGrant,
		arg.WorkspaceID,
		arg.ID,
		arg.MemberID,
		arg.ClientID,
		arg.Scopes,
		arg.Resource,
		arg.CreatedAt,
	)
	var i OauthGrant
	err := row.Scan(
		&i.WorkspaceID,
		&i.ID,
		&i.MemberID,
		&i.ClientID,
		&i.Scopes,
		&i.Resource,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RequestMonth,
		&i.RequestCount,
		&i.RevokedAt,
	)
	return i, err
}
