// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pages.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const addPageRating = `-- name: AddPageRating :exec
INSERT INTO page_ratings (workspace_id, inbox_id, channel_id, page, title, day, up, down)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (workspace_id, channel_id, page, day) DO UPDATE SET
    up = page_ratings.up + excluded.up,
    down = page_ratings.down + excluded.down,
    title = CASE WHEN excluded.title <> '' THEN excluded.title ELSE page_ratings.title END
`

type AddPageRatingParams struct {
	WorkspaceID uuid.UUID
	InboxID     uuid.UUID
	ChannelID   uuid.UUID
	Page        string
	Title       string
	Day         time.Time
	Up          int32
	Down        int32
}

func (q *Queries) AddPageRating(ctx context.Context, arg AddPageRatingParams) error {
	_, err := q.db.Exec(ctx, addPageRating,
		arg.WorkspaceID,
		arg.InboxID,
		arg.ChannelID,
		arg.Page,
		arg.Title,
		arg.Day,
		arg.Up,
		arg.Down,
	)
	return err
}

const conversationHasMemberReply = `-- name: ConversationHasMemberReply :one
SELECT EXISTS (
    SELECT 1 FROM messages
    WHERE workspace_id = $1 AND conversation_id = $2
      AND kind = 'message' AND direction = 'out' AND author_type = 'member' AND NOT draft)::bool
`

type ConversationHasMemberReplyParams struct {
	WorkspaceID    uuid.UUID
	ConversationID uuid.UUID
}

func (q *Queries) ConversationHasMemberReply(ctx context.Context, arg ConversationHasMemberReplyParams) (bool, error) {
	row := q.db.QueryRow(ctx, conversationHasMemberReply, arg.WorkspaceID, arg.ConversationID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const createPageAnswer = `-- name: CreatePageAnswer :one
INSERT INTO page_answers (id, workspace_id, inbox_id, channel_id, page, title, question, answer, member_id,
                          conversation_id, published_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9,
        $10, $11, $11)
RETURNING id, workspace_id, inbox_id, channel_id, page, title, question, answer, member_id, conversation_id, published_at, updated_at
`

type CreatePageAnswerParams struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	InboxID        uuid.UUID
	ChannelID      uuid.UUID
	Page           string
	Title          string
	Question       string
	Answer         string
	MemberID       *uuid.UUID
	ConversationID *uuid.UUID
	Now            time.Time
}

func (q *Queries) CreatePageAnswer(ctx context.Context, arg CreatePageAnswerParams) (PageAnswer, error) {
	row := q.db.QueryRow(ctx, createPageAnswer,
		arg.ID,
		arg.WorkspaceID,
		arg.InboxID,
		arg.ChannelID,
		arg.Page,
		arg.Title,
		arg.Question,
		arg.Answer,
		arg.MemberID,
		arg.ConversationID,
		arg.Now,
	)
	var i PageAnswer
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InboxID,
		&i.ChannelID,
		&i.Page,
		&i.Title,
		&i.Question,
		&i.Answer,
		&i.MemberID,
		&i.ConversationID,
		&i.PublishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePageAnswer = `-- name: DeletePageAnswer :execrows
DELETE FROM page_answers WHERE workspace_id = $1 AND id = $2
`

type DeletePageAnswerParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) DeletePageAnswer(ctx context.Context, arg DeletePageAnswerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePageAnswer, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDocsSummaryCounts = `-- name: GetDocsSummaryCounts :one
WITH visible AS (
    SELECT i.id FROM inboxes i
    WHERE i.workspace_id = $1
      AND ($4::uuid IS NULL OR i.id = $4::uuid)
      AND ($5::bool OR EXISTS (
          SELECT 1 FROM inbox_viewers iv
          WHERE iv.workspace_id = i.workspace_id AND iv.inbox_id = i.id AND iv.viewer_id = $6::uuid))
)
SELECT
    (SELECT count(*) FROM (
        SELECT DISTINCT r.inbox_id, r.page FROM page_ratings r
        WHERE r.workspace_id = $1 AND r.inbox_id IN (SELECT id FROM visible) AND r.day >= $2::date
          AND r.up + r.down > 0) rp)::bigint AS rated_pages,
    (SELECT count(*) FROM page_answers a
     WHERE a.workspace_id = $1 AND a.inbox_id IN (SELECT id FROM visible)
       AND a.published_at >= $3::timestamptz)::bigint AS published_answers
`

type GetDocsSummaryCountsParams struct {
	WorkspaceID uuid.UUID
	Since       time.Time
	SinceAt     time.Time
	InboxID     *uuid.UUID
	AllInboxes  bool
	ViewerID    uuid.UUID
}

type GetDocsSummaryCountsRow struct {
	RatedPages       int64
	PublishedAnswers int64
}

func (q *Queries) GetDocsSummaryCounts(ctx context.Context, arg GetDocsSummaryCountsParams) (GetDocsSummaryCountsRow, error) {
	row := q.db.QueryRow(ctx, getDocsSummaryCounts,
		arg.WorkspaceID,
		arg.Since,
		arg.SinceAt,
		arg.InboxID,
		arg.AllInboxes,
		arg.ViewerID,
	)
	var i GetDocsSummaryCountsRow
	err := row.Scan(&i.RatedPages, &i.PublishedAnswers)
	return i, err
}

const getPageAnswer = `-- name: GetPageAnswer :one
SELECT id, workspace_id, inbox_id, channel_id, page, title, question, answer, member_id, conversation_id, published_at, updated_at FROM page_answers WHERE workspace_id = $1 AND id = $2
`

type GetPageAnswerParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetPageAnswer(ctx context.Context, arg GetPageAnswerParams) (PageAnswer, error) {
	row := q.db.QueryRow(ctx, getPageAnswer, arg.WorkspaceID, arg.ID)
	var i PageAnswer
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InboxID,
		&i.ChannelID,
		&i.Page,
		&i.Title,
		&i.Question,
		&i.Answer,
		&i.MemberID,
		&i.ConversationID,
		&i.PublishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClientPageAnswers = `-- name: ListClientPageAnswers :many
SELECT id, workspace_id, inbox_id, channel_id, page, title, question, answer, member_id, conversation_id, published_at, updated_at FROM page_answers
WHERE workspace_id = $1 AND inbox_id = $2 AND page = $3
ORDER BY published_at DESC, id DESC
LIMIT 100
`

type ListClientPageAnswersParams struct {
	WorkspaceID uuid.UUID
	InboxID     uuid.UUID
	Page        string
}

func (q *Queries) ListClientPageAnswers(ctx context.Context, arg ListClientPageAnswersParams) ([]PageAnswer, error) {
	rows, err := q.db.Query(ctx, listClientPageAnswers, arg.WorkspaceID, arg.InboxID, arg.Page)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PageAnswer
	for rows.Next() {
		var i PageAnswer
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.InboxID,
			&i.ChannelID,
			&i.Page,
			&i.Title,
			&i.Question,
			&i.Answer,
			&i.MemberID,
			&i.ConversationID,
			&i.PublishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocsPages = `-- name: ListDocsPages :many
WITH visible AS (
    SELECT i.id FROM inboxes i
    WHERE i.workspace_id = $1
      AND ($6::uuid IS NULL OR i.id = $6::uuid)
      AND ($7::bool OR EXISTS (
          SELECT 1 FROM inbox_viewers iv
          WHERE iv.workspace_id = i.workspace_id AND iv.inbox_id = i.id AND iv.viewer_id = $8::uuid))
), rated AS (
    SELECT r.inbox_id, r.page, sum(r.up)::bigint AS up, sum(r.down)::bigint AS down
    FROM page_ratings r
    WHERE r.workspace_id = $1 AND r.inbox_id IN (SELECT id FROM visible) AND r.day >= $9::date
      AND ($10::text IS NULL OR r.page = $10::text)
    GROUP BY r.inbox_id, r.page
), opened AS (
    SELECT c.inbox_id, c.page_url AS page,
           count(*) FILTER (WHERE c.kind = 'feedback')::bigint AS open_feedback,
           count(*) FILTER (WHERE c.kind = 'question')::bigint AS open_questions
    FROM conversations c
    WHERE c.workspace_id = $1 AND c.inbox_id IN (SELECT id FROM visible)
      AND c.page_url IS NOT NULL AND c.status = 'open' AND NOT c.spam
      AND ($10::text IS NULL OR c.page_url = $10::text)
    GROUP BY c.inbox_id, c.page_url
), answered AS (
    SELECT a.inbox_id, a.page, count(*)::bigint AS published_answers
    FROM page_answers a
    WHERE a.workspace_id = $1 AND a.inbox_id IN (SELECT id FROM visible)
      AND ($10::text IS NULL OR a.page = $10::text)
    GROUP BY a.inbox_id, a.page
), pages AS (
    SELECT rated.inbox_id, rated.page FROM rated
    UNION SELECT opened.inbox_id, opened.page FROM opened
    UNION SELECT answered.inbox_id, answered.page FROM answered
)
SELECT d.inbox_id, d.page, d.title, d.up, d.down, d.open_feedback, d.open_questions, d.published_answers FROM (
SELECT p.inbox_id::uuid AS inbox_id, p.page::text AS page,
    coalesce(
        (SELECT t.title FROM page_ratings t
         WHERE t.workspace_id = $1 AND t.inbox_id = p.inbox_id AND t.page = p.page AND t.title <> ''
         ORDER BY t.day DESC LIMIT 1),
        (SELECT ct.page_title FROM conversations ct
         WHERE ct.workspace_id = $1 AND ct.inbox_id = p.inbox_id AND ct.page_url = p.page AND ct.page_title <> ''
         ORDER BY ct.created_at DESC LIMIT 1),
        (SELECT at.title FROM page_answers at
         WHERE at.workspace_id = $1 AND at.inbox_id = p.inbox_id AND at.page = p.page AND at.title <> ''
         ORDER BY at.published_at DESC LIMIT 1),
        '')::text AS title,
    coalesce(rated.up, 0)::bigint AS up,
    coalesce(rated.down, 0)::bigint AS down,
    coalesce(opened.open_feedback, 0)::bigint AS open_feedback,
    coalesce(opened.open_questions, 0)::bigint AS open_questions,
    coalesce(answered.published_answers, 0)::bigint AS published_answers
FROM pages p
LEFT JOIN rated ON rated.inbox_id = p.inbox_id AND rated.page = p.page
LEFT JOIN opened ON opened.inbox_id = p.inbox_id AND opened.page = p.page
LEFT JOIN answered ON answered.inbox_id = p.inbox_id AND answered.page = p.page
) d
ORDER BY
    CASE $2::text
        WHEN 'up' THEN d.up
        WHEN 'activity' THEN d.up + d.down + d.open_feedback + d.open_questions
        WHEN 'helpful' THEN CASE WHEN d.up + d.down >= $3::bigint THEN 1 ELSE 0 END
        ELSE d.down
    END DESC,
    CASE WHEN $2::text = 'helpful' THEN d.up::float8 / nullif(d.up + d.down, 0) END DESC NULLS LAST,
    d.up + d.down DESC, d.page, d.inbox_id
LIMIT $5 OFFSET $4
`

type ListDocsPagesParams struct {
	WorkspaceID uuid.UUID
	Sort        string
	HelpfulMin  int64
	Off         int32
	Lim         int32
	InboxID     *uuid.UUID
	AllInboxes  bool
	ViewerID    uuid.UUID
	Since       time.Time
	Page        *string
}

type ListDocsPagesRow struct {
	InboxID          uuid.UUID
	Page             string
	Title            string
	Up               int64
	Down             int64
	OpenFeedback     int64
	OpenQuestions    int64
	PublishedAnswers int64
}

func (q *Queries) ListDocsPages(ctx context.Context, arg ListDocsPagesParams) ([]ListDocsPagesRow, error) {
	rows, err := q.db.Query(ctx, listDocsPages,
		arg.WorkspaceID,
		arg.Sort,
		arg.HelpfulMin,
		arg.Off,
		arg.Lim,
		arg.InboxID,
		arg.AllInboxes,
		arg.ViewerID,
		arg.Since,
		arg.Page,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocsPagesRow
	for rows.Next() {
		var i ListDocsPagesRow
		if err := rows.Scan(
			&i.InboxID,
			&i.Page,
			&i.Title,
			&i.Up,
			&i.Down,
			&i.OpenFeedback,
			&i.OpenQuestions,
			&i.PublishedAnswers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocsSummaryDays = `-- name: ListDocsSummaryDays :many
WITH visible AS (
    SELECT i.id FROM inboxes i
    WHERE i.workspace_id = $1
      AND ($2::uuid IS NULL OR i.id = $2::uuid)
      AND ($3::bool OR EXISTS (
          SELECT 1 FROM inbox_viewers iv
          WHERE iv.workspace_id = i.workspace_id AND iv.inbox_id = i.id AND iv.viewer_id = $4::uuid))
), days AS (
    SELECT generate_series($5::date, $6::date, interval '1 day')::date AS day
), rated AS (
    SELECT r.day, sum(r.up)::bigint AS up, sum(r.down)::bigint AS down
    FROM page_ratings r
    WHERE r.workspace_id = $1 AND r.inbox_id IN (SELECT id FROM visible) AND r.day >= $5::date
    GROUP BY r.day
), sent AS (
    SELECT (c.created_at AT TIME ZONE 'UTC')::date AS day,
           count(*) FILTER (WHERE c.kind = 'feedback')::bigint AS feedback,
           count(*) FILTER (WHERE c.kind = 'question')::bigint AS questions
    FROM conversations c
    WHERE c.workspace_id = $1 AND c.inbox_id IN (SELECT id FROM visible)
      AND c.page_url IS NOT NULL AND NOT c.spam AND c.created_at >= $7::timestamptz
    GROUP BY 1
)
SELECT days.day::date AS day,
    coalesce(rated.up, 0)::bigint AS up,
    coalesce(rated.down, 0)::bigint AS down,
    coalesce(sent.feedback, 0)::bigint AS feedback,
    coalesce(sent.questions, 0)::bigint AS questions
FROM days
LEFT JOIN rated ON rated.day = days.day
LEFT JOIN sent ON sent.day = days.day
ORDER BY days.day
`

type ListDocsSummaryDaysParams struct {
	WorkspaceID uuid.UUID
	InboxID     *uuid.UUID
	AllInboxes  bool
	ViewerID    uuid.UUID
	Since       time.Time
	Until       time.Time
	SinceAt     time.Time
}

type ListDocsSummaryDaysRow struct {
	Day       time.Time
	Up        int64
	Down      int64
	Feedback  int64
	Questions int64
}

func (q *Queries) ListDocsSummaryDays(ctx context.Context, arg ListDocsSummaryDaysParams) ([]ListDocsSummaryDaysRow, error) {
	rows, err := q.db.Query(ctx, listDocsSummaryDays,
		arg.WorkspaceID,
		arg.InboxID,
		arg.AllInboxes,
		arg.ViewerID,
		arg.Since,
		arg.Until,
		arg.SinceAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocsSummaryDaysRow
	for rows.Next() {
		var i ListDocsSummaryDaysRow
		if err := rows.Scan(
			&i.Day,
			&i.Up,
			&i.Down,
			&i.Feedback,
			&i.Questions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPageAnswers = `-- name: ListPageAnswers :many
SELECT a.id, a.workspace_id, a.inbox_id, a.channel_id, a.page, a.title, a.question, a.answer, a.member_id, a.conversation_id, a.published_at, a.updated_at FROM page_answers a
WHERE a.workspace_id = $1
  AND ($2::bool OR EXISTS (
      SELECT 1 FROM inbox_viewers iv
      WHERE iv.workspace_id = a.workspace_id AND iv.inbox_id = a.inbox_id AND iv.viewer_id = $3::uuid))
  AND ($4::uuid IS NULL OR a.inbox_id = $4::uuid)
  AND ($5::text IS NULL OR a.page = $5::text)
  AND ($6::uuid IS NULL OR a.conversation_id = $6::uuid)
  AND ($7::timestamptz IS NULL
       OR (a.published_at, a.id) < ($7::timestamptz, $8::uuid))
ORDER BY a.published_at DESC, a.id DESC
LIMIT $9
`

type ListPageAnswersParams struct {
	WorkspaceID    uuid.UUID
	AllInboxes     bool
	ViewerID       uuid.UUID
	InboxID        *uuid.UUID
	Page           *string
	ConversationID *uuid.UUID
	CursorAt       *time.Time
	CursorID       *uuid.UUID
	Lim            int32
}

func (q *Queries) ListPageAnswers(ctx context.Context, arg ListPageAnswersParams) ([]PageAnswer, error) {
	rows, err := q.db.Query(ctx, listPageAnswers,
		arg.WorkspaceID,
		arg.AllInboxes,
		arg.ViewerID,
		arg.InboxID,
		arg.Page,
		arg.ConversationID,
		arg.CursorAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PageAnswer
	for rows.Next() {
		var i PageAnswer
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.InboxID,
			&i.ChannelID,
			&i.Page,
			&i.Title,
			&i.Question,
			&i.Answer,
			&i.MemberID,
			&i.ConversationID,
			&i.PublishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPageRatingDays = `-- name: ListPageRatingDays :many
SELECT day, sum(up)::bigint AS up, sum(down)::bigint AS down
FROM page_ratings
WHERE workspace_id = $1 AND inbox_id = $2 AND page = $3 AND day >= $4::date
GROUP BY day
ORDER BY day
`

type ListPageRatingDaysParams struct {
	WorkspaceID uuid.UUID
	InboxID     uuid.UUID
	Page        string
	Since       time.Time
}

type ListPageRatingDaysRow struct {
	Day  time.Time
	Up   int64
	Down int64
}

func (q *Queries) ListPageRatingDays(ctx context.Context, arg ListPageRatingDaysParams) ([]ListPageRatingDaysRow, error) {
	rows, err := q.db.Query(ctx, listPageRatingDays,
		arg.WorkspaceID,
		arg.InboxID,
		arg.Page,
		arg.Since,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPageRatingDaysRow
	for rows.Next() {
		var i ListPageRatingDaysRow
		if err := rows.Scan(&i.Day, &i.Up, &i.Down); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const takeBackPageRating = `-- name: TakeBackPageRating :exec
UPDATE page_ratings pr SET
    up = pr.up - CASE WHEN $1::bool THEN 1 ELSE 0 END,
    down = pr.down - CASE WHEN $1::bool THEN 0 ELSE 1 END
WHERE pr.workspace_id = $2 AND pr.channel_id = $3 AND pr.page = $4
  AND pr.day = (
      SELECT max(r.day) FROM page_ratings r
      WHERE r.workspace_id = $2 AND r.channel_id = $3 AND r.page = $4
        AND r.day >= $5::date AND CASE WHEN $1::bool THEN r.up > 0 ELSE r.down > 0 END)
`

type TakeBackPageRatingParams struct {
	Up          bool
	WorkspaceID uuid.UUID
	ChannelID   uuid.UUID
	Page        string
	Since       time.Time
}

func (q *Queries) TakeBackPageRating(ctx context.Context, arg TakeBackPageRatingParams) error {
	_, err := q.db.Exec(ctx, takeBackPageRating,
		arg.Up,
		arg.WorkspaceID,
		arg.ChannelID,
		arg.Page,
		arg.Since,
	)
	return err
}

const updatePageAnswer = `-- name: UpdatePageAnswer :one
UPDATE page_answers SET question = $1, answer = $2, updated_at = $3
WHERE workspace_id = $4 AND id = $5
RETURNING id, workspace_id, inbox_id, channel_id, page, title, question, answer, member_id, conversation_id, published_at, updated_at
`

type UpdatePageAnswerParams struct {
	Question    string
	Answer      string
	Now         time.Time
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) UpdatePageAnswer(ctx context.Context, arg UpdatePageAnswerParams) (PageAnswer, error) {
	row := q.db.QueryRow(ctx, updatePageAnswer,
		arg.Question,
		arg.Answer,
		arg.Now,
		arg.WorkspaceID,
		arg.ID,
	)
	var i PageAnswer
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InboxID,
		&i.ChannelID,
		&i.Page,
		&i.Title,
		&i.Question,
		&i.Answer,
		&i.MemberID,
		&i.ConversationID,
		&i.PublishedAt,
		&i.UpdatedAt,
	)
	return i, err
}
