// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: passkeys.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const createPasskey = `-- name: CreatePasskey :one
INSERT INTO passkeys (id, person_id, rp_id, credential_id, name, credential)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, person_id, rp_id, credential_id, name, credential, created_at, last_used_at
`

type CreatePasskeyParams struct {
	ID           uuid.UUID
	PersonID     uuid.UUID
	RpID         string
	CredentialID []byte
	Name         string
	Credential   []byte
}

func (q *Queries) CreatePasskey(ctx context.Context, arg CreatePasskeyParams) (Passkey, error) {
	row := q.db.QueryRow(ctx, createPasskey,
		arg.ID,
		arg.PersonID,
		arg.RpID,
		arg.CredentialID,
		arg.Name,
		arg.Credential,
	)
	var i Passkey
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.RpID,
		&i.CredentialID,
		&i.Name,
		&i.Credential,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const createWebauthnCeremony = `-- name: CreateWebauthnCeremony :exec
INSERT INTO webauthn_ceremonies (id_hash, kind, person_id, session_data, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateWebauthnCeremonyParams struct {
	IDHash      []byte
	Kind        string
	PersonID    *uuid.UUID
	SessionData []byte
	ExpiresAt   time.Time
}

func (q *Queries) CreateWebauthnCeremony(ctx context.Context, arg CreateWebauthnCeremonyParams) error {
	_, err := q.db.Exec(ctx, createWebauthnCeremony,
		arg.IDHash,
		arg.Kind,
		arg.PersonID,
		arg.SessionData,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredWebauthnCeremonies = `-- name: DeleteExpiredWebauthnCeremonies :exec
DELETE FROM webauthn_ceremonies WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredWebauthnCeremonies(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.Exec(ctx, deleteExpiredWebauthnCeremonies, expiresAt)
	return err
}

const deletePasskey = `-- name: DeletePasskey :execrows
DELETE FROM passkeys WHERE person_id = $1 AND id = $2
`

type DeletePasskeyParams struct {
	PersonID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) DeletePasskey(ctx context.Context, arg DeletePasskeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePasskey, arg.PersonID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPasskeys = `-- name: ListPasskeys :many
SELECT id, person_id, rp_id, credential_id, name, credential, created_at, last_used_at FROM passkeys WHERE person_id = $1 AND rp_id = $2 ORDER BY created_at, id
`

type ListPasskeysParams struct {
	PersonID uuid.UUID
	RpID     string
}

func (q *Queries) ListPasskeys(ctx context.Context, arg ListPasskeysParams) ([]Passkey, error) {
	rows, err := q.db.Query(ctx, listPasskeys, arg.PersonID, arg.RpID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Passkey
	for rows.Next() {
		var i Passkey
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.RpID,
			&i.CredentialID,
			&i.Name,
			&i.Credential,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const takeWebauthnCeremony = `-- name: TakeWebauthnCeremony :one
DELETE FROM webauthn_ceremonies WHERE id_hash = $1 AND kind = $2
RETURNING id_hash, kind, person_id, session_data, expires_at
`

type TakeWebauthnCeremonyParams struct {
	IDHash []byte
	Kind   string
}

func (q *Queries) TakeWebauthnCeremony(ctx context.Context, arg TakeWebauthnCeremonyParams) (WebauthnCeremony, error) {
	row := q.db.QueryRow(ctx, takeWebauthnCeremony, arg.IDHash, arg.Kind)
	var i WebauthnCeremony
	err := row.Scan(
		&i.IDHash,
		&i.Kind,
		&i.PersonID,
		&i.SessionData,
		&i.ExpiresAt,
	)
	return i, err
}

const updatePasskeyUse = `-- name: UpdatePasskeyUse :exec
UPDATE passkeys SET credential = $3, last_used_at = $4 WHERE person_id = $1 AND id = $2
`

type UpdatePasskeyUseParams struct {
	PersonID   uuid.UUID
	ID         uuid.UUID
	Credential []byte
	LastUsedAt *time.Time
}

func (q *Queries) UpdatePasskeyUse(ctx context.Context, arg UpdatePasskeyUseParams) error {
	_, err := q.db.Exec(ctx, updatePasskeyUse,
		arg.PersonID,
		arg.ID,
		arg.Credential,
		arg.LastUsedAt,
	)
	return err
}
