// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: people.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const createPerson = `-- name: CreatePerson :one
INSERT INTO people (id, email, name, locale, webauthn_handle) VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, name, locale, webauthn_handle, created_at, availability
`

type CreatePersonParams struct {
	ID             uuid.UUID
	Email          string
	Name           string
	Locale         string
	WebauthnHandle []byte
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, createPerson,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.Locale,
		arg.WebauthnHandle,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Locale,
		&i.WebauthnHandle,
		&i.CreatedAt,
		&i.Availability,
	)
	return i, err
}

const getPerson = `-- name: GetPerson :one
SELECT id, email, name, locale, webauthn_handle, created_at, availability FROM people WHERE id = $1
`

func (q *Queries) GetPerson(ctx context.Context, id uuid.UUID) (Person, error) {
	row := q.db.QueryRow(ctx, getPerson, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Locale,
		&i.WebauthnHandle,
		&i.CreatedAt,
		&i.Availability,
	)
	return i, err
}

const getPersonByEmail = `-- name: GetPersonByEmail :one
SELECT id, email, name, locale, webauthn_handle, created_at, availability FROM people WHERE email = $1
`

func (q *Queries) GetPersonByEmail(ctx context.Context, email string) (Person, error) {
	row := q.db.QueryRow(ctx, getPersonByEmail, email)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Locale,
		&i.WebauthnHandle,
		&i.CreatedAt,
		&i.Availability,
	)
	return i, err
}

const getPersonByWebauthnHandle = `-- name: GetPersonByWebauthnHandle :one
SELECT id, email, name, locale, webauthn_handle, created_at, availability FROM people WHERE webauthn_handle = $1
`

func (q *Queries) GetPersonByWebauthnHandle(ctx context.Context, webauthnHandle []byte) (Person, error) {
	row := q.db.QueryRow(ctx, getPersonByWebauthnHandle, webauthnHandle)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Locale,
		&i.WebauthnHandle,
		&i.CreatedAt,
		&i.Availability,
	)
	return i, err
}

const signInTarget = `-- name: SignInTarget :one
SELECT
    EXISTS (SELECT 1 FROM members m JOIN people p ON p.id = m.person_id WHERE p.email = $1)
    OR EXISTS (SELECT 1 FROM invites i WHERE i.email = $1 AND i.expires_at > $2) AS known
`

type SignInTargetParams struct {
	Email string
	Now   time.Time
}

func (q *Queries) SignInTarget(ctx context.Context, arg SignInTargetParams) (*bool, error) {
	row := q.db.QueryRow(ctx, signInTarget, arg.Email, arg.Now)
	var known *bool
	err := row.Scan(&known)
	return known, err
}

const updatePerson = `-- name: UpdatePerson :one
UPDATE people SET
    name = coalesce($2, name),
    locale = coalesce($3, locale)
WHERE id = $1
RETURNING id, email, name, locale, webauthn_handle, created_at, availability
`

type UpdatePersonParams struct {
	ID     uuid.UUID
	Name   *string
	Locale *string
}

func (q *Queries) UpdatePerson(ctx context.Context, arg UpdatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, updatePerson, arg.ID, arg.Name, arg.Locale)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Locale,
		&i.WebauthnHandle,
		&i.CreatedAt,
		&i.Availability,
	)
	return i, err
}
