// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ratings.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const claimRatingRequest = `-- name: ClaimRatingRequest :one
UPDATE conversations SET rating_requested_at = $1::timestamptz
WHERE workspace_id = $2 AND id = $3 AND status = 'closed' AND closed_at = $4 AND NOT spam
  AND (rating_requested_at IS NULL OR rating_requested_at < closed_at)
  AND (rated_at IS NULL OR rated_at < closed_at)
RETURNING id, workspace_id, inbox_id, contact_id, channel_id, subject, status, snooze_until, priority, assignee_id, last_message_at, last_activity_at, created_at, updated_at, spam, email_token, related_conversation_id, continuity_through, continuity_sent_at, kind, feedback, email_address, closed_at, rating, rating_comment, rated_at, rating_requested_at
`

type ClaimRatingRequestParams struct {
	Now         time.Time
	WorkspaceID uuid.UUID
	ID          uuid.UUID
	ClosedAt    *time.Time
}

func (q *Queries) ClaimRatingRequest(ctx context.Context, arg ClaimRatingRequestParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, claimRatingRequest,
		arg.Now,
		arg.WorkspaceID,
		arg.ID,
		arg.ClosedAt,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InboxID,
		&i.ContactID,
		&i.ChannelID,
		&i.Subject,
		&i.Status,
		&i.SnoozeUntil,
		&i.Priority,
		&i.AssigneeID,
		&i.LastMessageAt,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Spam,
		&i.EmailToken,
		&i.RelatedConversationID,
		&i.ContinuityThrough,
		&i.ContinuitySentAt,
		&i.Kind,
		&i.Feedback,
		&i.EmailAddress,
		&i.ClosedAt,
		&i.Rating,
		&i.RatingComment,
		&i.RatedAt,
		&i.RatingRequestedAt,
	)
	return i, err
}

const conversationHasReply = `-- name: ConversationHasReply :one
SELECT EXISTS (
    SELECT 1 FROM messages
    WHERE workspace_id = $1 AND conversation_id = $2
      AND kind = 'message' AND direction = 'out' AND NOT draft AND author_type IN ('member', 'bot')
) AS replied
`

type ConversationHasReplyParams struct {
	WorkspaceID    uuid.UUID
	ConversationID uuid.UUID
}

func (q *Queries) ConversationHasReply(ctx context.Context, arg ConversationHasReplyParams) (bool, error) {
	row := q.db.QueryRow(ctx, conversationHasReply, arg.WorkspaceID, arg.ConversationID)
	var replied bool
	err := row.Scan(&replied)
	return replied, err
}

const rateConversation = `-- name: RateConversation :one
UPDATE conversations SET rating = $1::text, rating_comment = $2, rated_at = $3::timestamptz, updated_at = $3::timestamptz
WHERE workspace_id = $4 AND id = $5 AND status = 'closed' AND closed_at = $6
  AND (rated_at IS NULL OR rated_at < closed_at)
RETURNING id, workspace_id, inbox_id, contact_id, channel_id, subject, status, snooze_until, priority, assignee_id, last_message_at, last_activity_at, created_at, updated_at, spam, email_token, related_conversation_id, continuity_through, continuity_sent_at, kind, feedback, email_address, closed_at, rating, rating_comment, rated_at, rating_requested_at
`

type RateConversationParams struct {
	Rating      string
	Comment     *string
	Now         time.Time
	WorkspaceID uuid.UUID
	ID          uuid.UUID
	ClosedAt    *time.Time
}

func (q *Queries) RateConversation(ctx context.Context, arg RateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, rateConversation,
		arg.Rating,
		arg.Comment,
		arg.Now,
		arg.WorkspaceID,
		arg.ID,
		arg.ClosedAt,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InboxID,
		&i.ContactID,
		&i.ChannelID,
		&i.Subject,
		&i.Status,
		&i.SnoozeUntil,
		&i.Priority,
		&i.AssigneeID,
		&i.LastMessageAt,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Spam,
		&i.EmailToken,
		&i.RelatedConversationID,
		&i.ContinuityThrough,
		&i.ContinuitySentAt,
		&i.Kind,
		&i.Feedback,
		&i.EmailAddress,
		&i.ClosedAt,
		&i.Rating,
		&i.RatingComment,
		&i.RatedAt,
		&i.RatingRequestedAt,
	)
	return i, err
}

const statsRatings = `-- name: StatsRatings :many
SELECT c.inbox_id, c.rating::text AS rating, count(*) AS n
FROM conversations c
WHERE c.workspace_id = $1 AND c.rated_at >= $2::timestamptz AND c.rated_at <= $3::timestamptz
  AND ($4::uuid IS NULL OR c.inbox_id = $4::uuid)
  AND ($5::bool OR EXISTS (
      SELECT 1 FROM inbox_viewers iv
      WHERE iv.workspace_id = c.workspace_id AND iv.inbox_id = c.inbox_id AND iv.viewer_id = $6::uuid))
GROUP BY 1, 2
ORDER BY 1, 2
`

type StatsRatingsParams struct {
	WorkspaceID uuid.UUID
	Since       time.Time
	Until       time.Time
	InboxID     *uuid.UUID
	AllInboxes  bool
	ViewerID    uuid.UUID
}

type StatsRatingsRow struct {
	InboxID uuid.UUID
	Rating  string
	N       int64
}

func (q *Queries) StatsRatings(ctx context.Context, arg StatsRatingsParams) ([]StatsRatingsRow, error) {
	rows, err := q.db.Query(ctx, statsRatings,
		arg.WorkspaceID,
		arg.Since,
		arg.Until,
		arg.InboxID,
		arg.AllInboxes,
		arg.ViewerID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsRatingsRow
	for rows.Next() {
		var i StatsRatingsRow
		if err := rows.Scan(&i.InboxID, &i.Rating, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
