// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, person_id, token_hash, method, created_at, expires_at, last_seen_at)
VALUES ($1, $2, $3, $4, $5, $6, $5)
`

type CreateSessionParams struct {
	ID        uuid.UUID
	PersonID  uuid.UUID
	TokenHash []byte
	Method    string
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.PersonID,
		arg.TokenHash,
		arg.Method,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, person_id, token_hash, method, created_at, expires_at, last_seen_at FROM sessions WHERE token_hash = $1 AND expires_at > $2
`

type GetSessionByTokenHashParams struct {
	TokenHash []byte
	ExpiresAt time.Time
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, arg GetSessionByTokenHashParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, arg.TokenHash, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.TokenHash,
		&i.Method,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = $1::timestamptz
WHERE id = $2 AND last_seen_at < $3::timestamptz
`

type TouchSessionParams struct {
	Now         time.Time
	ID          uuid.UUID
	StaleBefore time.Time
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.Now, arg.ID, arg.StaleBefore)
	return err
}
