// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const statsClosed = `-- name: StatsClosed :many
SELECT m.author_member_id, count(*) AS n
FROM messages m
JOIN conversations c ON c.workspace_id = m.workspace_id AND c.id = m.conversation_id
WHERE m.workspace_id = $1 AND m.created_at >= $2 AND m.created_at <= $3
  AND m.kind = 'event' AND m.event->>'type' = 'status_changed' AND m.event->>'status' = 'closed'
  AND ($4::uuid IS NULL OR c.inbox_id = $4::uuid)
  AND ($5::bool OR EXISTS (
      SELECT 1 FROM inbox_viewers iv
      WHERE iv.workspace_id = c.workspace_id AND iv.inbox_id = c.inbox_id AND iv.viewer_id = $6::uuid))
GROUP BY 1
`

type StatsClosedParams struct {
	WorkspaceID uuid.UUID
	Since       time.Time
	Until       time.Time
	InboxID     *uuid.UUID
	AllInboxes  bool
	ViewerID    uuid.UUID
}

type StatsClosedRow struct {
	AuthorMemberID *uuid.UUID
	N              int64
}

func (q *Queries) StatsClosed(ctx context.Context, arg StatsClosedParams) ([]StatsClosedRow, error) {
	rows, err := q.db.Query(ctx, statsClosed,
		arg.WorkspaceID,
		arg.Since,
		arg.Until,
		arg.InboxID,
		arg.AllInboxes,
		arg.ViewerID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsClosedRow
	for rows.Next() {
		var i StatsClosedRow
		if err := rows.Scan(&i.AuthorMemberID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsFirstReplies = `-- name: StatsFirstReplies :many
SELECT a.asked_at::timestamptz AS asked_at, min(o.created_at)::timestamptz AS replied_at
FROM (
    SELECT i.conversation_id, min(i.created_at) AS asked_at
    FROM messages i
    WHERE i.workspace_id = $1 AND i.kind = 'message' AND i.direction = 'in'
      AND i.conversation_id IN (
          SELECT m.conversation_id
          FROM messages m
          JOIN conversations c ON c.workspace_id = m.workspace_id AND c.id = m.conversation_id
          WHERE m.workspace_id = $1 AND m.created_at >= $2 AND m.created_at <= $3
            AND m.kind = 'message' AND m.direction = 'out' AND NOT m.draft
            AND (m.author_type = 'member' OR m.sent_by_member_id IS NOT NULL)
            AND ($4::uuid IS NULL OR c.inbox_id = $4::uuid)
            AND ($5::bool OR EXISTS (
                SELECT 1 FROM inbox_viewers iv
                WHERE iv.workspace_id = c.workspace_id AND iv.inbox_id = c.inbox_id AND iv.viewer_id = $6::uuid)))
    GROUP BY i.conversation_id
) a
JOIN messages o ON o.workspace_id = $1 AND o.conversation_id = a.conversation_id
    AND o.kind = 'message' AND o.direction = 'out' AND NOT o.draft
    AND (o.author_type = 'member' OR o.sent_by_member_id IS NOT NULL)
    AND o.created_at > a.asked_at
GROUP BY a.conversation_id, a.asked_at
HAVING min(o.created_at) >= $2 AND min(o.created_at) <= $3
`

type StatsFirstRepliesParams struct {
	WorkspaceID uuid.UUID
	Since       time.Time
	Until       time.Time
	InboxID     *uuid.UUID
	AllInboxes  bool
	ViewerID    uuid.UUID
}

type StatsFirstRepliesRow struct {
	AskedAt   time.Time
	RepliedAt time.Time
}

func (q *Queries) StatsFirstReplies(ctx context.Context, arg StatsFirstRepliesParams) ([]StatsFirstRepliesRow, error) {
	rows, err := q.db.Query(ctx, statsFirstReplies,
		arg.WorkspaceID,
		arg.Since,
		arg.Until,
		arg.InboxID,
		arg.AllInboxes,
		arg.ViewerID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsFirstRepliesRow
	for rows.Next() {
		var i StatsFirstRepliesRow
		if err := rows.Scan(&i.AskedAt, &i.RepliedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsReplies = `-- name: StatsReplies :many
SELECT m.sent_by_member_id, m.author_member_id, count(*) AS n
FROM messages m
JOIN conversations c ON c.workspace_id = m.workspace_id AND c.id = m.conversation_id
WHERE m.workspace_id = $1 AND m.created_at >= $2 AND m.created_at <= $3
  AND m.kind = 'message' AND m.direction = 'out' AND NOT m.draft
  AND (m.author_type = 'member' OR m.sent_by_member_id IS NOT NULL)
  AND ($4::uuid IS NULL OR c.inbox_id = $4::uuid)
  AND ($5::bool OR EXISTS (
      SELECT 1 FROM inbox_viewers iv
      WHERE iv.workspace_id = c.workspace_id AND iv.inbox_id = c.inbox_id AND iv.viewer_id = $6::uuid))
GROUP BY 1, 2
`

type StatsRepliesParams struct {
	WorkspaceID uuid.UUID
	Since       time.Time
	Until       time.Time
	InboxID     *uuid.UUID
	AllInboxes  bool
	ViewerID    uuid.UUID
}

type StatsRepliesRow struct {
	SentByMemberID *uuid.UUID
	AuthorMemberID *uuid.UUID
	N              int64
}

func (q *Queries) StatsReplies(ctx context.Context, arg StatsRepliesParams) ([]StatsRepliesRow, error) {
	rows, err := q.db.Query(ctx, statsReplies,
		arg.WorkspaceID,
		arg.Since,
		arg.Until,
		arg.InboxID,
		arg.AllInboxes,
		arg.ViewerID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsRepliesRow
	for rows.Next() {
		var i StatsRepliesRow
		if err := rows.Scan(&i.SentByMemberID, &i.AuthorMemberID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
