// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const addUsage = `-- name: AddUsage :exec
INSERT INTO usage_counters (workspace_id, month, conversations, messages, attachment_bytes)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (workspace_id, month) DO UPDATE SET
    conversations = usage_counters.conversations + EXCLUDED.conversations,
    messages = usage_counters.messages + EXCLUDED.messages,
    attachment_bytes = usage_counters.attachment_bytes + EXCLUDED.attachment_bytes
`

type AddUsageParams struct {
	WorkspaceID     uuid.UUID
	Month           time.Time
	Conversations   int64
	Messages        int64
	AttachmentBytes int64
}

func (q *Queries) AddUsage(ctx context.Context, arg AddUsageParams) error {
	_, err := q.db.Exec(ctx, addUsage,
		arg.WorkspaceID,
		arg.Month,
		arg.Conversations,
		arg.Messages,
		arg.AttachmentBytes,
	)
	return err
}

const listUsage = `-- name: ListUsage :many
SELECT workspace_id, month, conversations, messages, attachment_bytes FROM usage_counters WHERE workspace_id = $1 ORDER BY month DESC LIMIT 24
`

func (q *Queries) ListUsage(ctx context.Context, workspaceID uuid.UUID) ([]UsageCounter, error) {
	rows, err := q.db.Query(ctx, listUsage, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsageCounter
	for rows.Next() {
		var i UsageCounter
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.Month,
			&i.Conversations,
			&i.Messages,
			&i.AttachmentBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
