// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const contactInboxIDs = `-- name: ContactInboxIDs :many
SELECT x.inbox_id FROM contact_external_ids x WHERE x.workspace_id = $1 AND x.contact_id = $2
UNION
SELECT c.inbox_id FROM conversations c WHERE c.workspace_id = $1 AND c.contact_id = $2
`

type ContactInboxIDsParams struct {
	WorkspaceID uuid.UUID
	ContactID   uuid.UUID
}

func (q *Queries) ContactInboxIDs(ctx context.Context, arg ContactInboxIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, contactInboxIDs, arg.WorkspaceID, arg.ContactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var inbox_id uuid.UUID
		if err := rows.Scan(&inbox_id); err != nil {
			return nil, err
		}
		items = append(items, inbox_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contactLastActivity = `-- name: ContactLastActivity :one
SELECT coalesce(greatest(
    (SELECT max(last_seen_at) FROM contact_sessions s WHERE s.workspace_id = $1 AND s.contact_id = $2),
    (SELECT max(seen_at) FROM realtime_connections rc WHERE rc.workspace_id = $1 AND rc.contact_id = $2)
), 'epoch')::timestamptz AS last_seen
`

type ContactLastActivityParams struct {
	WorkspaceID uuid.UUID
	ContactID   uuid.UUID
}

func (q *Queries) ContactLastActivity(ctx context.Context, arg ContactLastActivityParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, contactLastActivity, arg.WorkspaceID, arg.ContactID)
	var last_seen time.Time
	err := row.Scan(&last_seen)
	return last_seen, err
}

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one
INSERT INTO webhook_deliveries (id, workspace_id, endpoint_id, message_id, event_type, payload, next_attempt_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7::timestamptz, $7::timestamptz, $7::timestamptz)
RETURNING id, workspace_id, endpoint_id, message_id, event_type, payload, state, attempts, next_attempt_at, last_attempt_at, created_at, updated_at
`

type CreateWebhookDeliveryParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	EndpointID  uuid.UUID
	MessageID   string
	EventType   string
	Payload     string
	Now         time.Time
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, createWebhookDelivery,
		arg.ID,
		arg.WorkspaceID,
		arg.EndpointID,
		arg.MessageID,
		arg.EventType,
		arg.Payload,
		arg.Now,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EndpointID,
		&i.MessageID,
		&i.EventType,
		&i.Payload,
		&i.State,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LastAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWebhookEndpoint = `-- name: CreateWebhookEndpoint :one
INSERT INTO webhook_endpoints (id, workspace_id, inbox_id, url, description, events, include_notes, enabled, secret, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $10)
RETURNING id, workspace_id, inbox_id, url, description, events, include_notes, enabled, secret, previous_secret, previous_secret_until, failing_since, disabled_at, disabled_reason, created_at, updated_at
`

type CreateWebhookEndpointParams struct {
	ID           uuid.UUID
	WorkspaceID  uuid.UUID
	InboxID      *uuid.UUID
	Url          string
	Description  string
	Events       []string
	IncludeNotes bool
	Enabled      bool
	Secret       []byte
	Now          time.Time
}

func (q *Queries) CreateWebhookEndpoint(ctx context.Context, arg CreateWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, createWebhookEndpoint,
		arg.ID,
		arg.WorkspaceID,
		arg.InboxID,
		arg.Url,
		arg.Description,
		arg.Events,
		arg.IncludeNotes,
		arg.Enabled,
		arg.Secret,
		arg.Now,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InboxID,
		&i.Url,
		&i.Description,
		&i.Events,
		&i.IncludeNotes,
		&i.Enabled,
		&i.Secret,
		&i.PreviousSecret,
		&i.PreviousSecretUntil,
		&i.FailingSince,
		&i.DisabledAt,
		&i.DisabledReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFinishedWebhookDeliveries = `-- name: DeleteFinishedWebhookDeliveries :execrows
DELETE FROM webhook_deliveries WHERE workspace_id = $1 AND state <> 'pending' AND created_at < $2
`

type DeleteFinishedWebhookDeliveriesParams struct {
	WorkspaceID uuid.UUID
	Before      time.Time
}

func (q *Queries) DeleteFinishedWebhookDeliveries(ctx context.Context, arg DeleteFinishedWebhookDeliveriesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFinishedWebhookDeliveries, arg.WorkspaceID, arg.Before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWebhookEndpoint = `-- name: DeleteWebhookEndpoint :execrows
DELETE FROM webhook_endpoints WHERE workspace_id = $1 AND id = $2
`

type DeleteWebhookEndpointParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) DeleteWebhookEndpoint(ctx context.Context, arg DeleteWebhookEndpointParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebhookEndpoint, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const disableWebhookEndpoint = `-- name: DisableWebhookEndpoint :execrows
UPDATE webhook_endpoints SET enabled = false, disabled_at = $1::timestamptz, disabled_reason = $2, updated_at = $1::timestamptz
WHERE workspace_id = $3 AND id = $4 AND enabled
`

type DisableWebhookEndpointParams struct {
	Now         time.Time
	Reason      *string
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) DisableWebhookEndpoint(ctx context.Context, arg DisableWebhookEndpointParams) (int64, error) {
	result, err := q.db.Exec(ctx, disableWebhookEndpoint,
		arg.Now,
		arg.Reason,
		arg.WorkspaceID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failPendingWebhookDelivery = `-- name: FailPendingWebhookDelivery :exec
UPDATE webhook_deliveries SET state = 'failed', next_attempt_at = NULL, updated_at = $1::timestamptz
WHERE workspace_id = $2 AND id = $3 AND state = 'pending'
`

type FailPendingWebhookDeliveryParams struct {
	Now         time.Time
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) FailPendingWebhookDelivery(ctx context.Context, arg FailPendingWebhookDeliveryParams) error {
	_, err := q.db.Exec(ctx, failPendingWebhookDelivery, arg.Now, arg.WorkspaceID, arg.ID)
	return err
}

const finishWebhookAttempt = `-- name: FinishWebhookAttempt :one
UPDATE webhook_deliveries SET attempts = attempts + 1, last_attempt_at = $1::timestamptz, state = $2,
    next_attempt_at = $3, updated_at = $1::timestamptz
WHERE workspace_id = $4 AND id = $5
RETURNING id, workspace_id, endpoint_id, message_id, event_type, payload, state, attempts, next_attempt_at, last_attempt_at, created_at, updated_at
`

type FinishWebhookAttemptParams struct {
	Now           time.Time
	State         string
	NextAttemptAt *time.Time
	WorkspaceID   uuid.UUID
	ID            uuid.UUID
}

func (q *Queries) FinishWebhookAttempt(ctx context.Context, arg FinishWebhookAttemptParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, finishWebhookAttempt,
		arg.Now,
		arg.State,
		arg.NextAttemptAt,
		arg.WorkspaceID,
		arg.ID,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EndpointID,
		&i.MessageID,
		&i.EventType,
		&i.Payload,
		&i.State,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LastAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEndpointDelivery = `-- name: GetEndpointDelivery :one
SELECT id, workspace_id, endpoint_id, message_id, event_type, payload, state, attempts, next_attempt_at, last_attempt_at, created_at, updated_at FROM webhook_deliveries WHERE workspace_id = $1 AND endpoint_id = $2 AND id = $3
`

type GetEndpointDeliveryParams struct {
	WorkspaceID uuid.UUID
	EndpointID  uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetEndpointDelivery(ctx context.Context, arg GetEndpointDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, getEndpointDelivery, arg.WorkspaceID, arg.EndpointID, arg.ID)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EndpointID,
		&i.MessageID,
		&i.EventType,
		&i.Payload,
		&i.State,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LastAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookDelivery = `-- name: GetWebhookDelivery :one
SELECT id, workspace_id, endpoint_id, message_id, event_type, payload, state, attempts, next_attempt_at, last_attempt_at, created_at, updated_at FROM webhook_deliveries WHERE workspace_id = $1 AND id = $2
`

type GetWebhookDeliveryParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetWebhookDelivery(ctx context.Context, arg GetWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, getWebhookDelivery, arg.WorkspaceID, arg.ID)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EndpointID,
		&i.MessageID,
		&i.EventType,
		&i.Payload,
		&i.State,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LastAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookEndpoint = `-- name: GetWebhookEndpoint :one
SELECT id, workspace_id, inbox_id, url, description, events, include_notes, enabled, secret, previous_secret, previous_secret_until, failing_since, disabled_at, disabled_reason, created_at, updated_at FROM webhook_endpoints WHERE workspace_id = $1 AND id = $2
`

type GetWebhookEndpointParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetWebhookEndpoint(ctx context.Context, arg GetWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, getWebhookEndpoint, arg.WorkspaceID, arg.ID)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InboxID,
		&i.Url,
		&i.Description,
		&i.Events,
		&i.IncludeNotes,
		&i.Enabled,
		&i.Secret,
		&i.PreviousSecret,
		&i.PreviousSecretUntil,
		&i.FailingSince,
		&i.DisabledAt,
		&i.DisabledReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDeliveryAttempts = `-- name: ListDeliveryAttempts :many
SELECT id, workspace_id, endpoint_id, delivery_id, attempted_at, manual, success, status_code, latency_ms, response_body, error FROM webhook_attempts
WHERE workspace_id = $1 AND delivery_id = ANY($2::uuid[])
ORDER BY delivery_id, attempted_at DESC, id DESC
`

type ListDeliveryAttemptsParams struct {
	WorkspaceID uuid.UUID
	DeliveryIds []uuid.UUID
}

func (q *Queries) ListDeliveryAttempts(ctx context.Context, arg ListDeliveryAttemptsParams) ([]WebhookAttempt, error) {
	rows, err := q.db.Query(ctx, listDeliveryAttempts, arg.WorkspaceID, arg.DeliveryIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookAttempt
	for rows.Next() {
		var i WebhookAttempt
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.EndpointID,
			&i.DeliveryID,
			&i.AttemptedAt,
			&i.Manual,
			&i.Success,
			&i.StatusCode,
			&i.LatencyMs,
			&i.ResponseBody,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledWebhookEndpoints = `-- name: ListEnabledWebhookEndpoints :many
SELECT id, workspace_id, inbox_id, url, description, events, include_notes, enabled, secret, previous_secret, previous_secret_until, failing_since, disabled_at, disabled_reason, created_at, updated_at FROM webhook_endpoints WHERE workspace_id = $1 AND enabled ORDER BY created_at, id
`

func (q *Queries) ListEnabledWebhookEndpoints(ctx context.Context, workspaceID uuid.UUID) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, listEnabledWebhookEndpoints, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookEndpoint
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.InboxID,
			&i.Url,
			&i.Description,
			&i.Events,
			&i.IncludeNotes,
			&i.Enabled,
			&i.Secret,
			&i.PreviousSecret,
			&i.PreviousSecretUntil,
			&i.FailingSince,
			&i.DisabledAt,
			&i.DisabledReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookAttempts = `-- name: ListWebhookAttempts :many
SELECT id, workspace_id, endpoint_id, delivery_id, attempted_at, manual, success, status_code, latency_ms, response_body, error FROM webhook_attempts
WHERE workspace_id = $1 AND endpoint_id = $2
ORDER BY attempted_at DESC, id DESC
LIMIT $3
`

type ListWebhookAttemptsParams struct {
	WorkspaceID uuid.UUID
	EndpointID  uuid.UUID
	Lim         int32
}

func (q *Queries) ListWebhookAttempts(ctx context.Context, arg ListWebhookAttemptsParams) ([]WebhookAttempt, error) {
	rows, err := q.db.Query(ctx, listWebhookAttempts, arg.WorkspaceID, arg.EndpointID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookAttempt
	for rows.Next() {
		var i WebhookAttempt
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.EndpointID,
			&i.DeliveryID,
			&i.AttemptedAt,
			&i.Manual,
			&i.Success,
			&i.StatusCode,
			&i.LatencyMs,
			&i.ResponseBody,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveries = `-- name: ListWebhookDeliveries :many
SELECT id, workspace_id, endpoint_id, message_id, event_type, payload, state, attempts, next_attempt_at, last_attempt_at, created_at, updated_at FROM webhook_deliveries d
WHERE d.workspace_id = $1 AND d.endpoint_id = $2
  AND ($3::text IS NULL OR d.state = $3::text)
  AND ($4::timestamptz IS NULL
       OR (d.created_at, d.id) < ($4::timestamptz, $5::uuid))
ORDER BY d.created_at DESC, d.id DESC
LIMIT $6
`

type ListWebhookDeliveriesParams struct {
	WorkspaceID uuid.UUID
	EndpointID  uuid.UUID
	State       *string
	CursorAt    *time.Time
	CursorID    *uuid.UUID
	Lim         int32
}

func (q *Queries) ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveries,
		arg.WorkspaceID,
		arg.EndpointID,
		arg.State,
		arg.CursorAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.EndpointID,
			&i.MessageID,
			&i.EventType,
			&i.Payload,
			&i.State,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastAttemptAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEndpoints = `-- name: ListWebhookEndpoints :many
SELECT id, workspace_id, inbox_id, url, description, events, include_notes, enabled, secret, previous_secret, previous_secret_until, failing_since, disabled_at, disabled_reason, created_at, updated_at FROM webhook_endpoints
WHERE workspace_id = $1 AND ($2::uuid IS NULL OR inbox_id = $2::uuid)
ORDER BY created_at, id
`

type ListWebhookEndpointsParams struct {
	WorkspaceID uuid.UUID
	InboxID     *uuid.UUID
}

func (q *Queries) ListWebhookEndpoints(ctx context.Context, arg ListWebhookEndpointsParams) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, listWebhookEndpoints, arg.WorkspaceID, arg.InboxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookEndpoint
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.InboxID,
			&i.Url,
			&i.Description,
			&i.Events,
			&i.IncludeNotes,
			&i.Enabled,
			&i.Secret,
			&i.PreviousSecret,
			&i.PreviousSecretUntil,
			&i.FailingSince,
			&i.DisabledAt,
			&i.DisabledReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWebhookEndpoint = `-- name: LockWebhookEndpoint :one
SELECT id, workspace_id, inbox_id, url, description, events, include_notes, enabled, secret, previous_secret, previous_secret_until, failing_since, disabled_at, disabled_reason, created_at, updated_at FROM webhook_endpoints WHERE workspace_id = $1 AND id = $2 FOR UPDATE
`

type LockWebhookEndpointParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) LockWebhookEndpoint(ctx context.Context, arg LockWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, lockWebhookEndpoint, arg.WorkspaceID, arg.ID)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InboxID,
		&i.Url,
		&i.Description,
		&i.Events,
		&i.IncludeNotes,
		&i.Enabled,
		&i.Secret,
		&i.PreviousSecret,
		&i.PreviousSecretUntil,
		&i.FailingSince,
		&i.DisabledAt,
		&i.DisabledReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const pruneWebhookAttempts = `-- name: PruneWebhookAttempts :exec
DELETE FROM webhook_attempts w WHERE w.workspace_id = $1 AND w.endpoint_id = $2 AND w.id IN (
    SELECT a.id FROM webhook_attempts a
    WHERE a.workspace_id = $1 AND a.endpoint_id = $2
    ORDER BY a.attempted_at DESC, a.id DESC
    OFFSET $3)
`

type PruneWebhookAttemptsParams struct {
	WorkspaceID uuid.UUID
	EndpointID  uuid.UUID
	Offset      int32
}

func (q *Queries) PruneWebhookAttempts(ctx context.Context, arg PruneWebhookAttemptsParams) error {
	_, err := q.db.Exec(ctx, pruneWebhookAttempts, arg.WorkspaceID, arg.EndpointID, arg.Offset)
	return err
}

const recordWebhookAttempt = `-- name: RecordWebhookAttempt :exec
INSERT INTO webhook_attempts (id, workspace_id, endpoint_id, delivery_id, attempted_at, manual, success, status_code,
                              latency_ms, response_body, error)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        $9, $10, $11)
`

type RecordWebhookAttemptParams struct {
	ID           uuid.UUID
	WorkspaceID  uuid.UUID
	EndpointID   uuid.UUID
	DeliveryID   uuid.UUID
	AttemptedAt  time.Time
	Manual       bool
	Success      bool
	StatusCode   *int32
	LatencyMs    int32
	ResponseBody string
	Error        *string
}

func (q *Queries) RecordWebhookAttempt(ctx context.Context, arg RecordWebhookAttemptParams) error {
	_, err := q.db.Exec(ctx, recordWebhookAttempt,
		arg.ID,
		arg.WorkspaceID,
		arg.EndpointID,
		arg.DeliveryID,
		arg.AttemptedAt,
		arg.Manual,
		arg.Success,
		arg.StatusCode,
		arg.LatencyMs,
		arg.ResponseBody,
		arg.Error,
	)
	return err
}

const rotateWebhookSecret = `-- name: RotateWebhookSecret :one
UPDATE webhook_endpoints SET previous_secret = secret, previous_secret_until = $1, secret = $2, updated_at = $3
WHERE workspace_id = $4 AND id = $5
RETURNING id, workspace_id, inbox_id, url, description, events, include_notes, enabled, secret, previous_secret, previous_secret_until, failing_since, disabled_at, disabled_reason, created_at, updated_at
`

type RotateWebhookSecretParams struct {
	PreviousUntil *time.Time
	Secret        []byte
	Now           time.Time
	WorkspaceID   uuid.UUID
	ID            uuid.UUID
}

func (q *Queries) RotateWebhookSecret(ctx context.Context, arg RotateWebhookSecretParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, rotateWebhookSecret,
		arg.PreviousUntil,
		arg.Secret,
		arg.Now,
		arg.WorkspaceID,
		arg.ID,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InboxID,
		&i.Url,
		&i.Description,
		&i.Events,
		&i.IncludeNotes,
		&i.Enabled,
		&i.Secret,
		&i.PreviousSecret,
		&i.PreviousSecretUntil,
		&i.FailingSince,
		&i.DisabledAt,
		&i.DisabledReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWebhookEndpoint = `-- name: UpdateWebhookEndpoint :one
UPDATE webhook_endpoints SET url = $1, description = $2, events = $3, include_notes = $4,
    enabled = $5,
    disabled_at = CASE WHEN $5::bool THEN NULL ELSE disabled_at END,
    disabled_reason = CASE WHEN $5::bool THEN NULL ELSE disabled_reason END,
    failing_since = CASE WHEN $5::bool AND NOT enabled THEN NULL ELSE failing_since END,
    updated_at = $6
WHERE workspace_id = $7 AND id = $8
RETURNING id, workspace_id, inbox_id, url, description, events, include_notes, enabled, secret, previous_secret, previous_secret_until, failing_since, disabled_at, disabled_reason, created_at, updated_at
`

type UpdateWebhookEndpointParams struct {
	Url          string
	Description  string
	Events       []string
	IncludeNotes bool
	Enabled      bool
	Now          time.Time
	WorkspaceID  uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) UpdateWebhookEndpoint(ctx context.Context, arg UpdateWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, updateWebhookEndpoint,
		arg.Url,
		arg.Description,
		arg.Events,
		arg.IncludeNotes,
		arg.Enabled,
		arg.Now,
		arg.WorkspaceID,
		arg.ID,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InboxID,
		&i.Url,
		&i.Description,
		&i.Events,
		&i.IncludeNotes,
		&i.Enabled,
		&i.Secret,
		&i.PreviousSecret,
		&i.PreviousSecretUntil,
		&i.FailingSince,
		&i.DisabledAt,
		&i.DisabledReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const webhookFailed = `-- name: WebhookFailed :one
UPDATE webhook_endpoints SET failing_since = coalesce(failing_since, $1::timestamptz)
WHERE workspace_id = $2 AND id = $3
RETURNING failing_since::timestamptz AS failing_since, enabled
`

type WebhookFailedParams struct {
	Now         time.Time
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

type WebhookFailedRow struct {
	FailingSince time.Time
	Enabled      bool
}

func (q *Queries) WebhookFailed(ctx context.Context, arg WebhookFailedParams) (WebhookFailedRow, error) {
	row := q.db.QueryRow(ctx, webhookFailed, arg.Now, arg.WorkspaceID, arg.ID)
	var i WebhookFailedRow
	err := row.Scan(&i.FailingSince, &i.Enabled)
	return i, err
}

const webhookSucceeded = `-- name: WebhookSucceeded :exec
UPDATE webhook_endpoints SET failing_since = NULL WHERE workspace_id = $1 AND id = $2
`

type WebhookSucceededParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) WebhookSucceeded(ctx context.Context, arg WebhookSucceededParams) error {
	_, err := q.db.Exec(ctx, webhookSucceeded, arg.WorkspaceID, arg.ID)
	return err
}

const workspaceHasWebhooks = `-- name: WorkspaceHasWebhooks :one
SELECT EXISTS (SELECT 1 FROM webhook_endpoints WHERE workspace_id = $1 AND enabled) AS found
`

func (q *Queries) WorkspaceHasWebhooks(ctx context.Context, workspaceID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, workspaceHasWebhooks, workspaceID)
	var found bool
	err := row.Scan(&found)
	return found, err
}
