// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const countWorkspaceConversations = `-- name: CountWorkspaceConversations :one
SELECT count(*) FROM conversations WHERE workspace_id = $1
`

func (q *Queries) CountWorkspaceConversations(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkspaceConversations, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkspaces = `-- name: CountWorkspaces :one
SELECT count(*) FROM workspaces
`

func (q *Queries) CountWorkspaces(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkspaces)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (id, name) VALUES ($1, $2)
RETURNING id, name, created_at, retention_days, deleted_at, bots_may_send
`

type CreateWorkspaceParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.ID, arg.Name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.RetentionDays,
		&i.DeletedAt,
		&i.BotsMaySend,
	)
	return i, err
}

const deleteLonelyMembersPushSubscriptions = `-- name: DeleteLonelyMembersPushSubscriptions :execrows
DELETE FROM push_subscriptions ps
WHERE ps.person_id IN (SELECT m.person_id FROM members m WHERE m.workspace_id = $1)
  AND NOT EXISTS (
      SELECT 1 FROM members o JOIN workspaces w ON w.id = o.workspace_id
      WHERE o.person_id = ps.person_id AND o.workspace_id <> $1 AND w.deleted_at IS NULL
  )
`

// Push subscriptions belong to a person (see "Hosting for others later"): those of members who
// are left with no other workspace go with the workspace.
func (q *Queries) DeleteLonelyMembersPushSubscriptions(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLonelyMembersPushSubscriptions, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWorkspaceContacts = `-- name: DeleteWorkspaceContacts :execrows
DELETE FROM contacts c WHERE c.workspace_id = $1
  AND c.id IN (SELECT x.id FROM contacts x WHERE x.workspace_id = $1 LIMIT $2)
`

type DeleteWorkspaceContactsParams struct {
	WorkspaceID uuid.UUID
	MaxRows     int32
}

func (q *Queries) DeleteWorkspaceContacts(ctx context.Context, arg DeleteWorkspaceContactsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkspaceContacts, arg.WorkspaceID, arg.MaxRows)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWorkspaceWebhookEndpoints = `-- name: DeleteWorkspaceWebhookEndpoints :execrows
DELETE FROM webhook_endpoints WHERE workspace_id = $1
`

func (q *Queries) DeleteWorkspaceWebhookEndpoints(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkspaceWebhookEndpoints, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDeletedWorkspace = `-- name: GetDeletedWorkspace :one
SELECT id, name, created_at, retention_days, deleted_at, bots_may_send FROM workspaces WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) GetDeletedWorkspace(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getDeletedWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.RetentionDays,
		&i.DeletedAt,
		&i.BotsMaySend,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, created_at, retention_days, deleted_at, bots_may_send FROM workspaces WHERE id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.RetentionDays,
		&i.DeletedAt,
		&i.BotsMaySend,
	)
	return i, err
}

const isWorkspaceLive = `-- name: IsWorkspaceLive :one
SELECT EXISTS (SELECT 1 FROM workspaces WHERE id = $1 AND deleted_at IS NULL) AS live
`

func (q *Queries) IsWorkspaceLive(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isWorkspaceLive, id)
	var live bool
	err := row.Scan(&live)
	return live, err
}

const listDeletedWorkspaceIDs = `-- name: ListDeletedWorkspaceIDs :many
SELECT id FROM workspaces WHERE deleted_at IS NOT NULL ORDER BY deleted_at, id
`

func (q *Queries) ListDeletedWorkspaceIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listDeletedWorkspaceIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnedWorkspaces = `-- name: ListOwnedWorkspaces :many
SELECT w.id, w.name FROM members m JOIN workspaces w ON w.id = m.workspace_id
WHERE m.person_id = $1 AND m.role = 'owner' AND w.deleted_at IS NULL
ORDER BY w.id
`

type ListOwnedWorkspacesRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) ListOwnedWorkspaces(ctx context.Context, personID uuid.UUID) ([]ListOwnedWorkspacesRow, error) {
	rows, err := q.db.Query(ctx, listOwnedWorkspaces, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOwnedWorkspacesRow
	for rows.Next() {
		var i ListOwnedWorkspacesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceConversationIDs = `-- name: ListWorkspaceConversationIDs :many
SELECT id FROM conversations WHERE workspace_id = $1 ORDER BY id LIMIT $2
`

type ListWorkspaceConversationIDsParams struct {
	WorkspaceID uuid.UUID
	MaxRows     int32
}

func (q *Queries) ListWorkspaceConversationIDs(ctx context.Context, arg ListWorkspaceConversationIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listWorkspaceConversationIDs, arg.WorkspaceID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceIDs = `-- name: ListWorkspaceIDs :many
SELECT id FROM workspaces ORDER BY id
`

func (q *Queries) ListWorkspaceIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listWorkspaceIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceRetention = `-- name: ListWorkspaceRetention :many
SELECT id, retention_days::integer AS retention_days FROM workspaces WHERE retention_days IS NOT NULL ORDER BY id
`

type ListWorkspaceRetentionRow struct {
	ID            uuid.UUID
	RetentionDays int32
}

func (q *Queries) ListWorkspaceRetention(ctx context.Context) ([]ListWorkspaceRetentionRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceRetention)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkspaceRetentionRow
	for rows.Next() {
		var i ListWorkspaceRetentionRow
		if err := rows.Scan(&i.ID, &i.RetentionDays); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesByName = `-- name: ListWorkspacesByName :many
SELECT id, name, created_at, retention_days, deleted_at, bots_may_send FROM workspaces WHERE name = $1 AND deleted_at IS NULL ORDER BY created_at, id
`

func (q *Queries) ListWorkspacesByName(ctx context.Context, name string) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspacesByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.RetentionDays,
			&i.DeletedAt,
			&i.BotsMaySend,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBootstrap = `-- name: LockBootstrap :exec
SELECT pg_advisory_xact_lock(hashtext('yuva.bootstrap'))
`

func (q *Queries) LockBootstrap(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockBootstrap)
	return err
}

const lockWorkspace = `-- name: LockWorkspace :one
SELECT id FROM workspaces WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockWorkspace(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockWorkspace, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const markWorkspaceDeleted = `-- name: MarkWorkspaceDeleted :execrows
UPDATE workspaces SET deleted_at = $1 WHERE id = $2 AND deleted_at IS NULL
`

type MarkWorkspaceDeletedParams struct {
	Now *time.Time
	ID  uuid.UUID
}

func (q *Queries) MarkWorkspaceDeleted(ctx context.Context, arg MarkWorkspaceDeletedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markWorkspaceDeleted, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeWorkspace = `-- name: PurgeWorkspace :execrows
DELETE FROM workspaces WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) PurgeWorkspace(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, purgeWorkspace, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setWorkspaceBotsMaySend = `-- name: SetWorkspaceBotsMaySend :one
UPDATE workspaces SET bots_may_send = $1
WHERE id = $2
RETURNING id, name, created_at, retention_days, deleted_at, bots_may_send
`

type SetWorkspaceBotsMaySendParams struct {
	BotsMaySend bool
	ID          uuid.UUID
}

func (q *Queries) SetWorkspaceBotsMaySend(ctx context.Context, arg SetWorkspaceBotsMaySendParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, setWorkspaceBotsMaySend, arg.BotsMaySend, arg.ID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.RetentionDays,
		&i.DeletedAt,
		&i.BotsMaySend,
	)
	return i, err
}

const setWorkspaceRetention = `-- name: SetWorkspaceRetention :one
UPDATE workspaces SET retention_days = $1
WHERE id = $2
RETURNING id, name, created_at, retention_days, deleted_at, bots_may_send
`

type SetWorkspaceRetentionParams struct {
	RetentionDays *int32
	ID            uuid.UUID
}

func (q *Queries) SetWorkspaceRetention(ctx context.Context, arg SetWorkspaceRetentionParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, setWorkspaceRetention, arg.RetentionDays, arg.ID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.RetentionDays,
		&i.DeletedAt,
		&i.BotsMaySend,
	)
	return i, err
}
