// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package store

import (
	"context"

	"uuid"
)

const countWorkspaces = `-- name: CountWorkspaces :one
SELECT count(*) FROM workspaces
`

func (q *Queries) CountWorkspaces(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkspaces)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (id, name) VALUES ($1, $2)
RETURNING id, name, created_at
`

type CreateWorkspaceParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.ID, arg.Name)
	var i Workspace
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, created_at FROM workspaces WHERE id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const lockBootstrap = `-- name: LockBootstrap :exec
SELECT pg_advisory_xact_lock(hashtext('yuva.bootstrap'))
`

func (q *Queries) LockBootstrap(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockBootstrap)
	return err
}

const lockWorkspace = `-- name: LockWorkspace :one
SELECT id FROM workspaces WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockWorkspace(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockWorkspace, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}
