// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package store

import (
	"context"

	"uuid"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (id, name) VALUES ($1, $2)
RETURNING id, name, created_at
`

type CreateWorkspaceParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.ID, arg.Name)
	var i Workspace
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, created_at FROM workspaces WHERE id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
