package: oas
output: oas.gen.go
generate:
  models: true
  std-http-server: true
  strict-server: true
output-options:
  skip-prune: true
  exclude-operation-ids: [realtime, clientRealtime, ingestEmail, ingestSes]
  nullable-type: true
  type-mapping:
    string:
      formats:
        uuid:
          type: uuid.UUID
          import: uuid
